Temperature Control System: IndicatorInterface Class Reference
IndicatorInterface Class Reference
Interface class for PCF8575 I/O expander and OLED display.
#include <IndicatorInterface.h>
Data Structures
struct BlinkingPort
Structure for managing blinking port states.
Public Member Functions
IndicatorInterface (TwoWire &i2cBus, uint8_t pcf_i2cAddress, int intPin=-1)
Constructor for IndicatorInterface.
~IndicatorInterface ()
Destructor for IndicatorInterface.
bool begin ()
Initialize the indicator interface.
void update ()
Update interface state (call in main loop)
void setDirection (uint16_t directionMask)
Set port directions for all 16 ports.
void setMode (uint16_t modeMask)
Set port inversion mode for all 16 ports.
void setPortNames (const std::map< std::string, uint8_t > &portNames)
Set names for multiple ports.
void setPortName (const std::string &name, uint8_t portNumber)
Set name for a single port.
bool writePort (const std::string &portName, bool state)
Write state to a named port.
bool writePort (uint8_t portNumber, bool state)
Write state to a numbered port.
void writePorts (uint16_t portMask)
Write states to multiple ports simultaneously.
void setAllOutputs (bool state)
Set all output ports to specified state.
void setAllOutputsHigh ()
Set all output ports to high state.
void setAllOutputsLow ()
Set all output ports to low state.
void setPortInverted (const std::string &portName, bool inverted)
Set inversion mode for a named port.
void setPortInverted (uint8_t portNumber, bool inverted)
Set inversion mode for a numbered port.
uint16_t getCurrentState ()
Get current state of all 16 ports.
bool readPort (const std::string &portName)
Read state of a named port.
bool readPort (uint8_t portNumber)
Read state of a numbered port.
bool isOutput (uint8_t portNumber)
Check if port is configured as output.
bool isInput (uint8_t portNumber)
Check if port is configured as input.
bool isInverted (uint8_t portNumber)
Check if port has inverted logic.
uint8_t getPortNumber (const std::string &portName)
Get port number from port name.
std::string getPortName (uint8_t portNumber)
Get port name from port number.
void handleInterrupt ()
Handle interrupt from PCF8575.
void setInterruptCallback (void(*callback)(uint16_t currentState, uint16_t changedPins))
Set callback function for port change interrupts.
void printPortStates ()
Print current state of all ports to Serial.
void printConfiguration ()
Print complete port configuration to Serial.
void setOledSleepDelay (long sleepDelay)
Set OLED sleep delay.
void setOledMode (int lines)
Set OLED display mode.
void printText (String buffer[], int bufferSize)
Display text buffer on OLED.
void setOLEDblink (int timeOn, int timeOff, bool blinkOn=true)
Set OLED blinking mode.
void setOLEDOff ()
Turn OLED display off.
void setOLEDOn ()
Turn OLED display on.
void updateOLED ()
Update OLED display (call in main loop)
void pushLine (String newLine)
Push new line to display, shifting others down.
void displayOK ()
Display large "OK" symbol.
void displayCross ()
Display large cross/error symbol.
void blinkOK (int blinkDelay)
Blink between OK symbol and previous text.
void blinkCross (int blinkDelay)
Blink between cross symbol and previous text.
void stopBlinking ()
Stop all blinking and restore normal text.
void startBlinking (const std::string &portName, unsigned long onTime, unsigned long offTime)
Start blinking a named port.
void stopBlinking (const std::string &portName)
Stop blinking a named port.
void updateBlinking ()
Update all blinking ports (call in main loop)
bool isBlinking (const std::string &portName)
Check if a port is currently blinking.
Private Member Functions
void _updateState ()
Update internal state from PCF8575.
void _clearInterrupt ()
Clear interrupt flag on PCF8575.
uint16_t _readPCF ()
Read raw state from PCF8575.
void _writePCF (uint16_t state)
Write raw state to PCF8575.
bool _applyModeLogic (uint8_t portNumber, bool state)
Apply inversion logic to port state.
bool _reverseModeLogic (uint8_t portNumber, bool state)
Reverse inversion logic from physical to logical.
void _configureInterruptPin ()
Configure interrupt pin for PCF8575.
void _initOLED ()
Initialize OLED display.
void _updateOLEDDisplay ()
Update OLED display content.
void _handleOLEDSleep ()
Handle OLED sleep management.
void _handleOLEDBlink ()
Handle OLED blinking.
void _handleScrolling ()
Handle text scrolling.
void _drawTextLine (int lineIndex, int yPos)
Draw single text line at specified position.
void _calculateDisplayParams ()
Calculate display parameters.
void _wakeOLED ()
Wake OLED from sleep.
void _saveCurrentText ()
Save current text before displaying special symbols.
void _restoreCurrentText ()
Restore previously saved text.
void _handleSpecialBlink ()
Handle special symbol blinking.
Static Private Member Functions
static void IRAM_ATTR _staticInterruptHandler ()
Static interrupt service routine.
Private Attributes
std::vector< BlinkingPort > _blinkingPorts
Vector of ports configured for blinking.
TwoWire * _i2cBus
Pointer to I2C bus interface.
uint8_t _pcf_i2cAddress
I2C address of PCF8575 expander.
uint8_t oled_i2cAddress
I2C address of OLED display.
int _intPin
GPIO pin for interrupt handling.
PCF8575 _pcf8575
PCF8575 expander instance.
uint16_t _directionMask
Port direction mask (0=input, 1=output)
uint16_t _modeMask
Port inversion mask (0=normal, 1=inverted)
std::map< std::string, uint8_t > _portNames
Map of port names to numbers.
std::map< uint8_t, std::string > _portNumbers
Map of port numbers to names.
uint16_t _currentState
Current state of all 16 ports.
uint16_t _lastState
Previous state for change detection.
unsigned long _lastReadTime
Last time ports were read.
unsigned long _pollInterval
Polling interval for port updates.
volatile bool _interruptFlag
Flag set by interrupt handler.
bool _useInterrupts
Whether interrupts are enabled.
void(* _interruptCallback)(uint16_t currentState, uint16_t changedPins)
User callback function.
long _oledSleepDelay
Sleep delay in milliseconds (-1 = never sleep)
int _oledLines
Number of display lines (1-5)
String _textBuffer [5]
Text buffer for display (max 5 lines)
int _textBufferSize
Current number of lines in buffer.
bool _oledOn
OLED power state.
bool _oledBlink
Whether OLED is blinking.
int _blinkTimeOn
Milliseconds OLED stays on during blink.
int _blinkTimeOff
Milliseconds OLED stays off during blink.
unsigned long _lastBlinkTime
Last blink toggle time.
bool _blinkState
Current blink state (on/off)
unsigned long _lastActivityTime
Last user activity time.
bool _oledSleeping
Whether OLED is currently sleeping.
int _scrollOffset [5]
Horizontal scroll offset for each line.
unsigned long _lastScrollTime
Last scroll update time.
int _scrollDelay
Delay between scroll steps.
int _charWidth
Width of characters in pixels.
int _lineHeight
Height of lines in pixels.
int _maxCharsPerLine
Maximum characters per display line.
String _savedTextBuffer [5]
Backup of text before OK/Cross display.
int _savedTextBufferSize
Size of saved text buffer.
int _savedOledLines
Saved number of display lines.
bool _isBlinkingOK
Whether currently blinking OK symbol.
bool _isBlinkingCross
Whether currently blinking cross symbol.
int _blinkDelayTime
Delay time for special symbol blinking.
unsigned long _lastBlinkToggle
Last toggle time for special blinking.
bool _blinkShowSpecial
Current blink state (true=symbol, false=text)
Static Private Attributes
static IndicatorInterface * _instance = nullptr
Static instance for interrupt callback.
static U8G2_SH1106_128X64_NONAME_F_HW_I2C u8g2
Static OLED display instance.
Detailed Description
Interface class for PCF8575 I/O expander and OLED display.
Provides comprehensive control over 16-bit I/O expander with named ports, interrupt handling, blinking control, and OLED display management
Definition at line 37 of file IndicatorInterface.h.
Constructor & Destructor Documentation
IndicatorInterface()
IndicatorInterface::IndicatorInterface (TwoWire & i2cBus, uint8_t pcf_i2cAddress, int intPin = -1)
Constructor for IndicatorInterface.
Parameters
[in] i2cBus Reference to I2C bus (Wire)
[in] pcf_i2cAddress I2C address of PCF8575 expander
[in] intPin GPIO pin for interrupt handling (-1 to disable)
Initializes I/O expander and OLED display interfaces
Definition at line 28 of file IndicatorInterface.cpp.
References _blinkDelayTime, _blinkShowSpecial, _blinkState, _blinkTimeOff, _blinkTimeOn, _charWidth, _currentState, _directionMask, _i2cBus, _instance, _interruptCallback, _interruptFlag, _intPin, _isBlinkingCross, _isBlinkingOK, _lastActivityTime, _lastBlinkTime, _lastBlinkToggle, _lastReadTime, _lastScrollTime, _lastState, _lineHeight, _maxCharsPerLine, _modeMask, _oledBlink, _oledLines, _oledOn, _oledSleepDelay, _oledSleeping, _pcf8575, _pcf_i2cAddress, _pollInterval, _savedOledLines, _savedTextBufferSize, _scrollDelay, _scrollOffset, _textBufferSize, and _useInterrupts.
~IndicatorInterface()
IndicatorInterface::~IndicatorInterface ()
Destructor for IndicatorInterface.
Cleans up resources and disables interrupts
Definition at line 56 of file IndicatorInterface.cpp.
References _instance, _intPin, and _useInterrupts.
Member Function Documentation
_applyModeLogic()
bool IndicatorInterface::_applyModeLogic (uint8_t portNumber, bool state) private
Apply inversion logic to port state.
Parameters
[in] portNumber Port number (0-15)
[in] state Logical state
Returns
bool Physical state after inversion logic
Definition at line 390 of file IndicatorInterface.cpp.
References isInverted().
Referenced by setAllOutputs(), writePort(), and writePorts().
_calculateDisplayParams()
void IndicatorInterface::_calculateDisplayParams () private
Calculate display parameters.
Computes character dimensions and layout parameters
Definition at line 531 of file IndicatorInterface.cpp.
References _charWidth, _lineHeight, _maxCharsPerLine, _oledLines, and u8g2.
Referenced by _initOLED(), _updateOLEDDisplay(), and setOledMode().
_clearInterrupt()
void IndicatorInterface::_clearInterrupt () private
Clear interrupt flag on PCF8575.
Resets interrupt condition by reading ports
Definition at line 373 of file IndicatorInterface.cpp.
References _pcf8575.
Referenced by _writePCF(), and begin().
_configureInterruptPin()
void IndicatorInterface::_configureInterruptPin () private
Configure interrupt pin for PCF8575.
Sets up GPIO pin for interrupt handling
Definition at line 96 of file IndicatorInterface.cpp.
References _intPin, and _staticInterruptHandler().
Referenced by begin().
_drawTextLine()
void IndicatorInterface::_drawTextLine (int lineIndex, int yPos) private
Draw single text line at specified position.
Draw a single text line with circular scrolling support.
Parameters
[in] lineIndex Index of line in text buffer
[in] yPos Vertical position in pixels
[in] lineIndex Index of the line to draw (0-4)
[in] yPos Y position on the display
Implements circular scrolling for text longer than display width. Text continuously loops with a 3-space separator between end and beginning.
Definition at line 659 of file IndicatorInterface.cpp.
References _scrollOffset, _textBuffer, _textBufferSize, and u8g2.
Referenced by _updateOLEDDisplay().
_handleOLEDBlink()
void IndicatorInterface::_handleOLEDBlink () private
Handle OLED blinking.
Manages display on/off timing for blink mode
Definition at line 705 of file IndicatorInterface.cpp.
References _blinkState, _blinkTimeOff, _blinkTimeOn, _lastBlinkTime, _oledBlink, _oledSleeping, _updateOLEDDisplay(), and u8g2.
Referenced by updateOLED().
_handleOLEDSleep()
void IndicatorInterface::_handleOLEDSleep () private
Handle OLED sleep management.
Manages automatic sleep based on activity timeout
Definition at line 696 of file IndicatorInterface.cpp.
References _lastActivityTime, _oledSleepDelay, _oledSleeping, and u8g2.
Referenced by updateOLED().
_handleScrolling()
void IndicatorInterface::_handleScrolling () private
Handle text scrolling.
Handle circular scrolling animation for all text lines.
Updates horizontal scroll position for long text lines
Updates scroll offsets for lines longer than display width. Implements seamless circular scrolling where text wraps around continuously.
Definition at line 730 of file IndicatorInterface.cpp.
References _lastScrollTime, _scrollDelay, _scrollOffset, _textBuffer, _textBufferSize, _updateOLEDDisplay(), and u8g2.
Referenced by updateOLED().
_handleSpecialBlink()
void IndicatorInterface::_handleSpecialBlink () private
Handle special symbol blinking.
Manages alternation between special symbols and saved text
Definition at line 981 of file IndicatorInterface.cpp.
References _blinkDelayTime, _blinkShowSpecial, _isBlinkingCross, _isBlinkingOK, _lastBlinkToggle, _restoreCurrentText(), displayCross(), and displayOK().
Referenced by updateOLED().
_initOLED()
void IndicatorInterface::_initOLED () private
Initialize OLED display.
Sets up SH1106 display and calculates display parameters
Definition at line 425 of file IndicatorInterface.cpp.
References _calculateDisplayParams(), _lastActivityTime, and u8g2.
Referenced by begin().
_readPCF()
uint16_t IndicatorInterface::_readPCF () private
Read raw state from PCF8575.
Returns
uint16_t Raw 16-bit port state
Definition at line 379 of file IndicatorInterface.cpp.
References _pcf8575.
Referenced by _updateState(), and begin().
_restoreCurrentText()
void IndicatorInterface::_restoreCurrentText () private
Restore previously saved text.
Restores display state from before special symbol display
Definition at line 970 of file IndicatorInterface.cpp.
References _oledLines, _savedOledLines, _savedTextBuffer, _savedTextBufferSize, _textBuffer, _textBufferSize, and _updateOLEDDisplay().
Referenced by _handleSpecialBlink(), and stopBlinking().
_reverseModeLogic()
bool IndicatorInterface::_reverseModeLogic (uint8_t portNumber, bool state) private
Reverse inversion logic from physical to logical.
Parameters
[in] portNumber Port number (0-15)
[in] state Physical state
Returns
bool Logical state after reversing inversion
Definition at line 395 of file IndicatorInterface.cpp.
References isInverted().
Referenced by printPortStates(), and readPort().
_saveCurrentText()
void IndicatorInterface::_saveCurrentText () private
Save current text before displaying special symbols.
Backs up current display state for later restoration
Definition at line 961 of file IndicatorInterface.cpp.
References _oledLines, _savedOledLines, _savedTextBuffer, _savedTextBufferSize, _textBuffer, and _textBufferSize.
Referenced by blinkCross(), and blinkOK().
_staticInterruptHandler()
void IRAM_ATTR IndicatorInterface::_staticInterruptHandler () static private
Static interrupt service routine.
IRAM-resident ISR for handling PCF8575 interrupts
Definition at line 400 of file IndicatorInterface.cpp.
References _instance.
Referenced by _configureInterruptPin().
_updateOLEDDisplay()
void IndicatorInterface::_updateOLEDDisplay () private
Update OLED display content.
Redraws display with current text buffer
Definition at line 622 of file IndicatorInterface.cpp.
References _calculateDisplayParams(), _drawTextLine(), _oledLines, _oledOn, _oledSleeping, _textBufferSize, and u8g2.
Referenced by _handleOLEDBlink(), _handleScrolling(), _restoreCurrentText(), printText(), pushLine(), and setOLEDOn().
_updateState()
void IndicatorInterface::_updateState () private
Update internal state from PCF8575.
Reads current port states and detects changes
Definition at line 359 of file IndicatorInterface.cpp.
References _currentState, _interruptCallback, _lastReadTime, _lastState, and _readPCF().
Referenced by getCurrentState(), and handleInterrupt().
_wakeOLED()
void IndicatorInterface::_wakeOLED () private
Wake OLED from sleep.
Powers up display and resets activity timer
Definition at line 769 of file IndicatorInterface.cpp.
References _lastActivityTime, _oledOn, _oledSleeping, and u8g2.
Referenced by displayCross(), displayOK(), handleInterrupt(), printText(), pushLine(), setOLEDblink(), setOledMode(), setOLEDOn(), and setOledSleepDelay().
_writePCF()
void IndicatorInterface::_writePCF (uint16_t state) private
Write raw state to PCF8575.
Parameters
[in] state 16-bit state to write
Definition at line 383 of file IndicatorInterface.cpp.
References _clearInterrupt(), _currentState, and _pcf8575.
Referenced by setAllOutputs(), setDirection(), writePort(), and writePorts().
begin()
bool IndicatorInterface::begin ()
Initialize the indicator interface.
Returns
bool True if initialization successful
Sets up PCF8575, OLED display, and interrupt handling
Definition at line 63 of file IndicatorInterface.cpp.
References _clearInterrupt(), _configureInterruptPin(), _currentState, _i2cBus, _initOLED(), _lastReadTime, _lastState, _pcf8575, _readPCF(), _useInterrupts, and u8g2.
blinkCross()
void IndicatorInterface::blinkCross (int blinkDelay)
Blink between cross symbol and previous text.
Parameters
[in] blinkDelay Milliseconds between blink states
Alternates between cross symbol and saved text
Definition at line 940 of file IndicatorInterface.cpp.
References _blinkDelayTime, _blinkShowSpecial, _isBlinkingCross, _isBlinkingOK, _lastBlinkToggle, _oledBlink, _saveCurrentText(), and displayCross().
blinkOK()
void IndicatorInterface::blinkOK (int blinkDelay)
Blink between OK symbol and previous text.
Parameters
[in] blinkDelay Milliseconds between blink states
Alternates between OK symbol and saved text
Definition at line 926 of file IndicatorInterface.cpp.
References _blinkDelayTime, _blinkShowSpecial, _isBlinkingCross, _isBlinkingOK, _lastBlinkToggle, _oledBlink, _saveCurrentText(), and displayOK().
displayCross()
void IndicatorInterface::displayCross ()
Display large cross/error symbol.
Shows error symbol in circle filling the display
Definition at line 847 of file IndicatorInterface.cpp.
References _wakeOLED(), and u8g2.
Referenced by _handleSpecialBlink(), and blinkCross().
displayOK()
void IndicatorInterface::displayOK ()
Display large "OK" symbol.
Shows confirmation symbol filling the display
Definition at line 817 of file IndicatorInterface.cpp.
References _wakeOLED(), and u8g2.
Referenced by _handleSpecialBlink(), and blinkOK().
getCurrentState()
uint16_t IndicatorInterface::getCurrentState ()
Get current state of all 16 ports.
Returns
uint16_t 16-bit value representing all port states
Returns raw port states as read from PCF8575
Definition at line 239 of file IndicatorInterface.cpp.
References _currentState, _lastReadTime, _pollInterval, _updateState(), and _useInterrupts.
Referenced by printPortStates(), and readPort().
getPortName()
std::string IndicatorInterface::getPortName (uint8_t portNumber)
Get port name from port number.
Parameters
[in] portNumber Port number (0-15)
Returns
std::string Port name, empty string if no name assigned
Definition at line 289 of file IndicatorInterface.cpp.
References _portNumbers.
Referenced by printPortStates().
getPortNumber()
uint8_t IndicatorInterface::getPortNumber (const std::string & portName)
Get port number from port name.
Parameters
[in] portName Name of the port
Returns
uint8_t Port number (0-15), 255 if name not found
Definition at line 284 of file IndicatorInterface.cpp.
References _portNames.
handleInterrupt()
void IndicatorInterface::handleInterrupt ()
Handle interrupt from PCF8575.
Called when interrupt pin is triggered, reads and processes port changes
Definition at line 778 of file IndicatorInterface.cpp.
References _interruptFlag, _updateState(), and _wakeOLED().
isBlinking()
bool IndicatorInterface::isBlinking (const std::string & portName)
Check if a port is currently blinking.
Parameters
[in] portName Name of port to check
Returns
bool True if port is actively blinking
Definition at line 1068 of file IndicatorInterface.cpp.
References _blinkingPorts.
isInput()
bool IndicatorInterface::isInput (uint8_t portNumber)
Check if port is configured as input.
Parameters
[in] portNumber Port number (0-15)
Returns
bool True if port is configured as input
Definition at line 276 of file IndicatorInterface.cpp.
References isOutput().
isInverted()
bool IndicatorInterface::isInverted (uint8_t portNumber)
Check if port has inverted logic.
Parameters
[in] portNumber Port number (0-15)
Returns
bool True if port logic is inverted
Definition at line 280 of file IndicatorInterface.cpp.
References _modeMask.
Referenced by _applyModeLogic(), _reverseModeLogic(), and printPortStates().
isOutput()
bool IndicatorInterface::isOutput (uint8_t portNumber)
Check if port is configured as output.
Parameters
[in] portNumber Port number (0-15)
Returns
bool True if port is configured as output
Definition at line 272 of file IndicatorInterface.cpp.
References _directionMask.
Referenced by isInput(), printPortStates(), setAllOutputs(), setDirection(), writePort(), and writePorts().
printConfiguration()
void IndicatorInterface::printConfiguration ()
Print complete port configuration to Serial.
Shows direction, inversion, and name mappings for all ports
Definition at line 336 of file IndicatorInterface.cpp.
References _directionMask, _intPin, _modeMask, _pcf_i2cAddress, _portNames, and _useInterrupts.
printPortStates()
void IndicatorInterface::printPortStates ()
Print current state of all ports to Serial.
Useful for debugging port configurations and states
Definition at line 305 of file IndicatorInterface.cpp.
References _reverseModeLogic(), getCurrentState(), getPortName(), isInverted(), and isOutput().
printText()
void IndicatorInterface::printText (String buffer[], int bufferSize)
Display text buffer on OLED.
Parameters
[in] buffer Array of strings to display
[in] bufferSize Number of strings in buffer
Updates OLED display with provided text
Definition at line 447 of file IndicatorInterface.cpp.
References _lastActivityTime, _scrollOffset, _textBuffer, _textBufferSize, _updateOLEDDisplay(), and _wakeOLED().
pushLine()
void IndicatorInterface::pushLine (String newLine)
Push new line to display, shifting others down.
Parameters
[in] newLine New text line to add at bottom
Adds new line and scrolls existing lines up
Definition at line 792 of file IndicatorInterface.cpp.
References _oledLines, _scrollOffset, _textBuffer, _textBufferSize, _updateOLEDDisplay(), and _wakeOLED().
readPort() [1/2]
bool IndicatorInterface::readPort (const std::string & portName)
Read state of a named port.
Parameters
[in] portName Name of the port to read
Returns
bool Current port state (true=high, false=low)
Reads input port state using human-readable name
Definition at line 252 of file IndicatorInterface.cpp.
References _portNames, and readPort().
Referenced by readPort().
readPort() [2/2]
bool IndicatorInterface::readPort (uint8_t portNumber)
Read state of a numbered port.
Parameters
[in] portNumber Port number (0-15)
Returns
bool Current port state (true=high, false=low)
Reads input port state using port number
Definition at line 260 of file IndicatorInterface.cpp.
References _reverseModeLogic(), and getCurrentState().
setAllOutputs()
void IndicatorInterface::setAllOutputs (bool state)
Set all output ports to specified state.
Parameters
[in] state Desired state for all outputs
Controls all output ports simultaneously
Definition at line 210 of file IndicatorInterface.cpp.
References _applyModeLogic(), _currentState, _writePCF(), and isOutput().
Referenced by setAllOutputsHigh(), and setAllOutputsLow().
setAllOutputsHigh()
void IndicatorInterface::setAllOutputsHigh ()
Set all output ports to high state.
Convenience method to set all outputs high
Definition at line 231 of file IndicatorInterface.cpp.
References setAllOutputs().
setAllOutputsLow()
void IndicatorInterface::setAllOutputsLow ()
Set all output ports to low state.
Convenience method to set all outputs low
Definition at line 235 of file IndicatorInterface.cpp.
References setAllOutputs().
setDirection()
void IndicatorInterface::setDirection (uint16_t directionMask)
Set port directions for all 16 ports.
Parameters
[in] directionMask Bit mask where 0=input, 1=output
Configures which ports are inputs vs outputs
Definition at line 113 of file IndicatorInterface.cpp.
References _currentState, _directionMask, _writePCF(), and isOutput().
setInterruptCallback()
void IndicatorInterface::setInterruptCallback (void(* callback)(uint16_t currentState, uint16_t changedPins))
Set callback function for port change interrupts.
Parameters
[in] callback Function to call when ports change
Callback receives current state and changed pins as parameters
Definition at line 301 of file IndicatorInterface.cpp.
References _interruptCallback.
setMode()
void IndicatorInterface::setMode (uint16_t modeMask)
Set port inversion mode for all 16 ports.
Parameters
[in] modeMask Bit mask where 0=normal, 1=inverted
Configures logic inversion for each port
Definition at line 129 of file IndicatorInterface.cpp.
References _modeMask.
setOLEDblink()
void IndicatorInterface::setOLEDblink (int timeOn, int timeOff, bool blinkOn = true)
Set OLED blinking mode.
Parameters
[in] timeOn Milliseconds display is on
[in] timeOff Milliseconds display is off
[in] blinkOn True to enable blinking
Controls OLED blinking for attention-getting displays
Definition at line 470 of file IndicatorInterface.cpp.
References _blinkState, _blinkTimeOff, _blinkTimeOn, _lastBlinkTime, _oledBlink, and _wakeOLED().
setOledMode()
void IndicatorInterface::setOledMode (int lines)
Set OLED display mode.
Parameters
[in] lines Number of text lines to display (1-5)
Configures display layout for text output
Definition at line 438 of file IndicatorInterface.cpp.
References _calculateDisplayParams(), _oledLines, and _wakeOLED().
setOLEDOff()
void IndicatorInterface::setOLEDOff ()
Turn OLED display off.
Powers down OLED display
Definition at line 482 of file IndicatorInterface.cpp.
References _oledBlink, _oledOn, and u8g2.
setOLEDOn()
void IndicatorInterface::setOLEDOn ()
Turn OLED display on.
Powers up OLED display
Definition at line 488 of file IndicatorInterface.cpp.
References _oledOn, _oledSleeping, _updateOLEDDisplay(), _wakeOLED(), and u8g2.
setOledSleepDelay()
void IndicatorInterface::setOledSleepDelay (long sleepDelay)
Set OLED sleep delay.
Parameters
[in] sleepDelay Milliseconds before sleep (-1 = never sleep)
Controls automatic OLED power saving
Definition at line 433 of file IndicatorInterface.cpp.
References _oledSleepDelay, and _wakeOLED().
setPortInverted() [1/2]
void IndicatorInterface::setPortInverted (const std::string & portName, bool inverted)
Set inversion mode for a named port.
Parameters
[in] portName Name of the port
[in] inverted True to invert logic, false for normal
Controls whether port logic is inverted
Definition at line 407 of file IndicatorInterface.cpp.
References _portNames, and setPortInverted().
Referenced by setPortInverted().
setPortInverted() [2/2]
void IndicatorInterface::setPortInverted (uint8_t portNumber, bool inverted)
Set inversion mode for a numbered port.
Parameters
[in] portNumber Port number (0-15)
[in] inverted True to invert logic, false for normal
Controls whether port logic is inverted
Definition at line 414 of file IndicatorInterface.cpp.
References _modeMask.
setPortName()
void IndicatorInterface::setPortName (const std::string & name, uint8_t portNumber)
Set name for a single port.
Parameters
[in] name Human-readable port name
[in] portNumber Port number (0-15)
Assigns a name to a specific port number
Definition at line 143 of file IndicatorInterface.cpp.
References _portNames, and _portNumbers.
setPortNames()
void IndicatorInterface::setPortNames (const std::map< std::string, uint8_t > & portNames)
Set names for multiple ports.
Parameters
[in] portNames Map of port names to port numbers
Assigns human-readable names to port numbers for easier access
Definition at line 133 of file IndicatorInterface.cpp.
References _portNames, and _portNumbers.
startBlinking()
void IndicatorInterface::startBlinking (const std::string & portName, unsigned long onTime, unsigned long offTime)
Start blinking a named port.
Parameters
[in] portName Name of port to blink
[in] onTime Milliseconds port stays on
[in] offTime Milliseconds port stays off
Begins automatic blinking of specified port
Definition at line 1005 of file IndicatorInterface.cpp.
References _blinkingPorts, IndicatorInterface::BlinkingPort::currentState, LoggerManager::info(), IndicatorInterface::BlinkingPort::isActive, IndicatorInterface::BlinkingPort::lastToggleTime, IndicatorInterface::BlinkingPort::offTime, IndicatorInterface::BlinkingPort::onTime, IndicatorInterface::BlinkingPort::portName, and writePort().
stopBlinking() [1/2]
void IndicatorInterface::stopBlinking ()
Stop all blinking and restore normal text.
Ends blinking mode and returns to previous display
Definition at line 955 of file IndicatorInterface.cpp.
References _isBlinkingCross, _isBlinkingOK, and _restoreCurrentText().
stopBlinking() [2/2]
void IndicatorInterface::stopBlinking (const std::string & portName)
Stop blinking a named port.
Parameters
[in] portName Name of port to stop blinking
Ends automatic blinking and leaves port in current state
Definition at line 1034 of file IndicatorInterface.cpp.
References _blinkingPorts, LoggerManager::info(), and writePort().
update()
void IndicatorInterface::update ()
Update interface state (call in main loop)
Handles port state updates, blinking, OLED updates, and sleep management
Definition at line 512 of file IndicatorInterface.cpp.
References updateBlinking(), and updateOLED().
updateBlinking()
void IndicatorInterface::updateBlinking ()
Update all blinking ports (call in main loop)
Handles timing and state changes for all blinking ports
Definition at line 1048 of file IndicatorInterface.cpp.
References _blinkingPorts, and writePort().
Referenced by update().
updateOLED()
void IndicatorInterface::updateOLED ()
Update OLED display (call in main loop)
Handles scrolling, blinking, and sleep management
Definition at line 496 of file IndicatorInterface.cpp.
References _handleOLEDBlink(), _handleOLEDSleep(), _handleScrolling(), _handleSpecialBlink(), _isBlinkingCross, _isBlinkingOK, _oledOn, and _oledSleeping.
Referenced by update().
writePort() [1/2]
bool IndicatorInterface::writePort (const std::string & portName, bool state)
Write state to a named port.
Parameters
[in] portName Name of the port to control
[in] state Desired state (true=high, false=low)
Returns
bool True if port exists and write successful
Controls output port state using human-readable name
Definition at line 150 of file IndicatorInterface.cpp.
References _portNames, and writePort().
Referenced by startBlinking(), stopBlinking(), updateBlinking(), and writePort().
writePort() [2/2]
bool IndicatorInterface::writePort (uint8_t portNumber, bool state)
Write state to a numbered port.
Parameters
[in] portNumber Port number (0-15)
[in] state Desired state (true=high, false=low)
Returns
bool True if write successful
Controls output port state using port number
Definition at line 158 of file IndicatorInterface.cpp.
References _applyModeLogic(), _currentState, _writePCF(), and isOutput().
writePorts()
void IndicatorInterface::writePorts (uint16_t portMask)
Write states to multiple ports simultaneously.
Parameters
[in] portMask 16-bit mask representing desired port states
Updates all output ports in a single I2C transaction
Definition at line 187 of file IndicatorInterface.cpp.
References _applyModeLogic(), _currentState, _writePCF(), and isOutput().
Field Documentation
_blinkDelayTime
int IndicatorInterface::_blinkDelayTime private
Delay time for special symbol blinking.
Definition at line 541 of file IndicatorInterface.h.
Referenced by _handleSpecialBlink(), blinkCross(), blinkOK(), and IndicatorInterface().
_blinkingPorts
std::vector<BlinkingPort> IndicatorInterface::_blinkingPorts private
Vector of ports configured for blinking.
Definition at line 379 of file IndicatorInterface.h.
Referenced by isBlinking(), startBlinking(), stopBlinking(), and updateBlinking().
_blinkShowSpecial
bool IndicatorInterface::_blinkShowSpecial private
Current blink state (true=symbol, false=text)
Definition at line 543 of file IndicatorInterface.h.
Referenced by _handleSpecialBlink(), blinkCross(), blinkOK(), and IndicatorInterface().
_blinkState
bool IndicatorInterface::_blinkState private
Current blink state (on/off)
Definition at line 473 of file IndicatorInterface.h.
Referenced by _handleOLEDBlink(), IndicatorInterface(), and setOLEDblink().
_blinkTimeOff
int IndicatorInterface::_blinkTimeOff private
Milliseconds OLED stays off during blink.
Definition at line 471 of file IndicatorInterface.h.
Referenced by _handleOLEDBlink(), IndicatorInterface(), and setOLEDblink().
_blinkTimeOn
int IndicatorInterface::_blinkTimeOn private
Milliseconds OLED stays on during blink.
Definition at line 470 of file IndicatorInterface.h.
Referenced by _handleOLEDBlink(), IndicatorInterface(), and setOLEDblink().
_charWidth
int IndicatorInterface::_charWidth private
Width of characters in pixels.
Definition at line 481 of file IndicatorInterface.h.
Referenced by _calculateDisplayParams(), and IndicatorInterface().
_currentState
uint16_t IndicatorInterface::_currentState private
Current state of all 16 ports.
Definition at line 395 of file IndicatorInterface.h.
Referenced by _updateState(), _writePCF(), begin(), getCurrentState(), IndicatorInterface(), setAllOutputs(), setDirection(), writePort(), and writePorts().
_directionMask
uint16_t IndicatorInterface::_directionMask private
Port direction mask (0=input, 1=output)
Definition at line 389 of file IndicatorInterface.h.
Referenced by IndicatorInterface(), isOutput(), printConfiguration(), and setDirection().
_i2cBus
TwoWire* IndicatorInterface::_i2cBus private
Pointer to I2C bus interface.
Definition at line 382 of file IndicatorInterface.h.
Referenced by begin(), and IndicatorInterface().
_instance
IndicatorInterface * IndicatorInterface::_instance = nullptr static private
Static instance for interrupt callback.
Definition at line 453 of file IndicatorInterface.h.
Referenced by _staticInterruptHandler(), IndicatorInterface(), and ~IndicatorInterface().
_interruptCallback
void(* IndicatorInterface::_interruptCallback) (uint16_t currentState, uint16_t changedPins) private
User callback function.
Definition at line 403 of file IndicatorInterface.h.
Referenced by _updateState(), IndicatorInterface(), and setInterruptCallback().
_interruptFlag
volatile bool IndicatorInterface::_interruptFlag private
Flag set by interrupt handler.
Definition at line 401 of file IndicatorInterface.h.
Referenced by handleInterrupt(), and IndicatorInterface().
_intPin
int IndicatorInterface::_intPin private
GPIO pin for interrupt handling.
Definition at line 385 of file IndicatorInterface.h.
Referenced by _configureInterruptPin(), IndicatorInterface(), printConfiguration(), and ~IndicatorInterface().
_isBlinkingCross
bool IndicatorInterface::_isBlinkingCross private
Whether currently blinking cross symbol.
Definition at line 540 of file IndicatorInterface.h.
Referenced by _handleSpecialBlink(), blinkCross(), blinkOK(), IndicatorInterface(), stopBlinking(), and updateOLED().
_isBlinkingOK
bool IndicatorInterface::_isBlinkingOK private
Whether currently blinking OK symbol.
Definition at line 539 of file IndicatorInterface.h.
Referenced by _handleSpecialBlink(), blinkCross(), blinkOK(), IndicatorInterface(), stopBlinking(), and updateOLED().
_lastActivityTime
unsigned long IndicatorInterface::_lastActivityTime private
Last user activity time.
Definition at line 474 of file IndicatorInterface.h.
Referenced by _handleOLEDSleep(), _initOLED(), _wakeOLED(), IndicatorInterface(), and printText().
_lastBlinkTime
unsigned long IndicatorInterface::_lastBlinkTime private
Last blink toggle time.
Definition at line 472 of file IndicatorInterface.h.
Referenced by _handleOLEDBlink(), IndicatorInterface(), and setOLEDblink().
_lastBlinkToggle
unsigned long IndicatorInterface::_lastBlinkToggle private
Last toggle time for special blinking.
Definition at line 542 of file IndicatorInterface.h.
Referenced by _handleSpecialBlink(), blinkCross(), blinkOK(), and IndicatorInterface().
_lastReadTime
unsigned long IndicatorInterface::_lastReadTime private
Last time ports were read.
Definition at line 397 of file IndicatorInterface.h.
Referenced by _updateState(), begin(), getCurrentState(), and IndicatorInterface().
_lastScrollTime
unsigned long IndicatorInterface::_lastScrollTime private
Last scroll update time.
Definition at line 479 of file IndicatorInterface.h.
Referenced by _handleScrolling(), and IndicatorInterface().
_lastState
uint16_t IndicatorInterface::_lastState private
Previous state for change detection.
Definition at line 396 of file IndicatorInterface.h.
Referenced by _updateState(), begin(), and IndicatorInterface().
_lineHeight
int IndicatorInterface::_lineHeight private
Height of lines in pixels.
Definition at line 482 of file IndicatorInterface.h.
Referenced by _calculateDisplayParams(), and IndicatorInterface().
_maxCharsPerLine
int IndicatorInterface::_maxCharsPerLine private
Maximum characters per display line.
Definition at line 483 of file IndicatorInterface.h.
Referenced by _calculateDisplayParams(), and IndicatorInterface().
_modeMask
uint16_t IndicatorInterface::_modeMask private
Port inversion mask (0=normal, 1=inverted)
Definition at line 390 of file IndicatorInterface.h.
Referenced by IndicatorInterface(), isInverted(), printConfiguration(), setMode(), and setPortInverted().
_oledBlink
bool IndicatorInterface::_oledBlink private
Whether OLED is blinking.
Definition at line 469 of file IndicatorInterface.h.
Referenced by _handleOLEDBlink(), blinkCross(), blinkOK(), IndicatorInterface(), setOLEDblink(), and setOLEDOff().
_oledLines
int IndicatorInterface::_oledLines private
Number of display lines (1-5)
Definition at line 465 of file IndicatorInterface.h.
Referenced by _calculateDisplayParams(), _restoreCurrentText(), _saveCurrentText(), _updateOLEDDisplay(), IndicatorInterface(), pushLine(), and setOledMode().
_oledOn
bool IndicatorInterface::_oledOn private
OLED power state.
Definition at line 468 of file IndicatorInterface.h.
Referenced by _updateOLEDDisplay(), _wakeOLED(), IndicatorInterface(), setOLEDOff(), setOLEDOn(), and updateOLED().
_oledSleepDelay
long IndicatorInterface::_oledSleepDelay private
Sleep delay in milliseconds (-1 = never sleep)
Definition at line 464 of file IndicatorInterface.h.
Referenced by _handleOLEDSleep(), IndicatorInterface(), and setOledSleepDelay().
_oledSleeping
bool IndicatorInterface::_oledSleeping private
Whether OLED is currently sleeping.
Definition at line 475 of file IndicatorInterface.h.
Referenced by _handleOLEDBlink(), _handleOLEDSleep(), _updateOLEDDisplay(), _wakeOLED(), IndicatorInterface(), setOLEDOn(), and updateOLED().
_pcf8575
PCF8575 IndicatorInterface::_pcf8575 private
PCF8575 expander instance.
Definition at line 386 of file IndicatorInterface.h.
Referenced by _clearInterrupt(), _readPCF(), _writePCF(), begin(), and IndicatorInterface().
_pcf_i2cAddress
uint8_t IndicatorInterface::_pcf_i2cAddress private
I2C address of PCF8575 expander.
Definition at line 383 of file IndicatorInterface.h.
Referenced by IndicatorInterface(), and printConfiguration().
_pollInterval
unsigned long IndicatorInterface::_pollInterval private
Polling interval for port updates.
Definition at line 398 of file IndicatorInterface.h.
Referenced by getCurrentState(), and IndicatorInterface().
_portNames
std::map<std::string, uint8_t> IndicatorInterface::_portNames private
Map of port names to numbers.
Definition at line 391 of file IndicatorInterface.h.
Referenced by getPortNumber(), printConfiguration(), readPort(), setPortInverted(), setPortName(), setPortNames(), and writePort().
_portNumbers
std::map<uint8_t, std::string> IndicatorInterface::_portNumbers private
Map of port numbers to names.
Definition at line 392 of file IndicatorInterface.h.
Referenced by getPortName(), setPortName(), and setPortNames().
_savedOledLines
int IndicatorInterface::_savedOledLines private
Saved number of display lines.
Definition at line 538 of file IndicatorInterface.h.
Referenced by _restoreCurrentText(), _saveCurrentText(), and IndicatorInterface().
_savedTextBuffer
String IndicatorInterface::_savedTextBuffer[5] private
Backup of text before OK/Cross display.
Definition at line 536 of file IndicatorInterface.h.
Referenced by _restoreCurrentText(), and _saveCurrentText().
_savedTextBufferSize
int IndicatorInterface::_savedTextBufferSize private
Size of saved text buffer.
Definition at line 537 of file IndicatorInterface.h.
Referenced by _restoreCurrentText(), _saveCurrentText(), and IndicatorInterface().
_scrollDelay
int IndicatorInterface::_scrollDelay private
Delay between scroll steps.
Definition at line 480 of file IndicatorInterface.h.
Referenced by _handleScrolling(), and IndicatorInterface().
_scrollOffset
int IndicatorInterface::_scrollOffset[5] private
Horizontal scroll offset for each line.
Definition at line 478 of file IndicatorInterface.h.
Referenced by _drawTextLine(), _handleScrolling(), IndicatorInterface(), printText(), and pushLine().
_textBuffer
String IndicatorInterface::_textBuffer[5] private
Text buffer for display (max 5 lines)
Definition at line 466 of file IndicatorInterface.h.
Referenced by _drawTextLine(), _handleScrolling(), _restoreCurrentText(), _saveCurrentText(), printText(), and pushLine().
_textBufferSize
int IndicatorInterface::_textBufferSize private
Current number of lines in buffer.
Definition at line 467 of file IndicatorInterface.h.
Referenced by _drawTextLine(), _handleScrolling(), _restoreCurrentText(), _saveCurrentText(), _updateOLEDDisplay(), IndicatorInterface(), printText(), and pushLine().
_useInterrupts
bool IndicatorInterface::_useInterrupts private
Whether interrupts are enabled.
Definition at line 402 of file IndicatorInterface.h.
Referenced by begin(), getCurrentState(), IndicatorInterface(), printConfiguration(), and ~IndicatorInterface().
oled_i2cAddress
uint8_t IndicatorInterface::oled_i2cAddress private
I2C address of OLED display.
Definition at line 384 of file IndicatorInterface.h.
u8g2
U8G2_SH1106_128X64_NONAME_F_HW_I2C IndicatorInterface::u8g2 static private
Static OLED display instance.
Definition at line 461 of file IndicatorInterface.h.
Referenced by _calculateDisplayParams(), _drawTextLine(), _handleOLEDBlink(), _handleOLEDSleep(), _handleScrolling(), _initOLED(), _updateOLEDDisplay(), _wakeOLED(), begin(), displayCross(), displayOK(), setOLEDOff(), and setOLEDOn().
The documentation for this class was generated from the following files:
include/IndicatorInterface.h
src/IndicatorInterface.cpp