Temperature Control System: TimeManager Class Reference
TimeManager Class Reference
Manages system time with RTC and NTP synchronization.
#include <TimeManager.h>
Public Member Functions
TimeManager (int sdaPin=21, int sclPin=22)
Construct a new Time Manager object.
~TimeManager ()
Destroy the Time Manager object.
bool begin ()
Initialize time manager and RTC.
bool init ()
Alternative initialization method.
bool setTimeFromNTP (const char *ntpServer="pool.ntp.org")
Set time from NTP server.
bool setTime (int year, int month, int day, int hour, int minute, int second)
Set time manually.
bool setTime (DateTime dateTime)
Set time from DateTime object.
bool setTimeFromUnix (uint32_t unixTime)
Set time from Unix timestamp.
bool setTimeFromCompileTime ()
Set time from compile time.
DateTime getCurrentTime ()
Get current time from RTC.
String getFormattedTime (const String &format="YYYY-MM-DD hh:mm:ss")
Get formatted time string.
String getTimeString ()
Get time as string (HH:MM:SS)
String getDateString ()
Get date as string (YYYY-MM-DD)
uint32_t getUnixTime ()
Get Unix timestamp.
void setTimezone (int offsetHours, int offsetMinutes=0)
Set timezone offset.
void setTimezoneOffset (long offsetSeconds)
Set timezone offset in seconds.
int getTimezoneHours ()
Get timezone hours offset.
int getTimezoneMinutes ()
Get timezone minutes offset.
long getTimezoneOffset ()
Get total timezone offset in seconds.
void setNTPServer (const String &server)
Set NTP server address.
void setNTPUpdateInterval (unsigned long intervalMs)
Set NTP update interval.
String getNTPServer ()
Get current NTP server.
void update ()
Update time from NTP if needed.
bool syncWithNTP ()
Force immediate NTP synchronization.
bool isNTPSyncEnabled ()
Check if NTP sync is enabled.
void enableNTPSync (bool enable)
Enable/disable automatic NTP sync.
bool isRTCConnected ()
Check if RTC is connected.
bool isTimeSet ()
Check if time has been set.
bool hasLostPower ()
Check if RTC lost power.
unsigned long getLastNTPSync ()
Get timestamp of last NTP sync.
float getTemperature ()
Get temperature from DS3231.
bool setAlarm1 (DateTime alarmTime, Ds3231Alarm1Mode mode=DS3231_A1_Hour)
Set Alarm 1 on DS3231.
bool setAlarm2 (DateTime alarmTime, Ds3231Alarm2Mode mode=DS3231_A2_Hour)
Set Alarm 2 on DS3231.
bool clearAlarm1 ()
Clear Alarm 1 flag.
bool clearAlarm2 ()
Clear Alarm 2 flag.
bool isAlarm1Triggered ()
Check if Alarm 1 has triggered.
bool isAlarm2Triggered ()
Check if Alarm 2 has triggered.
void enableSquareWave (Ds3231SqwPinMode mode=DS3231_SquareWave1Hz)
Enable square wave output on SQW pin.
void disableSquareWave ()
Disable square wave output.
String getTimeJSON ()
Get current time as JSON string.
String getStatusJSON ()
Get time manager status as JSON.
void saveConfig ()
Save time configuration to persistent storage.
void loadConfig ()
Load time configuration from persistent storage.
Private Member Functions
void _initializeNTP ()
Initialize NTP client with current settings.
bool _isWiFiConnected ()
Check if WiFi is connected.
void _updateFromNTP ()
Update RTC from NTP server.
DateTime _applyTimezone (DateTime utcTime)
Apply timezone offset to UTC time.
DateTime _removeTimezone (DateTime localTime)
Remove timezone offset from local time.
String _formatDateTime (DateTime dt, const String &format)
Format DateTime according to format string.
Private Attributes
RTC_DS3231 _rtc
DS3231 RTC instance.
WiFiUDP _ntpUDP
UDP client for NTP communication.
NTPClient * _timeClient
NTP client instance.
int _sdaPin
I2C SDA pin number.
int _sclPin
I2C SCL pin number.
long _timezoneOffset
Timezone offset in seconds from UTC.
String _ntpServer
NTP server hostname.
unsigned long _ntpUpdateInterval
NTP sync interval in milliseconds.
bool _ntpSyncEnabled
Flag for automatic NTP synchronization.
bool _rtcConnected
RTC connection status.
bool _timeSet
Time validity flag.
unsigned long _lastNTPSync
Timestamp of last successful NTP sync.
unsigned long _lastNTPAttempt
Timestamp of last NTP sync attempt.
Detailed Description
Manages system time with RTC and NTP synchronization.
Provides comprehensive time management including RTC control, NTP synchronization, timezone handling, alarms, and formatting.
Definition at line 37 of file TimeManager.h.
Constructor & Destructor Documentation
TimeManager()
TimeManager::TimeManager (int sdaPin = 21, int sclPin = 22)
Construct a new Time Manager object.
Parameters
[in] sdaPin I2C SDA pin (default: 21)
[in] sclPin I2C SCL pin (default: 22)
Definition at line 24 of file TimeManager.cpp.
References _lastNTPAttempt, _lastNTPSync, _ntpServer, _ntpSyncEnabled, _ntpUpdateInterval, _rtcConnected, _sclPin, _sdaPin, _timeClient, _timeSet, and _timezoneOffset.
~TimeManager()
TimeManager::~TimeManager ()
Destroy the Time Manager object.
Cleans up NTP client resources
Definition at line 31 of file TimeManager.cpp.
References _timeClient.
Member Function Documentation
_applyTimezone()
DateTime TimeManager::_applyTimezone (DateTime utcTime) private
Apply timezone offset to UTC time.
Parameters
[in] utcTime UTC DateTime
Returns
DateTime Local time with timezone applied
Definition at line 429 of file TimeManager.cpp.
References _timezoneOffset.
_formatDateTime()
String TimeManager::_formatDateTime (DateTime dt, const String & format) private
Format DateTime according to format string.
Parameters
[in] dt DateTime to format
[in] format Format string with placeholders
Returns
String Formatted date/time string
Definition at line 437 of file TimeManager.cpp.
Referenced by getDateString(), getFormattedTime(), getTimeString(), and setTime().
_initializeNTP()
void TimeManager::_initializeNTP () private
Initialize NTP client with current settings.
Definition at line 99 of file TimeManager.cpp.
References _ntpServer, _ntpUDP, _ntpUpdateInterval, _timeClient, and _timezoneOffset.
Referenced by begin(), loadConfig(), setNTPServer(), and setTimeFromNTP().
_isWiFiConnected()
bool TimeManager::_isWiFiConnected () private
Check if WiFi is connected.
Returns
true if WiFi connected
false if WiFi disconnected
Definition at line 425 of file TimeManager.cpp.
Referenced by getStatusJSON(), setTimeFromNTP(), and update().
_removeTimezone()
DateTime TimeManager::_removeTimezone (DateTime localTime) private
Remove timezone offset from local time.
Parameters
[in] localTime Local DateTime
Returns
DateTime UTC time
Definition at line 433 of file TimeManager.cpp.
References _timezoneOffset.
_updateFromNTP()
void TimeManager::_updateFromNTP () private
Update RTC from NTP server.
Internal method called by update()
begin()
bool TimeManager::begin ()
Initialize time manager and RTC.
Returns
true if initialization successful
false if RTC not found or initialization failed
Definition at line 68 of file TimeManager.cpp.
References _initializeNTP(), and loadConfig().
clearAlarm1()
bool TimeManager::clearAlarm1 ()
Clear Alarm 1 flag.
Returns
true if alarm cleared successfully
false if RTC communication failed
Definition at line 306 of file TimeManager.cpp.
References _rtc, and _rtcConnected.
clearAlarm2()
bool TimeManager::clearAlarm2 ()
Clear Alarm 2 flag.
Returns
true if alarm cleared successfully
false if RTC communication failed
Definition at line 314 of file TimeManager.cpp.
References _rtc, and _rtcConnected.
disableSquareWave()
void TimeManager::disableSquareWave ()
Disable square wave output.
Definition at line 343 of file TimeManager.cpp.
References _rtc, and _rtcConnected.
enableNTPSync()
void TimeManager::enableNTPSync (bool enable)
Enable/disable automatic NTP sync.
Parameters
[in] enable True to enable, false to disable
Definition at line 265 of file TimeManager.cpp.
References _ntpSyncEnabled.
enableSquareWave()
void TimeManager::enableSquareWave (Ds3231SqwPinMode mode = DS3231_SquareWave1Hz)
Enable square wave output on SQW pin.
Parameters
[in] mode Square wave frequency (default: 1Hz)
See also
Ds3231SqwPinMode
Definition at line 337 of file TimeManager.cpp.
References _rtc, and _rtcConnected.
getCurrentTime()
DateTime TimeManager::getCurrentTime ()
Get current time from RTC.
Returns
DateTime Current date and time
Definition at line 170 of file TimeManager.cpp.
References _rtc, and _rtcConnected.
Referenced by getDateString(), getFormattedTime(), getTimeJSON(), and getTimeString().
getDateString()
String TimeManager::getDateString ()
Get date as string (YYYY-MM-DD)
Returns
String Date in YYYY-MM-DD format
Definition at line 189 of file TimeManager.cpp.
References _formatDateTime(), and getCurrentTime().
Referenced by getTimeJSON().
getFormattedTime()
String TimeManager::getFormattedTime (const String & format = "YYYY-MM-DD hh:mm:ss")
Get formatted time string.
Parameters
[in] format Format string (default: "YYYY-MM-DD hh:mm:ss")
Returns
String Formatted time string
Note
Format: YYYY=year, MM=month, DD=day, hh=hour, mm=minute, ss=second
Definition at line 179 of file TimeManager.cpp.
References _formatDateTime(), and getCurrentTime().
Referenced by getTimeJSON(), and setTimeFromNTP().
getLastNTPSync()
unsigned long TimeManager::getLastNTPSync ()
Get timestamp of last NTP sync.
Returns
unsigned long Milliseconds since last sync
Definition at line 281 of file TimeManager.cpp.
References _lastNTPSync.
getNTPServer()
String TimeManager::getNTPServer ()
Get current NTP server.
Returns
String NTP server address
Definition at line 240 of file TimeManager.cpp.
References _ntpServer.
getStatusJSON()
String TimeManager::getStatusJSON ()
Get time manager status as JSON.
Returns
String JSON with RTC status, NTP sync info, temperature
Note
Includes RTC connection, time set status, last sync time
Definition at line 366 of file TimeManager.cpp.
References _isWiFiConnected(), _lastNTPSync, _ntpServer, _ntpSyncEnabled, _rtc, _rtcConnected, _timeSet, hasLostPower(), isAlarm1Triggered(), and isAlarm2Triggered().
getTemperature()
float TimeManager::getTemperature ()
Get temperature from DS3231.
Returns
float Temperature in Celsius
Note
DS3231 has built-in temperature sensor
Definition at line 285 of file TimeManager.cpp.
References _rtc, and _rtcConnected.
getTimeJSON()
String TimeManager::getTimeJSON ()
Get current time as JSON string.
Returns
String JSON with time, date, timezone info
Note
Format: {"time":"HH:MM:SS","date":"YYYY-MM-DD","unix":timestamp,"timezone":offset}
Definition at line 349 of file TimeManager.cpp.
References _timezoneOffset, getCurrentTime(), getDateString(), getFormattedTime(), getTimeString(), getTimezoneHours(), and getTimezoneMinutes().
getTimeString()
String TimeManager::getTimeString ()
Get time as string (HH:MM:SS)
Returns
String Time in HH:MM:SS format
Definition at line 184 of file TimeManager.cpp.
References _formatDateTime(), and getCurrentTime().
Referenced by getTimeJSON().
getTimezoneHours()
int TimeManager::getTimezoneHours ()
Get timezone hours offset.
Returns
int Hours offset from UTC
Definition at line 216 of file TimeManager.cpp.
References _timezoneOffset.
Referenced by getTimeJSON().
getTimezoneMinutes()
int TimeManager::getTimezoneMinutes ()
Get timezone minutes offset.
Returns
int Minutes offset within hour
Definition at line 220 of file TimeManager.cpp.
References _timezoneOffset.
Referenced by getTimeJSON().
getTimezoneOffset()
long TimeManager::getTimezoneOffset ()
Get total timezone offset in seconds.
Returns
long Total seconds offset from UTC
Definition at line 224 of file TimeManager.cpp.
References _timezoneOffset.
getUnixTime()
uint32_t TimeManager::getUnixTime ()
Get Unix timestamp.
Returns
uint32_t Seconds since 1970-01-01 00:00:00
Definition at line 194 of file TimeManager.cpp.
References _rtc, and _rtcConnected.
hasLostPower()
bool TimeManager::hasLostPower ()
Check if RTC lost power.
Returns
true if RTC lost power and time invalid
false if RTC maintained time
Definition at line 277 of file TimeManager.cpp.
References _rtc, and _rtcConnected.
Referenced by getStatusJSON().
init()
bool TimeManager::init ()
Alternative initialization method.
Returns
true if initialization successful
false if initialization failed
See also
begin()
Definition at line 37 of file TimeManager.cpp.
References _rtc, _rtcConnected, _timeSet, and setTimeFromCompileTime().
isAlarm1Triggered()
bool TimeManager::isAlarm1Triggered ()
Check if Alarm 1 has triggered.
Returns
true if alarm triggered
false if alarm not triggered
Definition at line 323 of file TimeManager.cpp.
References _rtc, and _rtcConnected.
Referenced by getStatusJSON().
isAlarm2Triggered()
bool TimeManager::isAlarm2Triggered ()
Check if Alarm 2 has triggered.
Returns
true if alarm triggered
false if alarm not triggered
Definition at line 330 of file TimeManager.cpp.
References _rtc, and _rtcConnected.
Referenced by getStatusJSON().
isNTPSyncEnabled()
bool TimeManager::isNTPSyncEnabled ()
Check if NTP sync is enabled.
Returns
true if automatic NTP sync enabled
false if NTP sync disabled
Definition at line 261 of file TimeManager.cpp.
References _ntpSyncEnabled.
isRTCConnected()
bool TimeManager::isRTCConnected ()
Check if RTC is connected.
Returns
true if RTC communication successful
false if RTC not responding
Definition at line 269 of file TimeManager.cpp.
References _rtcConnected.
isTimeSet()
bool TimeManager::isTimeSet ()
Check if time has been set.
Returns
true if RTC time is valid
false if time not set
Definition at line 273 of file TimeManager.cpp.
References _timeSet.
loadConfig()
void TimeManager::loadConfig ()
Load time configuration from persistent storage.
Restores timezone, NTP server, and sync settings
Definition at line 403 of file TimeManager.cpp.
References _initializeNTP(), _ntpServer, _ntpSyncEnabled, _ntpUpdateInterval, and _timezoneOffset.
Referenced by begin().
saveConfig()
void TimeManager::saveConfig ()
Save time configuration to persistent storage.
Saves timezone, NTP server, and sync settings
Definition at line 388 of file TimeManager.cpp.
References _ntpServer, _ntpSyncEnabled, _ntpUpdateInterval, and _timezoneOffset.
setAlarm1()
bool TimeManager::setAlarm1 (DateTime alarmTime, Ds3231Alarm1Mode mode = DS3231_A1_Hour)
Set Alarm 1 on DS3231.
Parameters
[in] alarmTime DateTime when alarm should trigger
[in] mode Alarm mode (default: match hours)
Returns
true if alarm set successfully
false if RTC communication failed
See also
Ds3231Alarm1Mode
Definition at line 292 of file TimeManager.cpp.
References _rtc, and _rtcConnected.
setAlarm2()
bool TimeManager::setAlarm2 (DateTime alarmTime, Ds3231Alarm2Mode mode = DS3231_A2_Hour)
Set Alarm 2 on DS3231.
Parameters
[in] alarmTime DateTime when alarm should trigger
[in] mode Alarm mode (default: match hours)
Returns
true if alarm set successfully
false if RTC communication failed
See also
Ds3231Alarm2Mode
Definition at line 299 of file TimeManager.cpp.
References _rtc, and _rtcConnected.
setNTPServer()
void TimeManager::setNTPServer (const String & server)
Set NTP server address.
Parameters
[in] server NTP server hostname or IP
Definition at line 228 of file TimeManager.cpp.
References _initializeNTP(), and _ntpServer.
setNTPUpdateInterval()
void TimeManager::setNTPUpdateInterval (unsigned long intervalMs)
Set NTP update interval.
Parameters
[in] intervalMs Update interval in milliseconds
Definition at line 233 of file TimeManager.cpp.
References _ntpUpdateInterval, and _timeClient.
setTime() [1/2]
bool TimeManager::setTime (DateTime dateTime)
Set time from DateTime object.
Parameters
[in] dateTime DateTime object with time to set
Returns
true if time set successfully
false if RTC communication failed
Definition at line 144 of file TimeManager.cpp.
References _formatDateTime(), _rtc, _rtcConnected, and _timeSet.
setTime() [2/2]
bool TimeManager::setTime (int year, int month, int day, int hour, int minute, int second)
Set time manually.
Parameters
[in] year Year (2000-2099)
[in] month Month (1-12)
[in] day Day (1-31)
[in] hour Hour (0-23)
[in] minute Minute (0-59)
[in] second Second (0-59)
Returns
true if time set successfully
false if invalid parameters
Definition at line 139 of file TimeManager.cpp.
References setTime().
Referenced by setTime(), and setTimeFromUnix().
setTimeFromCompileTime()
bool TimeManager::setTimeFromCompileTime ()
Set time from compile time.
Returns
true if time set successfully
false if RTC communication failed
Note
Uses DATE and TIME macros
Definition at line 160 of file TimeManager.cpp.
References _rtc, _rtcConnected, and _timeSet.
Referenced by init().
setTimeFromNTP()
bool TimeManager::setTimeFromNTP (const char * ntpServer = "pool.ntp.org")
Set time from NTP server.
Parameters
[in] ntpServer NTP server address (default: "pool.ntp.org")
Returns
true if time set successfully
false if NTP sync failed
Definition at line 108 of file TimeManager.cpp.
References _initializeNTP(), _isWiFiConnected(), _lastNTPSync, _ntpServer, _rtc, _rtcConnected, _timeClient, _timeSet, and getFormattedTime().
Referenced by syncWithNTP(), and update().
setTimeFromUnix()
bool TimeManager::setTimeFromUnix (uint32_t unixTime)
Set time from Unix timestamp.
Parameters
[in] unixTime Unix timestamp (seconds since 1970)
Returns
true if time set successfully
false if RTC communication failed
Definition at line 155 of file TimeManager.cpp.
References setTime().
setTimezone()
void TimeManager::setTimezone (int offsetHours, int offsetMinutes = 0)
Set timezone offset.
Parameters
[in] offsetHours Hours offset from UTC (-12 to +14)
[in] offsetMinutes Minutes offset (default: 0)
Definition at line 201 of file TimeManager.cpp.
References _timeClient, and _timezoneOffset.
setTimezoneOffset()
void TimeManager::setTimezoneOffset (long offsetSeconds)
Set timezone offset in seconds.
Parameters
[in] offsetSeconds Seconds offset from UTC
Definition at line 209 of file TimeManager.cpp.
References _timeClient, and _timezoneOffset.
syncWithNTP()
bool TimeManager::syncWithNTP ()
Force immediate NTP synchronization.
Returns
true if sync successful
false if sync failed
Definition at line 257 of file TimeManager.cpp.
References setTimeFromNTP().
update()
void TimeManager::update ()
Update time from NTP if needed.
Call this in loop() for automatic NTP synchronization
Definition at line 244 of file TimeManager.cpp.
References _isWiFiConnected(), _lastNTPAttempt, _lastNTPSync, _ntpSyncEnabled, _ntpUpdateInterval, and setTimeFromNTP().
Field Documentation
_lastNTPAttempt
unsigned long TimeManager::_lastNTPAttempt private
Timestamp of last NTP sync attempt.
Definition at line 368 of file TimeManager.h.
Referenced by TimeManager(), and update().
_lastNTPSync
unsigned long TimeManager::_lastNTPSync private
Timestamp of last successful NTP sync.
Definition at line 367 of file TimeManager.h.
Referenced by getLastNTPSync(), getStatusJSON(), setTimeFromNTP(), TimeManager(), and update().
_ntpServer
String TimeManager::_ntpServer private
NTP server hostname.
Definition at line 360 of file TimeManager.h.
Referenced by _initializeNTP(), getNTPServer(), getStatusJSON(), loadConfig(), saveConfig(), setNTPServer(), setTimeFromNTP(), and TimeManager().
_ntpSyncEnabled
bool TimeManager::_ntpSyncEnabled private
Flag for automatic NTP synchronization.
Definition at line 362 of file TimeManager.h.
Referenced by enableNTPSync(), getStatusJSON(), isNTPSyncEnabled(), loadConfig(), saveConfig(), TimeManager(), and update().
_ntpUDP
WiFiUDP TimeManager::_ntpUDP private
UDP client for NTP communication.
Definition at line 353 of file TimeManager.h.
Referenced by _initializeNTP().
_ntpUpdateInterval
unsigned long TimeManager::_ntpUpdateInterval private
NTP sync interval in milliseconds.
Definition at line 361 of file TimeManager.h.
Referenced by _initializeNTP(), loadConfig(), saveConfig(), setNTPUpdateInterval(), TimeManager(), and update().
_rtc
RTC_DS3231 TimeManager::_rtc private
DS3231 RTC instance.
Definition at line 352 of file TimeManager.h.
Referenced by clearAlarm1(), clearAlarm2(), disableSquareWave(), enableSquareWave(), getCurrentTime(), getStatusJSON(), getTemperature(), getUnixTime(), hasLostPower(), init(), isAlarm1Triggered(), isAlarm2Triggered(), setAlarm1(), setAlarm2(), setTime(), setTimeFromCompileTime(), and setTimeFromNTP().
_rtcConnected
bool TimeManager::_rtcConnected private
RTC connection status.
Definition at line 365 of file TimeManager.h.
Referenced by clearAlarm1(), clearAlarm2(), disableSquareWave(), enableSquareWave(), getCurrentTime(), getStatusJSON(), getTemperature(), getUnixTime(), hasLostPower(), init(), isAlarm1Triggered(), isAlarm2Triggered(), isRTCConnected(), setAlarm1(), setAlarm2(), setTime(), setTimeFromCompileTime(), setTimeFromNTP(), and TimeManager().
_sclPin
int TimeManager::_sclPin private
I2C SCL pin number.
Definition at line 358 of file TimeManager.h.
Referenced by TimeManager().
_sdaPin
int TimeManager::_sdaPin private
I2C SDA pin number.
Definition at line 357 of file TimeManager.h.
Referenced by TimeManager().
_timeClient
NTPClient* TimeManager::_timeClient private
NTP client instance.
Definition at line 354 of file TimeManager.h.
Referenced by _initializeNTP(), setNTPUpdateInterval(), setTimeFromNTP(), setTimezone(), setTimezoneOffset(), TimeManager(), and ~TimeManager().
_timeSet
bool TimeManager::_timeSet private
Time validity flag.
Definition at line 366 of file TimeManager.h.
Referenced by getStatusJSON(), init(), isTimeSet(), setTime(), setTimeFromCompileTime(), setTimeFromNTP(), and TimeManager().
_timezoneOffset
long TimeManager::_timezoneOffset private
Timezone offset in seconds from UTC.
Definition at line 359 of file TimeManager.h.
Referenced by _applyTimezone(), _initializeNTP(), _removeTimezone(), getTimeJSON(), getTimezoneHours(), getTimezoneMinutes(), getTimezoneOffset(), loadConfig(), saveConfig(), setTimezone(), setTimezoneOffset(), and TimeManager().
The documentation for this class was generated from the following files:
include/TimeManager.h
src/TimeManager.cpp