Temperature Control System: MeasurementPoint Class Reference
MeasurementPoint Class Reference
Logical measurement point for temperature monitoring.
#include <MeasurementPoint.h>
Public Member Functions
MeasurementPoint ()
Default constructor.
MeasurementPoint (uint8_t address, const String &name)
Constructor with address and name.
~MeasurementPoint ()
Destructor.
uint8_t getAddress () const
Get measurement point address.
String getName () const
Get measurement point name.
int16_t getCurrentTemp () const
Get current temperature.
int16_t getMinTemp () const
Get minimum recorded temperature.
int16_t getMaxTemp () const
Get maximum recorded temperature.
int16_t getLowAlarmThreshold () const
Get low alarm threshold.
int16_t getHighAlarmThreshold () const
Get high alarm threshold.
uint8_t getAlarmStatus () const
Get alarm status bits.
uint8_t getErrorStatus () const
Get error status bits.
void setName (const String &newName)
Set measurement point name.
void setLowAlarmThreshold (int16_t threshold)
Set low alarm threshold.
void setHighAlarmThreshold (int16_t threshold)
Set high alarm threshold.
void bindSensor (Sensor *sensor)
Bind a physical sensor to this measurement point.
void unbindSensor ()
Unbind the currently bound sensor.
Sensor * getBoundSensor () const
Get pointer to bound sensor.
void update ()
Update measurement point (call periodically)
void resetMinMaxTemp ()
Reset min/max temperature records.
Private Member Functions
void updateAlarmStatus ()
Update alarm status based on current temperature.
Private Attributes
uint8_t address
Unique measurement point address.
String name
Human-readable measurement point name.
int16_t currentTemp
Latest temperature reading (째C)
int16_t minTemp
Minimum recorded temperature.
int16_t maxTemp
Maximum recorded temperature.
int16_t lowAlarmThreshold
Low temperature alarm threshold.
int16_t highAlarmThreshold
High temperature alarm threshold.
uint8_t alarmStatus
Bit field for alarm conditions.
uint8_t errorStatus
Bit field for error conditions.
Sensor * boundSensor
Pointer to bound physical sensor.
Detailed Description
Logical measurement point for temperature monitoring.
Represents a temperature measurement location with configurable alarm thresholds, min/max tracking, and optional sensor binding for direct hardware access
Definition at line 31 of file MeasurementPoint.h.
Constructor & Destructor Documentation
MeasurementPoint() [1/2]
MeasurementPoint::MeasurementPoint () inline
Default constructor.
Initializes measurement point with default values and safe ranges
Definition at line 37 of file MeasurementPoint.h.
References address, alarmStatus, boundSensor, currentTemp, errorStatus, highAlarmThreshold, lowAlarmThreshold, maxTemp, minTemp, and name.
MeasurementPoint() [2/2]
MeasurementPoint::MeasurementPoint (uint8_t address, const String & name)
Constructor with address and name.
Parameters
[in] address Unique address for this measurement point (0-255)
[in] name Human-readable name for the measurement point
Definition at line 24 of file MeasurementPoint.cpp.
References address, alarmStatus, boundSensor, currentTemp, errorStatus, highAlarmThreshold, lowAlarmThreshold, maxTemp, minTemp, and name.
~MeasurementPoint()
MeasurementPoint::~MeasurementPoint ()
Destructor.
Cleans up resources and unbinds any attached sensor
Definition at line 40 of file MeasurementPoint.cpp.
References boundSensor.
Member Function Documentation
bindSensor()
void MeasurementPoint::bindSensor (Sensor * sensor)
Bind a physical sensor to this measurement point.
Parameters
[in] sensor Pointer to sensor instance
Links measurement point to physical sensor for direct readings
Definition at line 118 of file MeasurementPoint.cpp.
References boundSensor.
Referenced by TemperatureController::bindSensorToPointByBusNumber(), TemperatureController::bindSensorToPointByChipSelect(), and TemperatureController::bindSensorToPointByRom().
getAddress()
uint8_t MeasurementPoint::getAddress () const
Get measurement point address.
Returns
uint8_t Unique address (0-255)
Definition at line 45 of file MeasurementPoint.cpp.
References address.
Referenced by CSVConfigManager::_exportPointToCSV(), ConfigManager::alarmsAPI(), RegisterMap::applyConfigFromMeasurementPoint(), RegisterMap::applyConfigToMeasurementPoint(), TemperatureController::createAlarm(), TemperatureController::ensureAlarmsForPoint(), TemperatureController::getAlarmsForPoint(), TemperatureController::getPointsJson(), ConfigManager::savePointsConfig(), and RegisterMap::updateFromMeasurementPoint().
getAlarmStatus()
uint8_t MeasurementPoint::getAlarmStatus () const
Get alarm status bits.
Returns
uint8_t Bit field representing active alarms
Definition at line 73 of file MeasurementPoint.cpp.
References alarmStatus.
Referenced by TemperatureController::getPointsJson(), and RegisterMap::updateFromMeasurementPoint().
getBoundSensor()
Sensor * MeasurementPoint::getBoundSensor () const
Get pointer to bound sensor.
Returns
Sensor* Pointer to bound sensor, nullptr if none bound
Definition at line 126 of file MeasurementPoint.cpp.
References boundSensor.
Referenced by TemperatureController::_checkPointForAlarms(), CSVConfigManager::_exportPointToCSV(), LoggerManager::_writeDataRow(), ConfigManager::alarmsAPI(), TemperatureController::ensureAlarmsForPoint(), TemperatureController::getBoundSensor(), TemperatureController::getPointsJson(), ConfigManager::loadPointsConfig(), ConfigManager::savePointsConfig(), and TemperatureController::unbindSensorFromPoint().
getCurrentTemp()
int16_t MeasurementPoint::getCurrentTemp () const
Get current temperature.
Returns
int16_t Current temperature in 째C (integer)
Definition at line 53 of file MeasurementPoint.cpp.
References currentTemp.
Referenced by TemperatureController::_checkPointForAlarms(), CSVConfigManager::_exportPointToCSV(), LoggerManager::_writeDataRow(), ConfigManager::alarmsAPI(), TemperatureController::getPointsJson(), and RegisterMap::updateFromMeasurementPoint().
getErrorStatus()
uint8_t MeasurementPoint::getErrorStatus () const
Get error status bits.
Returns
uint8_t Bit field representing error conditions
Definition at line 77 of file MeasurementPoint.cpp.
References errorStatus.
Referenced by TemperatureController::_checkPointForAlarms(), TemperatureController::getPointsJson(), and RegisterMap::updateFromMeasurementPoint().
getHighAlarmThreshold()
int16_t MeasurementPoint::getHighAlarmThreshold () const
Get high alarm threshold.
Returns
int16_t High temperature alarm threshold in 째C
Definition at line 69 of file MeasurementPoint.cpp.
References highAlarmThreshold.
Referenced by TemperatureController::_checkPointForAlarms(), CSVConfigManager::_exportPointToCSV(), ConfigManager::alarmsAPI(), RegisterMap::applyConfigFromMeasurementPoint(), TemperatureController::getPointsJson(), ConfigManager::pointsAPI(), and ConfigManager::savePointsConfig().
getLowAlarmThreshold()
int16_t MeasurementPoint::getLowAlarmThreshold () const
Get low alarm threshold.
Returns
int16_t Low temperature alarm threshold in 째C
Definition at line 65 of file MeasurementPoint.cpp.
References lowAlarmThreshold.
Referenced by TemperatureController::_checkPointForAlarms(), CSVConfigManager::_exportPointToCSV(), ConfigManager::alarmsAPI(), RegisterMap::applyConfigFromMeasurementPoint(), TemperatureController::getPointsJson(), ConfigManager::pointsAPI(), and ConfigManager::savePointsConfig().
getMaxTemp()
int16_t MeasurementPoint::getMaxTemp () const
Get maximum recorded temperature.
Returns
int16_t Maximum temperature since last reset
Definition at line 61 of file MeasurementPoint.cpp.
References maxTemp.
Referenced by CSVConfigManager::_exportPointToCSV(), TemperatureController::getPointsJson(), and RegisterMap::updateFromMeasurementPoint().
getMinTemp()
int16_t MeasurementPoint::getMinTemp () const
Get minimum recorded temperature.
Returns
int16_t Minimum temperature since last reset
Definition at line 57 of file MeasurementPoint.cpp.
References minTemp.
Referenced by CSVConfigManager::_exportPointToCSV(), TemperatureController::getPointsJson(), and RegisterMap::updateFromMeasurementPoint().
getName()
String MeasurementPoint::getName () const
Get measurement point name.
Returns
String Human-readable name
Definition at line 49 of file MeasurementPoint.cpp.
References name.
Referenced by CSVConfigManager::_exportPointToCSV(), LoggerManager::_generateCSVHeader(), TemperatureController::addAlarm(), ConfigManager::alarmsAPI(), TemperatureController::bindSensorToPointByChipSelect(), TemperatureController::bindSensorToPointByRom(), TemperatureController::getPointsJson(), ConfigManager::pointsAPI(), ConfigManager::savePointsConfig(), and TemperatureController::unbindSensorFromPoint().
resetMinMaxTemp()
void MeasurementPoint::resetMinMaxTemp ()
Reset min/max temperature records.
Sets min/max to current temperature value
Definition at line 148 of file MeasurementPoint.cpp.
References currentTemp, maxTemp, and minTemp.
setHighAlarmThreshold()
void MeasurementPoint::setHighAlarmThreshold (int16_t threshold)
Set high alarm threshold.
Parameters
[in] threshold High temperature alarm threshold in 째C
Definition at line 106 of file MeasurementPoint.cpp.
References address, highAlarmThreshold, LoggerManager::info(), name, and updateAlarmStatus().
Referenced by CSVConfigManager::_parseCSVLine(), ConfigManager::alarmsAPI(), RegisterMap::applyConfigToMeasurementPoint(), ConfigManager::loadPointsConfig(), ConfigManager::pointsAPI(), and ConfigManager::updatePointInConfig().
setLowAlarmThreshold()
void MeasurementPoint::setLowAlarmThreshold (int16_t threshold)
Set low alarm threshold.
Parameters
[in] threshold Low temperature alarm threshold in 째C
Definition at line 92 of file MeasurementPoint.cpp.
References address, LoggerManager::info(), lowAlarmThreshold, name, and updateAlarmStatus().
Referenced by CSVConfigManager::_parseCSVLine(), ConfigManager::alarmsAPI(), RegisterMap::applyConfigToMeasurementPoint(), ConfigManager::loadPointsConfig(), ConfigManager::pointsAPI(), and ConfigManager::updatePointInConfig().
setName()
void MeasurementPoint::setName (const String & newName)
Set measurement point name.
Parameters
[in] newName New human-readable name
Definition at line 81 of file MeasurementPoint.cpp.
References address, LoggerManager::info(), and name.
Referenced by CSVConfigManager::_parseCSVLine(), ConfigManager::alarmsAPI(), ConfigManager::loadPointsConfig(), ConfigManager::pointsAPI(), and ConfigManager::updatePointInConfig().
unbindSensor()
void MeasurementPoint::unbindSensor ()
Unbind the currently bound sensor.
Removes association with physical sensor
Definition at line 122 of file MeasurementPoint.cpp.
References boundSensor.
Referenced by TemperatureController::unbindSensorFromPoint().
update()
void MeasurementPoint::update ()
Update measurement point (call periodically)
Refreshes temperature reading and updates alarm/error status
Definition at line 130 of file MeasurementPoint.cpp.
References boundSensor, currentTemp, errorStatus, maxTemp, minTemp, and updateAlarmStatus().
updateAlarmStatus()
void MeasurementPoint::updateAlarmStatus () private
Update alarm status based on current temperature.
Internal method to evaluate alarm conditions and update status bits
Definition at line 153 of file MeasurementPoint.cpp.
References alarmStatus, currentTemp, errorStatus, highAlarmThreshold, and lowAlarmThreshold.
Referenced by setHighAlarmThreshold(), setLowAlarmThreshold(), and update().
Field Documentation
address
uint8_t MeasurementPoint::address private
Unique measurement point address.
Definition at line 163 of file MeasurementPoint.h.
Referenced by getAddress(), MeasurementPoint(), MeasurementPoint(), setHighAlarmThreshold(), setLowAlarmThreshold(), and setName().
alarmStatus
uint8_t MeasurementPoint::alarmStatus private
Bit field for alarm conditions.
Definition at line 171 of file MeasurementPoint.h.
Referenced by getAlarmStatus(), MeasurementPoint(), MeasurementPoint(), and updateAlarmStatus().
boundSensor
Sensor* MeasurementPoint::boundSensor private
Pointer to bound physical sensor.
Definition at line 174 of file MeasurementPoint.h.
Referenced by bindSensor(), getBoundSensor(), MeasurementPoint(), MeasurementPoint(), unbindSensor(), update(), and ~MeasurementPoint().
currentTemp
int16_t MeasurementPoint::currentTemp private
Latest temperature reading (째C)
Definition at line 166 of file MeasurementPoint.h.
Referenced by getCurrentTemp(), MeasurementPoint(), MeasurementPoint(), resetMinMaxTemp(), update(), and updateAlarmStatus().
errorStatus
uint8_t MeasurementPoint::errorStatus private
Bit field for error conditions.
Definition at line 172 of file MeasurementPoint.h.
Referenced by getErrorStatus(), MeasurementPoint(), MeasurementPoint(), update(), and updateAlarmStatus().
highAlarmThreshold
int16_t MeasurementPoint::highAlarmThreshold private
High temperature alarm threshold.
Definition at line 170 of file MeasurementPoint.h.
Referenced by getHighAlarmThreshold(), MeasurementPoint(), MeasurementPoint(), setHighAlarmThreshold(), and updateAlarmStatus().
lowAlarmThreshold
int16_t MeasurementPoint::lowAlarmThreshold private
Low temperature alarm threshold.
Definition at line 169 of file MeasurementPoint.h.
Referenced by getLowAlarmThreshold(), MeasurementPoint(), MeasurementPoint(), setLowAlarmThreshold(), and updateAlarmStatus().
maxTemp
int16_t MeasurementPoint::maxTemp private
Maximum recorded temperature.
Definition at line 168 of file MeasurementPoint.h.
Referenced by getMaxTemp(), MeasurementPoint(), MeasurementPoint(), resetMinMaxTemp(), and update().
minTemp
int16_t MeasurementPoint::minTemp private
Minimum recorded temperature.
Definition at line 167 of file MeasurementPoint.h.
Referenced by getMinTemp(), MeasurementPoint(), MeasurementPoint(), resetMinMaxTemp(), and update().
name
String MeasurementPoint::name private
Human-readable measurement point name.
Definition at line 164 of file MeasurementPoint.h.
Referenced by getName(), MeasurementPoint(), MeasurementPoint(), setHighAlarmThreshold(), setLowAlarmThreshold(), and setName().
The documentation for this class was generated from the following files:
include/MeasurementPoint.h
src/MeasurementPoint.cpp