Temperature Control System: TempModbusServer Class Reference
TempModbusServer Class Reference
Modbus RTU server implementation for temperature monitoring.
#include <TempModbusServer.h>
Public Member Functions
TempModbusServer (RegisterMap &regMap, uint8_t id, HardwareSerial &serialPort, int rx, int tx, int de, int baud=9600)
Construct a new Temp Modbus Server object.
~TempModbusServer ()
Destroy the Temp Modbus Server object.
bool begin ()
Initialize and start Modbus server.
void stop ()
Stop Modbus server.
void processCommands ()
Process pending commands from Modbus writes.
Static Private Member Functions
static ModbusMessage readHoldingRegistersWorker (ModbusMessage request)
Worker function for Read Holding Registers (FC03)
static ModbusMessage writeHoldingRegisterWorker (ModbusMessage request)
Worker function for Write Single Register (FC06)
static ModbusMessage writeMultipleRegistersWorker (ModbusMessage request)
Worker function for Write Multiple Registers (FC16)
Private Attributes
ModbusServerRTU * mbServer
Modbus RTU server instance.
RegisterMap & registerMap
Reference to register map.
uint8_t serverID
Modbus server ID (1-247)
HardwareSerial & serial
Hardware serial port reference.
int rxPin
UART RX pin.
int txPin
UART TX pin.
int dePin
RS485 Driver Enable pin.
int baudRate
Serial baud rate.
Static Private Attributes
static RegisterMap * registerMapPtr = nullptr
Static pointer for worker functions.
Detailed Description
Modbus RTU server implementation for temperature monitoring.
Provides Modbus RTU communication interface for reading temperature values, status information, and configuring alarm thresholds. Supports function codes 03 (Read Holding Registers), 06 (Write Single Register), and 16 (Write Multiple Registers).
Definition at line 36 of file TempModbusServer.h.
Constructor & Destructor Documentation
TempModbusServer()
TempModbusServer::TempModbusServer (RegisterMap & regMap, uint8_t id, HardwareSerial & serialPort, int rx, int tx, int de, int baud = 9600)
Construct a new Temp Modbus Server object.
Parameters
[in] regMap Reference to register map
[in] id Modbus server ID (1-247)
[in] serialPort Hardware serial port to use
[in] rx RX pin number
[in] tx TX pin number
[in] de Driver Enable pin for RS485
[in] baud Baud rate (default: 9600)
Definition at line 23 of file TempModbusServer.cpp.
References baudRate, dePin, LoggerManager::info(), mbServer, registerMap, registerMapPtr, rxPin, serial, serverID, and txPin.
~TempModbusServer()
TempModbusServer::~TempModbusServer ()
Destroy the Temp Modbus Server object.
Cleans up Modbus server resources
Definition at line 51 of file TempModbusServer.cpp.
References mbServer.
Member Function Documentation
begin()
bool TempModbusServer::begin ()
Initialize and start Modbus server.
Returns
true if server started successfully
false if initialization failed
Configures serial port, registers worker functions, and starts listening for Modbus requests
Definition at line 83 of file TempModbusServer.cpp.
References baudRate, LoggerManager::info(), mbServer, readHoldingRegistersWorker(), rxPin, serial, serverID, txPin, LoggerManager::warning(), writeHoldingRegisterWorker(), and writeMultipleRegistersWorker().
processCommands()
void TempModbusServer::processCommands ()
Process pending commands from Modbus writes.
Checks for pending commands in register map and executes them
Note
Should be called periodically from main loop
Definition at line 402 of file TempModbusServer.cpp.
References RegisterMap::ALARM_CONFIG_ERROR_ENABLE_BIT, RegisterMap::ALARM_CONFIG_ERROR_PRIORITY_MASK, RegisterMap::ALARM_CONFIG_ERROR_PRIORITY_SHIFT, RegisterMap::ALARM_CONFIG_HIGH_ENABLE_BIT, RegisterMap::ALARM_CONFIG_HIGH_PRIORITY_MASK, RegisterMap::ALARM_CONFIG_HIGH_PRIORITY_SHIFT, RegisterMap::ALARM_CONFIG_LOW_ENABLE_BIT, RegisterMap::ALARM_CONFIG_LOW_PRIORITY_MASK, RegisterMap::ALARM_CONFIG_LOW_PRIORITY_SHIFT, RegisterMap::CMD_APPLY_ALARM_CONFIG, LoggerManager::info(), registerMap, and LoggerManager::warning().
readHoldingRegistersWorker()
ModbusMessage TempModbusServer::readHoldingRegistersWorker (ModbusMessage request) static private
Worker function for Read Holding Registers (FC03)
Parameters
[in] request Modbus request message
Returns
ModbusMessage Response message with register data
Note
Static function called by Modbus library
Definition at line 174 of file TempModbusServer.cpp.
References LoggerManager::error(), LoggerManager::info(), and registerMapPtr.
Referenced by begin().
stop()
void TempModbusServer::stop ()
Stop Modbus server.
Stops server and releases resources
Definition at line 126 of file TempModbusServer.cpp.
writeHoldingRegisterWorker()
ModbusMessage TempModbusServer::writeHoldingRegisterWorker (ModbusMessage request) static private
Worker function for Write Single Register (FC06)
Parameters
[in] request Modbus request message
Returns
ModbusMessage Response message with confirmation
Note
Static function called by Modbus library
Definition at line 261 of file TempModbusServer.cpp.
References LoggerManager::error(), LoggerManager::info(), and registerMapPtr.
Referenced by begin().
writeMultipleRegistersWorker()
ModbusMessage TempModbusServer::writeMultipleRegistersWorker (ModbusMessage request) static private
Worker function for Write Multiple Registers (FC16)
Parameters
[in] request Modbus request message
Returns
ModbusMessage Response message with confirmation
Note
Static function called by Modbus library
Definition at line 335 of file TempModbusServer.cpp.
References LoggerManager::error(), LoggerManager::info(), and registerMapPtr.
Referenced by begin().
Field Documentation
baudRate
int TempModbusServer::baudRate private
Serial baud rate.
Definition at line 45 of file TempModbusServer.h.
Referenced by begin(), and TempModbusServer().
dePin
int TempModbusServer::dePin private
RS485 Driver Enable pin.
Definition at line 44 of file TempModbusServer.h.
Referenced by TempModbusServer().
mbServer
ModbusServerRTU* TempModbusServer::mbServer private
Modbus RTU server instance.
Definition at line 38 of file TempModbusServer.h.
Referenced by begin(), TempModbusServer(), and ~TempModbusServer().
registerMap
RegisterMap& TempModbusServer::registerMap private
Reference to register map.
Definition at line 39 of file TempModbusServer.h.
Referenced by processCommands(), and TempModbusServer().
registerMapPtr
RegisterMap * TempModbusServer::registerMapPtr = nullptr static private
Static pointer for worker functions.
Definition at line 73 of file TempModbusServer.h.
Referenced by readHoldingRegistersWorker(), TempModbusServer(), writeHoldingRegisterWorker(), and writeMultipleRegistersWorker().
rxPin
int TempModbusServer::rxPin private
UART RX pin.
Definition at line 42 of file TempModbusServer.h.
Referenced by begin(), and TempModbusServer().
serial
HardwareSerial& TempModbusServer::serial private
Hardware serial port reference.
Definition at line 41 of file TempModbusServer.h.
Referenced by begin(), and TempModbusServer().
serverID
uint8_t TempModbusServer::serverID private
Modbus server ID (1-247)
Definition at line 40 of file TempModbusServer.h.
Referenced by begin(), and TempModbusServer().
txPin
int TempModbusServer::txPin private
UART TX pin.
Definition at line 43 of file TempModbusServer.h.
Referenced by begin(), and TempModbusServer().
The documentation for this class was generated from the following files:
include/TempModbusServer.h
src/TempModbusServer.cpp