Temperature Control System: Sensor Class Reference
Sensor Class Reference
Abstract temperature sensor interface.
#include <Sensor.h>
Public Member Functions
Sensor (SensorType type, uint8_t address, const String &name)
Construct a new Sensor object.
~Sensor ()
Destroy the Sensor object.
void setupDS18B20 (uint8_t pin, const uint8_t *deviceAddress)
Configure sensor as DS18B20.
void setupPT1000 (uint8_t csPin, uint8_t maxAddress)
Configure sensor as PT1000.
bool initialize ()
Initialize sensor hardware.
bool readTemperature ()
Read temperature from sensor.
SensorType getType () const
Get sensor type.
uint8_t getAddress () const
Get sensor logical address.
String getName () const
Get sensor name.
void setName (const String &newName)
Set sensor name.
int16_t getCurrentTemp () const
Get current temperature.
int16_t getMinTemp () const
Get minimum recorded temperature.
int16_t getMaxTemp () const
Get maximum recorded temperature.
int16_t getLowAlarmThreshold () const
Get low temperature alarm threshold.
int16_t getHighAlarmThreshold () const
Get high temperature alarm threshold.
uint8_t getAlarmStatus () const
Get alarm status flags.
uint8_t getErrorStatus () const
Get error status flags.
uint8_t getPT1000ChipSelectPin () const
Get PT1000 chip select pin.
void setAddress (uint8_t newAddress)
Set sensor logical address.
void setLowAlarmThreshold (int16_t threshold)
Set low temperature alarm threshold.
void setHighAlarmThreshold (int16_t threshold)
Set high temperature alarm threshold.
const uint8_t * getDS18B20Address () const
Get DS18B20 ROM address.
void resetMinMaxTemp ()
Reset min/max temperature records.
void updateAlarmStatus ()
Update alarm status based on current temperature.
String getDS18B20RomString () const
Get DS18B20 ROM address as hex string.
void getDS18B20RomArray (uint8_t out[8]) const
Get DS18B20 ROM address as array.
uint8_t getOneWirePin ()
Get OneWire bus pin.
Private Attributes
uint8_t address
Logical sensor address.
String name
Human-readable sensor name.
SensorType type
Type of sensor (DS18B20 or PT1000)
int16_t currentTemp
Current temperature in 0.1°C units.
int16_t minTemp
Minimum recorded temperature.
int16_t maxTemp
Maximum recorded temperature.
int16_t lowAlarmThreshold
Low temperature alarm threshold.
int16_t highAlarmThreshold
High temperature alarm threshold.
uint8_t alarmStatus
Current alarm status flags.
uint8_t errorStatus
Current error status flags.
OneWire * oneWire
OneWire interface for DS18B20.
DallasTemperature * dallasTemperature
Dallas temperature library instance.
Adafruit_MAX31865 * max31865
MAX31865 interface for PT1000.
union {
struct {
uint8_t oneWirePin
OneWire bus GPIO pin.
uint8_t oneWireAddress [8]
8-byte ROM address
} ds18b20
DS18B20 connection parameters.
struct {
uint8_t csPin
SPI chip select pin.
uint8_t maxAddress
MAX31865 I2C address.
} pt1000
PT1000 connection parameters.
} connection
Union for sensor-specific connection details.
Detailed Description
Abstract temperature sensor interface.
Provides unified access to DS18B20 and PT1000 temperature sensors with common functionality for temperature reading, alarm management, and error handling.
Definition at line 63 of file Sensor.h.
Constructor & Destructor Documentation
Sensor()
Sensor::Sensor (SensorType type, uint8_t address, const String & name)
Construct a new Sensor object.
Parameters
[in] type Sensor type (DS18B20 or PT1000)
[in] address Logical address for the sensor
[in] name Human-readable name for the sensor
Definition at line 26 of file Sensor.cpp.
References address, alarmStatus, connection, currentTemp, dallasTemperature, DS18B20, errorStatus, highAlarmThreshold, lowAlarmThreshold, max31865, maxTemp, minTemp, name, oneWire, and type.
~Sensor()
Sensor::~Sensor ()
Destroy the Sensor object.
Cleans up hardware interfaces and dynamic memory
Definition at line 42 of file Sensor.cpp.
References dallasTemperature, max31865, and oneWire.
Member Function Documentation
getAddress()
uint8_t Sensor::getAddress () const
Get sensor logical address.
Returns
uint8_t Sensor address
Definition at line 172 of file Sensor.cpp.
References address.
getAlarmStatus()
uint8_t Sensor::getAlarmStatus () const
Get alarm status flags.
Returns
uint8_t Bitmask of active alarms
See also
ALARM_LOW_TEMP, ALARM_HIGH_TEMP
Definition at line 181 of file Sensor.cpp.
References alarmStatus.
getCurrentTemp()
int16_t Sensor::getCurrentTemp () const
Get current temperature.
Returns
int16_t Temperature in 0.1°C units
Definition at line 176 of file Sensor.cpp.
References currentTemp.
getDS18B20Address()
const uint8_t * Sensor::getDS18B20Address () const
Get DS18B20 ROM address.
Returns
const uint8_t* Pointer to 8-byte ROM address
Note
Only valid for DS18B20 sensors
Definition at line 188 of file Sensor.cpp.
References connection, DS18B20, and type.
getDS18B20RomArray()
void Sensor::getDS18B20RomArray (uint8_t out[8]) const
Get DS18B20 ROM address as array.
Parameters
[out] out 8-byte array to receive ROM address
Definition at line 223 of file Sensor.cpp.
References connection, DS18B20, and type.
Referenced by TemperatureController::getPointsJson().
getDS18B20RomString()
String Sensor::getDS18B20RomString () const
Get DS18B20 ROM address as hex string.
Returns
String ROM address in hexadecimal format
Definition at line 213 of file Sensor.cpp.
References connection, DS18B20, and type.
Referenced by CSVConfigManager::_exportPointToCSV(), TemperatureController::addSensor(), TemperatureController::getPointsJson(), TemperatureController::getSensorsJson(), ConfigManager::savePointsConfig(), ConfigManager::sensorAPI(), and TemperatureController::unbindSensorFromPoint().
getErrorStatus()
uint8_t Sensor::getErrorStatus () const
Get error status flags.
Returns
uint8_t Bitmask of active errors
See also
ERROR_COMMUNICATION, ERROR_OUT_OF_RANGE, ERROR_DISCONNECTED
Definition at line 182 of file Sensor.cpp.
References errorStatus.
getHighAlarmThreshold()
int16_t Sensor::getHighAlarmThreshold () const
Get high temperature alarm threshold.
Returns
int16_t High threshold in 0.1°C units
Definition at line 180 of file Sensor.cpp.
References highAlarmThreshold.
getLowAlarmThreshold()
int16_t Sensor::getLowAlarmThreshold () const
Get low temperature alarm threshold.
Returns
int16_t Low threshold in 0.1°C units
Definition at line 179 of file Sensor.cpp.
References lowAlarmThreshold.
getMaxTemp()
int16_t Sensor::getMaxTemp () const
Get maximum recorded temperature.
Returns
int16_t Maximum temperature in 0.1°C units
Definition at line 178 of file Sensor.cpp.
References maxTemp.
getMinTemp()
int16_t Sensor::getMinTemp () const
Get minimum recorded temperature.
Returns
int16_t Minimum temperature in 0.1°C units
Definition at line 177 of file Sensor.cpp.
References minTemp.
getName()
String Sensor::getName () const
Get sensor name.
Returns
String Sensor name
Definition at line 173 of file Sensor.cpp.
References name.
Referenced by TemperatureController::discoverDS18B20Sensors(), TemperatureController::discoverPTSensors(), and TemperatureController::unbindSensorFromPointBySensor().
getOneWirePin()
uint8_t Sensor::getOneWirePin () inline
Get OneWire bus pin.
Returns
uint8_t OneWire pin number
Definition at line 236 of file Sensor.h.
References connection.
Referenced by TemperatureController::discoverDS18B20Sensors(), and TemperatureController::getSensorBus().
getPT1000ChipSelectPin()
uint8_t Sensor::getPT1000ChipSelectPin () const
Get PT1000 chip select pin.
Returns
uint8_t Chip select pin number
Definition at line 208 of file Sensor.cpp.
References connection, PT1000, and type.
Referenced by TemperatureController::addSensor(), TemperatureController::discoverPTSensors(), TemperatureController::getPointsJson(), TemperatureController::getSensorBus(), ConfigManager::savePointsConfig(), ConfigManager::sensorAPI(), and TemperatureController::unbindSensorFromPoint().
getType()
SensorType Sensor::getType () const
Get sensor type.
Returns
SensorType DS18B20 or PT1000
Definition at line 171 of file Sensor.cpp.
References type.
Referenced by CSVConfigManager::_exportPointToCSV(), TemperatureController::addSensor(), TemperatureController::getPointsJson(), TemperatureController::getSensorBus(), TemperatureController::getSensorsJson(), ConfigManager::savePointsConfig(), and TemperatureController::unbindSensorFromPoint().
initialize()
bool Sensor::initialize ()
Initialize sensor hardware.
Returns
true if initialization successful
false if hardware initialization failed
Definition at line 67 of file Sensor.cpp.
References connection, dallasTemperature, DS18B20, max31865, oneWire, PT1000, and type.
Referenced by TemperatureController::discoverDS18B20Sensors(), TemperatureController::discoverPTSensors(), and ConfigManager::loadPointsConfig().
readTemperature()
bool Sensor::readTemperature ()
Read temperature from sensor.
Returns
true if reading successful
false if reading failed
Updates internal temperature values and error status
Definition at line 118 of file Sensor.cpp.
References connection, currentTemp, dallasTemperature, DS18B20, ERROR_COMMUNICATION, ERROR_DISCONNECTED, ERROR_OUT_OF_RANGE, errorStatus, max31865, maxTemp, minTemp, PT1000, type, and updateAlarmStatus().
resetMinMaxTemp()
void Sensor::resetMinMaxTemp ()
Reset min/max temperature records.
Definition at line 195 of file Sensor.cpp.
References currentTemp, maxTemp, and minTemp.
setAddress()
void Sensor::setAddress (uint8_t newAddress)
Set sensor logical address.
Parameters
[in] newAddress New address value
Definition at line 184 of file Sensor.cpp.
References address.
setHighAlarmThreshold()
void Sensor::setHighAlarmThreshold (int16_t threshold)
Set high temperature alarm threshold.
Parameters
[in] threshold Threshold in 0.1°C units
Definition at line 186 of file Sensor.cpp.
References highAlarmThreshold, and updateAlarmStatus().
setLowAlarmThreshold()
void Sensor::setLowAlarmThreshold (int16_t threshold)
Set low temperature alarm threshold.
Parameters
[in] threshold Threshold in 0.1°C units
Definition at line 185 of file Sensor.cpp.
References lowAlarmThreshold, and updateAlarmStatus().
setName()
void Sensor::setName (const String & newName)
Set sensor name.
Parameters
[in] newName New name for sensor
Definition at line 174 of file Sensor.cpp.
References name.
setupDS18B20()
void Sensor::setupDS18B20 (uint8_t pin, const uint8_t * deviceAddress)
Configure sensor as DS18B20.
Parameters
[in] pin OneWire bus pin number
[in] deviceAddress 8-byte ROM address of DS18B20
Definition at line 57 of file Sensor.cpp.
References connection.
Referenced by TemperatureController::discoverDS18B20Sensors(), and ConfigManager::loadPointsConfig().
setupPT1000()
void Sensor::setupPT1000 (uint8_t csPin, uint8_t maxAddress)
Configure sensor as PT1000.
Parameters
[in] csPin SPI chip select pin
[in] maxAddress MAX31865 I2C address
Definition at line 62 of file Sensor.cpp.
References connection, csPin, and maxAddress.
Referenced by TemperatureController::discoverPTSensors(), and ConfigManager::loadPointsConfig().
updateAlarmStatus()
void Sensor::updateAlarmStatus ()
Update alarm status based on current temperature.
Call after reading temperature or changing thresholds
Definition at line 200 of file Sensor.cpp.
References ALARM_HIGH_TEMP, ALARM_LOW_TEMP, alarmStatus, currentTemp, errorStatus, highAlarmThreshold, and lowAlarmThreshold.
Referenced by readTemperature(), setHighAlarmThreshold(), and setLowAlarmThreshold().
Field Documentation
address
uint8_t Sensor::address private
Logical sensor address.
Definition at line 239 of file Sensor.h.
Referenced by getAddress(), Sensor(), and setAddress().
alarmStatus
uint8_t Sensor::alarmStatus private
Current alarm status flags.
Definition at line 248 of file Sensor.h.
Referenced by getAlarmStatus(), Sensor(), and updateAlarmStatus().
[union]
union { ... } Sensor::connection
Union for sensor-specific connection details.
Sensor connection details
Referenced by getDS18B20Address(), getDS18B20RomArray(), getDS18B20RomString(), getOneWirePin(), getPT1000ChipSelectPin(), initialize(), readTemperature(), Sensor(), setupDS18B20(), and setupPT1000().
csPin
uint8_t Sensor::csPin
SPI chip select pin.
Definition at line 272 of file Sensor.h.
Referenced by setupPT1000().
currentTemp
int16_t Sensor::currentTemp private
Current temperature in 0.1°C units.
Definition at line 243 of file Sensor.h.
Referenced by getCurrentTemp(), readTemperature(), resetMinMaxTemp(), Sensor(), and updateAlarmStatus().
dallasTemperature
DallasTemperature* Sensor::dallasTemperature private
Dallas temperature library instance.
Definition at line 253 of file Sensor.h.
Referenced by initialize(), readTemperature(), Sensor(), and ~Sensor().
[struct]
struct { ... } Sensor::ds18b20
DS18B20 connection parameters.
errorStatus
uint8_t Sensor::errorStatus private
Current error status flags.
Definition at line 249 of file Sensor.h.
Referenced by getErrorStatus(), readTemperature(), Sensor(), and updateAlarmStatus().
highAlarmThreshold
int16_t Sensor::highAlarmThreshold private
High temperature alarm threshold.
Definition at line 247 of file Sensor.h.
Referenced by getHighAlarmThreshold(), Sensor(), setHighAlarmThreshold(), and updateAlarmStatus().
lowAlarmThreshold
int16_t Sensor::lowAlarmThreshold private
Low temperature alarm threshold.
Definition at line 246 of file Sensor.h.
Referenced by getLowAlarmThreshold(), Sensor(), setLowAlarmThreshold(), and updateAlarmStatus().
max31865
Adafruit_MAX31865* Sensor::max31865 private
MAX31865 interface for PT1000.
Definition at line 254 of file Sensor.h.
Referenced by initialize(), readTemperature(), Sensor(), and ~Sensor().
maxAddress
uint8_t Sensor::maxAddress
MAX31865 I2C address.
Definition at line 273 of file Sensor.h.
Referenced by setupPT1000().
maxTemp
int16_t Sensor::maxTemp private
Maximum recorded temperature.
Definition at line 245 of file Sensor.h.
Referenced by getMaxTemp(), readTemperature(), resetMinMaxTemp(), and Sensor().
minTemp
int16_t Sensor::minTemp private
Minimum recorded temperature.
Definition at line 244 of file Sensor.h.
Referenced by getMinTemp(), readTemperature(), resetMinMaxTemp(), and Sensor().
name
String Sensor::name private
Human-readable sensor name.
Definition at line 240 of file Sensor.h.
Referenced by getName(), Sensor(), and setName().
oneWire
OneWire* Sensor::oneWire private
OneWire interface for DS18B20.
Definition at line 252 of file Sensor.h.
Referenced by initialize(), Sensor(), and ~Sensor().
oneWireAddress
uint8_t Sensor::oneWireAddress[8]
8-byte ROM address
Definition at line 265 of file Sensor.h.
oneWirePin
uint8_t Sensor::oneWirePin
OneWire bus GPIO pin.
Definition at line 264 of file Sensor.h.
[struct]
struct { ... } Sensor::pt1000
PT1000 connection parameters.
type
SensorType Sensor::type private
Type of sensor (DS18B20 or PT1000)
Definition at line 241 of file Sensor.h.
Referenced by getDS18B20Address(), getDS18B20RomArray(), getDS18B20RomString(), getPT1000ChipSelectPin(), getType(), initialize(), readTemperature(), and Sensor().
The documentation for this class was generated from the following files:
include/Sensor.h
src/Sensor.cpp