Temperature Control System: Alarm Class Reference
Alarm Class Reference
Main alarm class for temperature monitoring system.
#include <Alarm.h>
Public Member Functions
Alarm (AlarmType type, MeasurementPoint *source, AlarmPriority priority=AlarmPriority::PRIORITY_MEDIUM)
Constructor for creating a new alarm.
~Alarm ()
Destructor for alarm cleanup.
AlarmType getType () const
Get the alarm type.
AlarmStage getStage () const
Get the current alarm stage.
AlarmPriority getPriority () const
Get the alarm priority.
MeasurementPoint * getSource () const
Get the source measurement point.
unsigned long getTimestamp () const
Get the alarm creation timestamp.
unsigned long getAcknowledgedTime () const
Get the acknowledgment timestamp.
unsigned long getClearedTime () const
Get the cleared timestamp.
String getMessage () const
Get the alarm message.
bool isActive () const
Check if alarm is currently active.
bool isAcknowledged () const
Check if alarm has been acknowledged.
bool isResolved () const
Check if alarm is resolved.
void acknowledge ()
Acknowledge the alarm.
void clear ()
Clear the alarm condition.
void resolve ()
Resolve the alarm completely.
void reactivate ()
Reactivate a previously cleared alarm.
bool updateCondition ()
Update alarm condition based on current measurement.
String getDisplayText () const
Get formatted display text for UI.
String getStatusText () const
Get status text description.
void setDelayTime (unsigned long delayMs)
Set the alarm delay time.
unsigned long getDelayTime () const
Get the alarm delay time.
bool isDelayElapsed () const
Check if the alarm delay period has elapsed.
bool operator< (const Alarm &other) const
Less-than comparison operator for alarm sorting.
bool operator== (const Alarm &other) const
Equality comparison operator.
String getTypeString () const
Get alarm type as string.
String getStageString () const
Get alarm stage as string.
String getConfigKey () const
Get the configuration key for this alarm.
void setConfigKey (const String &key)
Set the configuration key.
bool isEnabled () const
Check if alarm is enabled in configuration.
void setEnabled (bool enabled)
Enable or disable the alarm.
uint8_t getPointAddress () const
Get the measurement point address.
void setPriority (AlarmPriority priority)
Set the alarm priority.
void setStage (AlarmStage stage)
Set the alarm stage.
void setHysteresis (int16_t hysteresis)
Set the hysteresis value for alarm triggering.
int16_t getHysteresis () const
Get the hysteresis value.
void setAcknowledgedDelay (unsigned long delay)
Set the acknowledged delay period.
unsigned long getAcknowledgedDelay () const
Get the acknowledged delay period.
bool isAcknowledgedDelayElapsed () const
Check if acknowledged delay has elapsed.
unsigned long getAcknowledgedTimeLeft () const
Get remaining acknowledged delay time.
Private Member Functions
void _updateMessage ()
Update the alarm display message.
bool _checkCondition ()
Check if alarm condition is currently met.
String _getPriorityString () const
Get priority as string (internal version)
String _getPriorityString (AlarmPriority priority) const
Get priority as string with parameter.
Private Attributes
AlarmType _type
Type of alarm (temperature, sensor error, etc.)
AlarmStage _stage
Current lifecycle stage.
AlarmPriority _priority
Priority level for handling.
MeasurementPoint * _source
Associated measurement point.
unsigned long _timestamp
When alarm was created (millis)
unsigned long _acknowledgedTime
When alarm was acknowledged (millis)
unsigned long _clearedTime
When condition was cleared (millis)
int16_t _hysteresis
Hysteresis value to prevent flapping.
unsigned long _delayTime
Delay before auto-resolve (millis)
unsigned long _acknowledgedDelay
Delay after acknowledgment (millis)
String _configKey
Configuration key "alarm_<point>_<type>".
bool _enabled
Whether alarm is active in configuration.
String _message
Human-readable alarm description.
Detailed Description
Main alarm class for temperature monitoring system.
Manages individual alarm instances with full lifecycle tracking, priority handling, and integration with measurement points
Definition at line 70 of file Alarm.h.
Constructor & Destructor Documentation
Alarm()
Alarm::Alarm (AlarmType type, MeasurementPoint * source, AlarmPriority priority = AlarmPriority::PRIORITY_MEDIUM)
Constructor for creating a new alarm.
Constructor - Creates a new alarm instance.
Parameters
[in] type The type of alarm being created
[in] source Pointer to the measurement point that triggered this alarm
[in] priority Priority level for this alarm (default: PRIORITY_MEDIUM)
Note
The alarm is created in NEW stage and timestamp is set to current time
Parameters
[in] type Type of alarm being created
[in] source Pointer to measurement point that triggered the alarm
[in] priority Priority level for the alarm
Initializes alarm with NEW stage, current timestamp, and default timeouts. Generates configuration key and logs alarm creation event.
Definition at line 46 of file Alarm.cpp.
References _acknowledgedDelay, _acknowledgedTime, _clearedTime, _configKey, _delayTime, _enabled, _hysteresis, _priority, _source, _stage, _timestamp, _type, _updateMessage(), getTypeString(), LoggerManager::info(), and NEW.
Referenced by operator<(), and operator==().
~Alarm()
Alarm::~Alarm ()
Destructor for alarm cleanup.
Destructor - Cleans up alarm instance.
Ensures proper cleanup of alarm resources
Logs alarm destruction event and outputs debug information
Definition at line 88 of file Alarm.cpp.
References _source, getTypeString(), and LoggerManager::info().
Member Function Documentation
_checkCondition()
bool Alarm::_checkCondition () private
Check if alarm condition is currently met.
Returns
bool True if triggering condition is present
Definition at line 195 of file Alarm.cpp.
References _hysteresis, _source, _stage, _type, ACKNOWLEDGED, ACTIVE, CLEARED, getStageString(), HIGH_TEMPERATURE, LOW_TEMPERATURE, SENSOR_DISCONNECTED, and SENSOR_ERROR.
Referenced by updateCondition().
_getPriorityString() [1/2]
String Alarm::_getPriorityString () const private
Get priority as string (internal version)
Returns
String Priority level as text
Definition at line 397 of file Alarm.cpp.
References _priority, PRIORITY_CRITICAL, PRIORITY_HIGH, PRIORITY_LOW, and PRIORITY_MEDIUM.
Referenced by acknowledge(), setPriority(), and updateCondition().
_getPriorityString() [2/2]
String Alarm::_getPriorityString (AlarmPriority priority) const private
Get priority as string with parameter.
Parameters
[in] priority Priority level to convert
Returns
String Priority level as text
Definition at line 657 of file Alarm.cpp.
References PRIORITY_CRITICAL, PRIORITY_HIGH, PRIORITY_LOW, and PRIORITY_MEDIUM.
_updateMessage()
void Alarm::_updateMessage () private
Update the alarm display message.
Generates human-readable message based on current alarm state
Definition at line 372 of file Alarm.cpp.
References _message, and getDisplayText().
Referenced by acknowledge(), Alarm(), clear(), reactivate(), resolve(), and updateCondition().
acknowledge()
void Alarm::acknowledge ()
Acknowledge the alarm.
Transitions alarm to ACKNOWLEDGED stage, indicating operator awareness
Transitions alarm from NEW or ACTIVE stage to ACKNOWLEDGED stage. Records acknowledgment timestamp and logs the event.
Definition at line 107 of file Alarm.cpp.
References _acknowledgedTime, _getPriorityString(), _source, _stage, _type, _updateMessage(), ACKNOWLEDGED, ACTIVE, getStageString(), getTypeString(), HIGH_TEMPERATURE, LoggerManager::info(), LoggerManager::logAlarmStateChange(), and NEW.
Referenced by TemperatureController::acknowledgeHighestPriorityAlarm().
clear()
void Alarm::clear ()
Clear the alarm condition.
Marks that the triggering condition has been resolved
Definition at line 140 of file Alarm.cpp.
References _clearedTime, _source, _stage, _updateMessage(), ACKNOWLEDGED, ACTIVE, CLEARED, getTypeString(), and LoggerManager::info().
Referenced by updateCondition().
getAcknowledgedDelay()
unsigned long Alarm::getAcknowledgedDelay () const
Get the acknowledged delay period.
Returns
unsigned long Current acknowledged delay in milliseconds
Definition at line 632 of file Alarm.cpp.
References _acknowledgedDelay.
getAcknowledgedTime()
unsigned long Alarm::getAcknowledgedTime () const inline
Get the acknowledgment timestamp.
Returns
unsigned long Timestamp when alarm was acknowledged (millis)
Definition at line 122 of file Alarm.h.
References _acknowledgedTime.
getAcknowledgedTimeLeft()
unsigned long Alarm::getAcknowledgedTimeLeft () const
Get remaining acknowledged delay time.
Returns
unsigned long Milliseconds remaining in acknowledged delay
Definition at line 643 of file Alarm.cpp.
References _acknowledgedDelay, _acknowledgedTime, _stage, and ACKNOWLEDGED.
getClearedTime()
unsigned long Alarm::getClearedTime () const inline
Get the cleared timestamp.
Returns
unsigned long Timestamp when alarm condition was cleared (millis)
Definition at line 128 of file Alarm.h.
References _clearedTime.
getConfigKey()
String Alarm::getConfigKey () const
Get the configuration key for this alarm.
Returns
String Configuration key in format "alarm_<point>_<type>"
Definition at line 423 of file Alarm.cpp.
References _configKey.
getDelayTime()
unsigned long Alarm::getDelayTime () const inline
Get the alarm delay time.
Returns
unsigned long Current delay time in milliseconds
Definition at line 210 of file Alarm.h.
References _delayTime.
getDisplayText()
String Alarm::getDisplayText () const
Get formatted display text for UI.
Returns
String Human-readable text for display interfaces
Definition at line 336 of file Alarm.cpp.
References _source, _stage, _type, ACKNOWLEDGED, HIGH_TEMPERATURE, LOW_TEMPERATURE, SENSOR_DISCONNECTED, and SENSOR_ERROR.
Referenced by _updateMessage().
getHysteresis()
int16_t Alarm::getHysteresis () const inline
Get the hysteresis value.
Returns
int16_t Current hysteresis setting
Definition at line 298 of file Alarm.h.
References _hysteresis.
Referenced by ConfigManager::saveAlarmsConfig().
getMessage()
String Alarm::getMessage () const inline
Get the alarm message.
Returns
String Human-readable alarm description
Definition at line 134 of file Alarm.h.
References _message.
getPointAddress()
uint8_t Alarm::getPointAddress () const inline
Get the measurement point address.
Returns
uint8_t Address of associated measurement point (255 if no source)
Definition at line 274 of file Alarm.h.
References _source.
Referenced by CSVConfigManager::_getAlarmPriorityForPoint(), and ConfigManager::saveAlarmsConfig().
getPriority()
AlarmPriority Alarm::getPriority () const inline
Get the alarm priority.
Returns
AlarmPriority The priority level of this alarm
Definition at line 104 of file Alarm.h.
References _priority.
Referenced by CSVConfigManager::_getAlarmPriorityForPoint(), AlarmComparator::operator()(), and ConfigManager::saveAlarmsConfig().
getSource()
MeasurementPoint * Alarm::getSource () const inline
Get the source measurement point.
Returns
MeasurementPoint* Pointer to the measurement point that triggered this alarm
Definition at line 110 of file Alarm.h.
References _source.
getStage()
AlarmStage Alarm::getStage () const inline
Get the current alarm stage.
Returns
AlarmStage The current lifecycle stage
Definition at line 98 of file Alarm.h.
References _stage.
getStageString()
String Alarm::getStageString () const
Get alarm stage as string.
Returns
String Human-readable alarm stage description
Definition at line 386 of file Alarm.cpp.
References _stage, ACKNOWLEDGED, ACTIVE, CLEARED, NEW, and RESOLVED.
Referenced by _checkCondition(), acknowledge(), getStatusText(), and updateCondition().
getStatusText()
String Alarm::getStatusText () const
Get status text description.
Returns
String Current alarm status as text
Definition at line 364 of file Alarm.cpp.
References _source, getStageString(), and getTypeString().
Referenced by TemperatureController::acknowledgeHighestPriorityAlarm().
getTimestamp()
unsigned long Alarm::getTimestamp () const inline
Get the alarm creation timestamp.
Returns
unsigned long Timestamp when alarm was created (millis)
Definition at line 116 of file Alarm.h.
References _timestamp.
Referenced by TemperatureController::_updateAlarmQueues(), and AlarmComparator::operator()().
getType()
AlarmType Alarm::getType () const inline
Get the alarm type.
Returns
AlarmType The type of this alarm
Definition at line 92 of file Alarm.h.
References _type.
Referenced by CSVConfigManager::_getAlarmPriorityForPoint(), and ConfigManager::saveAlarmsConfig().
getTypeString()
String Alarm::getTypeString () const
Get alarm type as string.
Returns
String Human-readable alarm type description
Definition at line 376 of file Alarm.cpp.
References _type, HIGH_TEMPERATURE, LOW_TEMPERATURE, SENSOR_DISCONNECTED, and SENSOR_ERROR.
Referenced by acknowledge(), TemperatureController::addAlarm(), Alarm(), clear(), getStatusText(), reactivate(), resolve(), setEnabled(), setHysteresis(), setPriority(), updateCondition(), and ~Alarm().
isAcknowledged()
bool Alarm::isAcknowledged () const inline
Check if alarm has been acknowledged.
Returns
bool True if alarm is in ACKNOWLEDGED or CLEARED stage
Definition at line 146 of file Alarm.h.
References _stage, ACKNOWLEDGED, and CLEARED.
isAcknowledgedDelayElapsed()
bool Alarm::isAcknowledgedDelayElapsed () const
Check if acknowledged delay has elapsed.
Returns
bool True if acknowledged delay period has passed
Definition at line 636 of file Alarm.cpp.
References _acknowledgedDelay, _acknowledgedTime, _stage, and ACKNOWLEDGED.
Referenced by updateCondition().
isActive()
bool Alarm::isActive () const inline
Check if alarm is currently active.
Returns
bool True if alarm is in ACTIVE or ACKNOWLEDGED stage
Definition at line 140 of file Alarm.h.
References _stage, ACKNOWLEDGED, and ACTIVE.
isDelayElapsed()
bool Alarm::isDelayElapsed () const
Check if the alarm delay period has elapsed.
Returns
bool True if delay time has passed since alarm creation
Definition at line 329 of file Alarm.cpp.
References _clearedTime, _delayTime, _stage, and CLEARED.
isEnabled()
bool Alarm::isEnabled () const inline
Check if alarm is enabled in configuration.
Returns
bool True if alarm is active in system configuration
Definition at line 262 of file Alarm.h.
References _enabled.
Referenced by ConfigManager::saveAlarmsConfig().
isResolved()
bool Alarm::isResolved () const inline
Check if alarm is resolved.
Returns
bool True if alarm is in RESOLVED stage
Definition at line 152 of file Alarm.h.
References _stage, and RESOLVED.
operator<()
bool Alarm::operator< (const Alarm & other) const
Less-than comparison operator for alarm sorting.
Parameters
[in] other The alarm to compare against
Returns
bool True if this alarm has lower priority/older timestamp
Definition at line 407 of file Alarm.cpp.
References _priority, _timestamp, and Alarm().
operator==()
bool Alarm::operator== (const Alarm & other) const
Equality comparison operator.
Parameters
[in] other The alarm to compare against
Returns
bool True if alarms are equivalent
Definition at line 415 of file Alarm.cpp.
References _source, _timestamp, _type, and Alarm().
reactivate()
void Alarm::reactivate ()
Reactivate a previously cleared alarm.
Used when alarm condition returns before full resolution
Definition at line 176 of file Alarm.cpp.
References _acknowledgedTime, _clearedTime, _source, _stage, _updateMessage(), ACKNOWLEDGED, ACTIVE, CLEARED, getTypeString(), and LoggerManager::warning().
resolve()
void Alarm::resolve ()
Resolve the alarm completely.
Transitions alarm to RESOLVED stage, indicating full resolution
Definition at line 159 of file Alarm.cpp.
References _source, _stage, _updateMessage(), getTypeString(), LoggerManager::info(), and RESOLVED.
Referenced by updateCondition().
setAcknowledgedDelay()
void Alarm::setAcknowledgedDelay (unsigned long delay)
Set the acknowledged delay period.
Parameters
[in] delay Time in milliseconds before auto-resolution after acknowledgment
Definition at line 628 of file Alarm.cpp.
References _acknowledgedDelay.
Referenced by TemperatureController::addAlarm().
setConfigKey()
void Alarm::setConfigKey (const String & key)
Set the configuration key.
Parameters
[in] key Configuration key string
Definition at line 427 of file Alarm.cpp.
References _configKey.
Referenced by TemperatureController::addAlarm(), TemperatureController::createAlarm(), and TemperatureController::ensureAlarmsForPoint().
setDelayTime()
void Alarm::setDelayTime (unsigned long delayMs) inline
Set the alarm delay time.
Parameters
[in] delayMs Delay time in milliseconds before auto-resolution
Definition at line 204 of file Alarm.h.
References _delayTime.
setEnabled()
void Alarm::setEnabled (bool enabled)
Enable or disable the alarm.
Parameters
[in] enabled True to enable, false to disable
Definition at line 459 of file Alarm.cpp.
References _enabled, _source, getTypeString(), and LoggerManager::info().
Referenced by CSVConfigManager::_parseAlarmFromCSV(), TemperatureController::ensureAlarmsForPoint(), and TemperatureController::updateAlarm().
setHysteresis()
void Alarm::setHysteresis (int16_t hysteresis)
Set the hysteresis value for alarm triggering.
Parameters
[in] hysteresis Hysteresis value to prevent alarm flapping
Definition at line 445 of file Alarm.cpp.
References _hysteresis, _source, getTypeString(), and LoggerManager::info().
Referenced by CSVConfigManager::_parseAlarmFromCSV().
setPriority()
void Alarm::setPriority (AlarmPriority priority)
Set the alarm priority.
Parameters
[in] priority New priority level for this alarm
Definition at line 431 of file Alarm.cpp.
References _getPriorityString(), _priority, _source, getTypeString(), and LoggerManager::info().
Referenced by TemperatureController::ensureAlarmsForPoint(), and TemperatureController::updateAlarm().
setStage()
void Alarm::setStage (AlarmStage stage)
Set the alarm stage.
Parameters
[in] stage New stage for alarm lifecycle
Definition at line 472 of file Alarm.cpp.
References _stage.
updateCondition()
bool Alarm::updateCondition ()
Update alarm condition based on current measurement.
Returns
bool True if alarm condition has changed
Checks current measurement point values against alarm thresholds
Definition at line 477 of file Alarm.cpp.
References _acknowledgedTime, _checkCondition(), _clearedTime, _getPriorityString(), _source, _stage, _timestamp, _type, _updateMessage(), ACKNOWLEDGED, ACTIVE, clear(), CLEARED, LoggerManager::error(), getStageString(), getTypeString(), HIGH_TEMPERATURE, LoggerManager::info(), isAcknowledgedDelayElapsed(), LoggerManager::logAlarmStateChange(), LOW_TEMPERATURE, NEW, resolve(), RESOLVED, SENSOR_DISCONNECTED, SENSOR_ERROR, and LoggerManager::warning().
Field Documentation
_acknowledgedDelay
unsigned long Alarm::_acknowledgedDelay private
Delay after acknowledgment (millis)
Definition at line 342 of file Alarm.h.
Referenced by Alarm(), getAcknowledgedDelay(), getAcknowledgedTimeLeft(), isAcknowledgedDelayElapsed(), and setAcknowledgedDelay().
_acknowledgedTime
unsigned long Alarm::_acknowledgedTime private
When alarm was acknowledged (millis)
Definition at line 335 of file Alarm.h.
Referenced by acknowledge(), Alarm(), getAcknowledgedTime(), getAcknowledgedTimeLeft(), isAcknowledgedDelayElapsed(), reactivate(), and updateCondition().
_clearedTime
unsigned long Alarm::_clearedTime private
When condition was cleared (millis)
Definition at line 336 of file Alarm.h.
Referenced by Alarm(), clear(), getClearedTime(), isDelayElapsed(), reactivate(), and updateCondition().
_configKey
String Alarm::_configKey private
Configuration key "alarm_<point>_<type>".
Definition at line 343 of file Alarm.h.
Referenced by Alarm(), getConfigKey(), and setConfigKey().
_delayTime
unsigned long Alarm::_delayTime private
Delay before auto-resolve (millis)
Definition at line 341 of file Alarm.h.
Referenced by Alarm(), getDelayTime(), isDelayElapsed(), and setDelayTime().
_enabled
bool Alarm::_enabled private
Whether alarm is active in configuration.
Definition at line 344 of file Alarm.h.
Referenced by Alarm(), isEnabled(), and setEnabled().
_hysteresis
int16_t Alarm::_hysteresis private
Hysteresis value to prevent flapping.
Definition at line 338 of file Alarm.h.
Referenced by _checkCondition(), Alarm(), getHysteresis(), and setHysteresis().
_message
String Alarm::_message private
Human-readable alarm description.
Definition at line 347 of file Alarm.h.
Referenced by _updateMessage(), and getMessage().
_priority
AlarmPriority Alarm::_priority private
Priority level for handling.
Definition at line 330 of file Alarm.h.
Referenced by _getPriorityString(), Alarm(), getPriority(), operator<(), and setPriority().
_source
MeasurementPoint* Alarm::_source private
Associated measurement point.
Definition at line 331 of file Alarm.h.
Referenced by _checkCondition(), acknowledge(), Alarm(), clear(), getDisplayText(), getPointAddress(), getSource(), getStatusText(), operator==(), reactivate(), resolve(), setEnabled(), setHysteresis(), setPriority(), updateCondition(), and ~Alarm().
_stage
AlarmStage Alarm::_stage private
Current lifecycle stage.
Definition at line 329 of file Alarm.h.
Referenced by _checkCondition(), acknowledge(), Alarm(), clear(), getAcknowledgedTimeLeft(), getDisplayText(), getStage(), getStageString(), isAcknowledged(), isAcknowledgedDelayElapsed(), isActive(), isDelayElapsed(), isResolved(), reactivate(), resolve(), setStage(), and updateCondition().
_timestamp
unsigned long Alarm::_timestamp private
When alarm was created (millis)
Definition at line 334 of file Alarm.h.
Referenced by Alarm(), getTimestamp(), operator<(), operator==(), and updateCondition().
_type
AlarmType Alarm::_type private
Type of alarm (temperature, sensor error, etc.)
Definition at line 328 of file Alarm.h.
Referenced by _checkCondition(), acknowledge(), Alarm(), getDisplayText(), getType(), getTypeString(), operator==(), and updateCondition().
The documentation for this class was generated from the following files:
include/Alarm.h
src/Alarm.cpp