Temperature Control System: SettingsCSVManager Class Reference
SettingsCSVManager Class Reference
Manages CSV export/import of system settings.
#include <SettingsCSVManager.h>
Public Member Functions
SettingsCSVManager (ConfigAssist &config)
Construct a new Settings CSV Manager object.
String exportSettingsToCSV ()
Export all settings to CSV format.
bool importSettingsFromCSV (const String &csvData)
Import settings from CSV data.
bool validateSettingsCSV (const String &csvData)
Validate CSV data without importing.
String getLastError () const
Get last error message.
Private Member Functions
String _escapeCSVField (const String &field)
Escape special characters for CSV field.
String _unescapeCSVField (const String &field)
Unescape CSV field value.
bool _parseCSVLine (const String &line)
Parse single CSV line.
void _exportAcknowledgedDelays (String &csv)
Export acknowledged delay settings to CSV.
bool _importAcknowledgedDelays (const String &key, const String &value)
Import acknowledged delay settings.
Private Attributes
ConfigAssist & _config
Reference to configuration manager.
String _lastError
Last error message.
Detailed Description
Manages CSV export/import of system settings.
Provides methods to convert system configuration to/from CSV format, with validation and error handling for safe configuration updates.
Definition at line 31 of file SettingsCSVManager.h.
Constructor & Destructor Documentation
SettingsCSVManager()
SettingsCSVManager::SettingsCSVManager (ConfigAssist & config)
Construct a new Settings CSV Manager object.
Parameters
[in] config Reference to ConfigAssist instance
Definition at line 21 of file SettingsCSVManager.cpp.
References _config, and _lastError.
Member Function Documentation
_escapeCSVField()
String SettingsCSVManager::_escapeCSVField (const String & field) private
Escape special characters for CSV field.
Parameters
[in] field Field value to escape
Returns
String Escaped field value
Handles quotes, commas, and newlines
Definition at line 179 of file SettingsCSVManager.cpp.
Referenced by exportSettingsToCSV().
_exportAcknowledgedDelays()
void SettingsCSVManager::_exportAcknowledgedDelays (String & csv) private
Export acknowledged delay settings to CSV.
Parameters
[out] csv String to append delay settings to
Exports alarm acknowledgment delay configurations
_importAcknowledgedDelays()
bool SettingsCSVManager::_importAcknowledgedDelays (const String & key, const String & value) private
Import acknowledged delay settings.
Parameters
[in] key Configuration key
[in] value Configuration value
Returns
true if import successful
false if import failed
_parseCSVLine()
bool SettingsCSVManager::_parseCSVLine (const String & line) private
Parse single CSV line.
Parameters
[in] line CSV line to parse
Returns
true if line parsed successfully
false if parsing failed
Definition at line 109 of file SettingsCSVManager.cpp.
References _config, _lastError, and _unescapeCSVField().
Referenced by importSettingsFromCSV().
_unescapeCSVField()
String SettingsCSVManager::_unescapeCSVField (const String & field) private
Unescape CSV field value.
Parameters
[in] field Escaped field value
Returns
String Unescaped field value
Definition at line 195 of file SettingsCSVManager.cpp.
Referenced by _parseCSVLine().
exportSettingsToCSV()
String SettingsCSVManager::exportSettingsToCSV ()
Export all settings to CSV format.
Returns
String CSV formatted settings
Generates CSV with key-value pairs for all configuration items
Definition at line 25 of file SettingsCSVManager.cpp.
References _config, and _escapeCSVField().
getLastError()
String SettingsCSVManager::getLastError () const inline
Get last error message.
Returns
String Description of last error
Definition at line 70 of file SettingsCSVManager.h.
References _lastError.
importSettingsFromCSV()
bool SettingsCSVManager::importSettingsFromCSV (const String & csvData)
Import settings from CSV data.
Parameters
[in] csvData CSV formatted configuration data
Returns
true if import successful
false if CSV invalid or import failed
Validates and applies settings from CSV input
Definition at line 52 of file SettingsCSVManager.cpp.
References _lastError, _parseCSVLine(), and validateSettingsCSV().
validateSettingsCSV()
bool SettingsCSVManager::validateSettingsCSV (const String & csvData)
Validate CSV data without importing.
Parameters
[in] csvData CSV data to validate
Returns
true if CSV format is valid
false if CSV format is invalid
Checks CSV structure and field validity
Definition at line 87 of file SettingsCSVManager.cpp.
References _lastError.
Referenced by importSettingsFromCSV().
Field Documentation
_config
ConfigAssist& SettingsCSVManager::_config private
Reference to configuration manager.
Definition at line 73 of file SettingsCSVManager.h.
Referenced by _parseCSVLine(), exportSettingsToCSV(), and SettingsCSVManager().
_lastError
String SettingsCSVManager::_lastError private
Last error message.
Definition at line 74 of file SettingsCSVManager.h.
Referenced by _parseCSVLine(), getLastError(), importSettingsFromCSV(), SettingsCSVManager(), and validateSettingsCSV().
The documentation for this class was generated from the following files:
include/SettingsCSVManager.h
src/SettingsCSVManager.cpp