Temperature Control System: CSVConfigManager Class Reference
CSVConfigManager Class Reference
CSV configuration manager for measurement points and alarms.
#include <CSVConfigManager.h>
Public Member Functions
CSVConfigManager (TemperatureController &controller)
Constructor for CSV configuration manager.
String exportPointsWithAlarmsToCSV ()
Export measurement points with alarm configuration to CSV.
bool importPointsWithAlarmsFromCSV (const String &csvData)
Import measurement points and alarms from CSV data.
String exportSensorsToCSV ()
Export only sensor configuration to CSV.
bool importSensorsFromCSV (const String &csvData)
Import sensor configuration from CSV data.
bool saveCSVToFile (const String &filename, const String &csvData)
Save CSV data to file system.
String loadCSVFromFile (const String &filename)
Load CSV data from file system.
bool validatePointsCSV (const String &csvData)
Validate CSV data format and content.
String getLastError () const
Get the last error message.
Private Member Functions
String _escapeCSVField (const String &field)
Escape special characters in CSV field.
String _unescapeCSVField (const String &field)
Unescape CSV field back to original string.
bool _parseAlarmFromCSV (int pointAddress, const String &alarmType, const String &priority, const String &enabled, const String &hysteresis)
Parse alarm configuration from CSV fields.
String _getAlarmTypeString (AlarmType type)
Convert alarm type enum to string.
AlarmType _parseAlarmType (const String &typeStr)
Parse alarm type string to enum.
String _getPriorityString (AlarmPriority priority)
Convert alarm priority enum to string.
AlarmPriority _parsePriority (const String &priorityStr)
Parse priority string to enum.
void _exportPointToCSV (String &csv, MeasurementPoint *point, const String &pointType)
Export single measurement point to CSV format.
bool _parseCSVLine (const String &line)
Parse single CSV line.
String _getAlarmPriorityForPoint (int pointAddress, AlarmType alarmType)
Get alarm priority for specific point and alarm type.
Private Attributes
TemperatureController & _controller
Reference to temperature controller.
String _lastError
Last error message for debugging.
Detailed Description
CSV configuration manager for measurement points and alarms.
Handles import/export of system configuration through CSV files, enabling bulk configuration management and backup/restore operations
Definition at line 28 of file CSVConfigManager.h.
Constructor & Destructor Documentation
CSVConfigManager()
CSVConfigManager::CSVConfigManager (TemperatureController & controller)
Constructor for CSV configuration manager.
Parameters
[in] controller Reference to the temperature controller
Initializes CSV manager with temperature controller integration
Definition at line 4 of file CSVConfigManager.cpp.
References _controller, _lastError, and controller.
Member Function Documentation
_escapeCSVField()
String CSVConfigManager::_escapeCSVField (const String & field) private
Escape special characters in CSV field.
Parameters
[in] field String field to escape
Returns
String Properly escaped CSV field
Handles quotes, commas, and newlines in CSV fields
Definition at line 143 of file CSVConfigManager.cpp.
Referenced by _exportPointToCSV().
_exportPointToCSV()
void CSVConfigManager::_exportPointToCSV (String & csv, MeasurementPoint * point, const String & pointType) private
Export single measurement point to CSV format.
Parameters
[in,out] csv CSV string to append to
[in] point Measurement point to export
[in] pointType Type of measurement point (DS18B20, PT1000, etc.)
Appends measurement point configuration to CSV string
Definition at line 37 of file CSVConfigManager.cpp.
References _controller, _escapeCSVField(), _getAlarmPriorityForPoint(), DS18B20, MeasurementPoint::getAddress(), MeasurementPoint::getBoundSensor(), MeasurementPoint::getCurrentTemp(), Sensor::getDS18B20RomString(), MeasurementPoint::getHighAlarmThreshold(), MeasurementPoint::getLowAlarmThreshold(), MeasurementPoint::getMaxTemp(), MeasurementPoint::getMinTemp(), MeasurementPoint::getName(), Sensor::getType(), HIGH_TEMPERATURE, LOW_TEMPERATURE, PT1000, SENSOR_DISCONNECTED, and SENSOR_ERROR.
Referenced by exportPointsWithAlarmsToCSV().
_getAlarmPriorityForPoint()
String CSVConfigManager::_getAlarmPriorityForPoint (int pointAddress, AlarmType alarmType) private
Get alarm priority for specific point and alarm type.
Parameters
[in] pointAddress Measurement point address
[in] alarmType Type of alarm
Returns
String Priority level as string
Retrieves current alarm priority configuration
Definition at line 369 of file CSVConfigManager.cpp.
References _controller, _getPriorityString(), Alarm::getPointAddress(), Alarm::getPriority(), and Alarm::getType().
Referenced by _exportPointToCSV().
_getAlarmTypeString()
String CSVConfigManager::_getAlarmTypeString (AlarmType type) private
Convert alarm type enum to string.
Parameters
[in] type AlarmType enum value
Returns
String Human-readable alarm type string
Definition at line 168 of file CSVConfigManager.cpp.
References HIGH_TEMPERATURE, LOW_TEMPERATURE, SENSOR_DISCONNECTED, and SENSOR_ERROR.
_getPriorityString()
String CSVConfigManager::_getPriorityString (AlarmPriority priority) private
Convert alarm priority enum to string.
Parameters
[in] priority AlarmPriority enum value
Returns
String Human-readable priority string
Definition at line 186 of file CSVConfigManager.cpp.
References PRIORITY_CRITICAL, PRIORITY_HIGH, PRIORITY_LOW, and PRIORITY_MEDIUM.
Referenced by _getAlarmPriorityForPoint().
_parseAlarmFromCSV()
bool CSVConfigManager::_parseAlarmFromCSV (int pointAddress, const String & alarmType, const String & priority, const String & enabled, const String & hysteresis) private
Parse alarm configuration from CSV fields.
Parameters
[in] pointAddress Measurement point address
[in] alarmType Alarm type as string
[in] priority Alarm priority as string
[in] enabled Alarm enabled state as string
[in] hysteresis Hysteresis value as string
Returns
bool True if alarm parsing successful
Converts CSV string fields to alarm configuration
Definition at line 120 of file CSVConfigManager.cpp.
References _controller, _parseAlarmType(), _parsePriority(), Alarm::setEnabled(), and Alarm::setHysteresis().
_parseAlarmType()
AlarmType CSVConfigManager::_parseAlarmType (const String & typeStr) private
Parse alarm type string to enum.
Parameters
[in] typeStr Alarm type as string
Returns
AlarmType Corresponding enum value
Definition at line 178 of file CSVConfigManager.cpp.
References HIGH_TEMPERATURE, LOW_TEMPERATURE, SENSOR_DISCONNECTED, and SENSOR_ERROR.
Referenced by _parseAlarmFromCSV().
_parseCSVLine()
bool CSVConfigManager::_parseCSVLine (const String & line) private
Parse single CSV line.
Parameters
[in] line CSV line to parse
Returns
bool True if line parsing successful
Parses individual CSV line and applies configuration
Definition at line 289 of file CSVConfigManager.cpp.
References _controller, _lastError, _parsePriority(), HIGH_TEMPERATURE, LOW_TEMPERATURE, SENSOR_DISCONNECTED, SENSOR_ERROR, MeasurementPoint::setHighAlarmThreshold(), MeasurementPoint::setLowAlarmThreshold(), and MeasurementPoint::setName().
Referenced by importPointsWithAlarmsFromCSV().
_parsePriority()
AlarmPriority CSVConfigManager::_parsePriority (const String & priorityStr) private
Parse priority string to enum.
Parameters
[in] priorityStr Priority as string
Returns
AlarmPriority Corresponding enum value
Definition at line 196 of file CSVConfigManager.cpp.
References PRIORITY_CRITICAL, PRIORITY_HIGH, PRIORITY_LOW, and PRIORITY_MEDIUM.
Referenced by _parseAlarmFromCSV(), and _parseCSVLine().
_unescapeCSVField()
String CSVConfigManager::_unescapeCSVField (const String & field) private
Unescape CSV field back to original string.
Parameters
[in] field Escaped CSV field
Returns
String Original unescaped string
Reverses CSV field escaping
Definition at line 159 of file CSVConfigManager.cpp.
exportPointsWithAlarmsToCSV()
String CSVConfigManager::exportPointsWithAlarmsToCSV ()
Export measurement points with alarm configuration to CSV.
Returns
String CSV formatted string containing all measurement points and alarms
Generates comprehensive CSV export including point names, sensor configs, and alarm settings
Definition at line 8 of file CSVConfigManager.cpp.
References _controller, and _exportPointToCSV().
exportSensorsToCSV()
String CSVConfigManager::exportSensorsToCSV ()
Export only sensor configuration to CSV.
Returns
String CSV formatted string containing sensor configuration
Exports sensor-specific settings without alarm configuration
Definition at line 278 of file CSVConfigManager.cpp.
getLastError()
String CSVConfigManager::getLastError () const inline
Get the last error message.
Returns
String Description of the last error that occurred
Provides detailed error information for debugging import/export issues
Definition at line 101 of file CSVConfigManager.h.
References _lastError.
importPointsWithAlarmsFromCSV()
bool CSVConfigManager::importPointsWithAlarmsFromCSV (const String & csvData)
Import measurement points and alarms from CSV data.
Parameters
[in] csvData CSV formatted string containing configuration
Returns
bool True if import successful, false if validation or parsing failed
Parses CSV data and applies configuration to measurement points and alarms
Definition at line 73 of file CSVConfigManager.cpp.
References _controller, _lastError, _parseCSVLine(), and validatePointsCSV().
importSensorsFromCSV()
bool CSVConfigManager::importSensorsFromCSV (const String & csvData)
Import sensor configuration from CSV data.
Parameters
[in] csvData CSV formatted string containing sensor configuration
Returns
bool True if import successful
Parses and applies sensor configuration from CSV data
Definition at line 283 of file CSVConfigManager.cpp.
loadCSVFromFile()
String CSVConfigManager::loadCSVFromFile (const String & filename)
Load CSV data from file system.
Parameters
[in] filename Name of file to load from LittleFS
Returns
String CSV data from file, empty string if load failed
Reads CSV data from LittleFS with error handling
Definition at line 259 of file CSVConfigManager.cpp.
References _lastError.
saveCSVToFile()
bool CSVConfigManager::saveCSVToFile (const String & filename, const String & csvData)
Save CSV data to file system.
Parameters
[in] filename Name of file to save (will be stored in LittleFS)
[in] csvData CSV data to write to file
Returns
bool True if file save successful
Writes CSV data to LittleFS file system with error handling
Definition at line 236 of file CSVConfigManager.cpp.
References _lastError.
validatePointsCSV()
bool CSVConfigManager::validatePointsCSV (const String & csvData)
Validate CSV data format and content.
Parameters
[in] csvData CSV data to validate
Returns
bool True if CSV data is valid and can be imported
Performs comprehensive validation of CSV structure, data types, and ranges
Definition at line 204 of file CSVConfigManager.cpp.
References _lastError.
Referenced by importPointsWithAlarmsFromCSV().
Field Documentation
_controller
TemperatureController& CSVConfigManager::_controller private
Reference to temperature controller.
Definition at line 104 of file CSVConfigManager.h.
Referenced by _exportPointToCSV(), _getAlarmPriorityForPoint(), _parseAlarmFromCSV(), _parseCSVLine(), CSVConfigManager(), exportPointsWithAlarmsToCSV(), and importPointsWithAlarmsFromCSV().
_lastError
String CSVConfigManager::_lastError private
Last error message for debugging.
Definition at line 105 of file CSVConfigManager.h.
Referenced by _parseCSVLine(), CSVConfigManager(), getLastError(), importPointsWithAlarmsFromCSV(), loadCSVFromFile(), saveCSVToFile(), and validatePointsCSV().
The documentation for this class was generated from the following files:
include/CSVConfigManager.h
src/CSVConfigManager.cpp