Temperature Control System: LoggerManager Class Reference
LoggerManager Class Reference
Forward declaration for measurement point class.
#include <LoggerManager.h>
Public Member Functions
LoggerManager (TemperatureController &controller, TimeManager &timeManager, fs::FS &filesystem)
Constructor for LoggerManager.
~LoggerManager ()
Destructor for LoggerManager.
bool init ()
Initialize the logging system.
bool begin ()
Begin logging operations.
void setLogFrequency (unsigned long frequencyMs)
Set logging frequency.
unsigned long getLogFrequency () const
Get current logging frequency.
void setEnabled (bool enabled)
Enable or disable logging.
bool isEnabled () const
Check if logging is enabled.
void setDailyFiles (bool enabled)
Enable or disable daily file creation.
bool isDailyFiles () const
Check if daily files are enabled.
void setLogDirectory (const String &directory)
Set base log directory.
void update ()
bool logDataNow ()
bool createNewLogFile ()
String getCurrentLogFile () const
bool closeCurrentFile ()
bool deleteLogFile (const String &filename)
unsigned long getLastLogTime () const
size_t getLogFileSize () const
String getLastError () const
void forceNewFile ()
int getCurrentSequenceNumber () const
void resetSequenceNumber ()
void setEventLoggingEnabled (bool enabled)
bool isEventLoggingEnabled () const
void setEventLogDirectory (const String &directory)
String getEventLogDirectory () const
bool logEvent (const String &source, const String &description, const String &priority="INFO")
bool logInfo (const String &source, const String &description)
bool logWarning (const String &source, const String &description)
bool logError (const String &source, const String &description)
bool logCritical (const String &source, const String &description)
String getCurrentEventLogFile () const
std::vector< String > getEventLogFiles ()
bool deleteEventLogFile (const String &filename)
void setAlarmStateLoggingEnabled (bool enabled)
bool isAlarmStateLoggingEnabled () const
void setAlarmStateLogDirectory (const String &directory)
String getAlarmStateLogDirectory () const
bool logAlarmState (int pointNumber, const String &pointName, const String &alarmType, const String &alarmPriority, const String &previousState, const String &newState, int16_t currentTemp, int16_t threshold)
String getCurrentAlarmStateLogFile () const
bool deleteAlarmStateLogFile (const String &filename)
Static Public Member Functions
static LoggerManager * getInstance ()
Get singleton instance.
static bool info (const String &source, const String &description)
Log informational message (static convenience method)
static bool warning (const String &source, const String &description)
Log warning message (static convenience method)
static bool error (const String &source, const String &description)
Log error message (static convenience method)
static bool critical (const String &source, const String &description)
Log critical message (static convenience method)
static String getLogDirectory ()
Get current log directory.
static std::vector< String > getLogFiles ()
static bool logAlarmStateChange (int pointNumber, const String &pointName, const String &alarmType, const String &alarmPriority, const String &previousState, const String &newState, int16_t currentTemp, int16_t threshold)
static String getEventLogsJson (const String &startDate, const String &endDate)
static String getEventLogsCsv (const String &startDate, const String &endDate)
static String getEventLogStatsJson (const String &startDate, const String &endDate)
static String getAlarmHistoryJson (const String &startDate, const String &endDate)
static String getAlarmHistoryCsv (const String &startDate, const String &endDate)
static std::vector< String > getEventLogFilesStatic ()
static std::vector< String > getAlarmStateLogFiles ()
static bool getFileInfo (const String &filename, const String &type, size_t &fileSize, String &date)
static File openLogFile (const String &filename, const String &type)
static String getLogDirectoryPath (const String &type)
Private Member Functions
String _generateLogFileName ()
String _generateCSVHeader ()
bool _writeHeader ()
bool _writeDataRow ()
String _escapeCSVField (const String &field)
bool _ensureDirectoryExists ()
String _getCurrentDateString ()
String _getCurrentTimeString ()
bool _recoverFromExistingFiles ()
String _findLatestFileForDate (const String &dateStr)
int _extractSequenceNumber (const String &filename)
String _readHeaderFromFile (const String &filename)
std::vector< String > _getFilesForDate (const String &dateStr)
int _findHighestSequenceForDate (const String &dateStr)
bool _hasHeaderChanged ()
String _generateLogFileNameWithSequence ()
void _incrementSequenceNumber ()
String _generateEventLogFileName ()
bool _writeEventHeader ()
bool _writeEventRow (const String &timestamp, const String &source, const String &description, const String &priority)
bool _ensureEventLogExists ()
String _generateAlarmStateLogFileName ()
bool _writeAlarmStateHeader ()
bool _ensureAlarmStateLogExists ()
bool _writeAlarmStateRow (const String &timestamp, int pointNumber, const String &pointName, const String &alarmType, const String &alarmPriority, const String &previousState, const String &newState, int16_t currentTemp, int16_t threshold)
bool _isSDCardAvailable ()
Static Private Member Functions
static std::vector< String > _getEventLogFilesInRange (const String &startDate, const String &endDate)
static bool _parseEventLogEntry (const String &line, DynamicJsonDocument &entry)
static std::vector< String > _getAlarmLogFilesInRange (const String &startDate, const String &endDate)
static bool _parseAlarmStateLogEntry (const String &line, DynamicJsonDocument &entry)
static String _normalizeDate (const String &dateStr)
Private Attributes
TemperatureController * _controller
Reference to temperature controller.
TimeManager * _timeManager
Reference to time manager.
fs::FS * _fs
File system interface (SD or LittleFS)
unsigned long _logFrequency
Logging frequency in milliseconds.
unsigned long _lastLogTime
Last time data was logged.
String _currentLogFile
Current log file name.
bool _headerWritten
Flag to track if header is written.
bool _enabled
Whether logging is enabled.
String _logDirectory
Base directory for log files.
bool _dailyFiles
Create new file each day.
String _lastLogDate
Track date for daily file creation.
String _lastGeneratedHeader
bool _headerChanged
int _fileSequenceNumber
bool _eventLoggingEnabled
String _eventLogDirectory
String _currentEventLogFile
String _lastEventLogDate
bool _alarmStateLoggingEnabled
String _alarmStateLogDirectory
String _currentAlarmStateLogFile
String _lastAlarmStateLogDate
String _lastError
Static Private Attributes
static LoggerManager * _instance = nullptr
Singleton instance pointer.
Detailed Description
Forward declaration for measurement point class.
Singleton logger manager for comprehensive system logging
Provides measurement data logging, event logging, and alarm state logging with automatic file management, CSV formatting, and date-based organization
Definition at line 37 of file LoggerManager.h.
Constructor & Destructor Documentation
LoggerManager()
LoggerManager::LoggerManager (TemperatureController & controller, TimeManager & timeManager, fs::FS & filesystem)
Constructor for LoggerManager.
Parameters
[in] controller Reference to temperature controller
[in] timeManager Reference to time manager for timestamps
[in] filesystem Reference to file system (SD or LittleFS)
Initializes logging system with required dependencies
Definition at line 31 of file LoggerManager.cpp.
References _alarmStateLogDirectory, _alarmStateLoggingEnabled, _controller, _currentAlarmStateLogFile, _currentEventLogFile, _dailyFiles, _enabled, _eventLogDirectory, _eventLoggingEnabled, _fileSequenceNumber, _fs, _headerChanged, _headerWritten, _instance, _lastAlarmStateLogDate, _lastError, _lastEventLogDate, _lastGeneratedHeader, _lastLogTime, _logDirectory, _logFrequency, _timeManager, controller, and timeManager.
Referenced by getInstance().
~LoggerManager()
LoggerManager::~LoggerManager ()
Destructor for LoggerManager.
Closes any open files and cleans up resources
Definition at line 42 of file LoggerManager.cpp.
References closeCurrentFile().
Member Function Documentation
_ensureAlarmStateLogExists()
bool LoggerManager::_ensureAlarmStateLogExists () private
Definition at line 949 of file LoggerManager.cpp.
References _currentAlarmStateLogFile, _enabled, _fs, and _writeAlarmStateHeader().
Referenced by begin(), and logAlarmState().
_ensureDirectoryExists()
bool LoggerManager::_ensureDirectoryExists () private
Definition at line 376 of file LoggerManager.cpp.
References _enabled, _fs, and _logDirectory.
Referenced by begin(), and init().
_ensureEventLogExists()
bool LoggerManager::_ensureEventLogExists () private
Definition at line 807 of file LoggerManager.cpp.
References _currentEventLogFile, _enabled, _fs, and _writeEventHeader().
Referenced by init(), and logEvent().
_escapeCSVField()
String LoggerManager::_escapeCSVField (const String & field) private
Definition at line 360 of file LoggerManager.cpp.
Referenced by _generateCSVHeader(), _writeAlarmStateRow(), and _writeEventRow().
_extractSequenceNumber()
int LoggerManager::_extractSequenceNumber (const String & filename) private
Definition at line 622 of file LoggerManager.cpp.
Referenced by _findHighestSequenceForDate(), and _findLatestFileForDate().
_findHighestSequenceForDate()
int LoggerManager::_findHighestSequenceForDate (const String & dateStr) private
Definition at line 592 of file LoggerManager.cpp.
References _extractSequenceNumber(), and _getFilesForDate().
Referenced by _recoverFromExistingFiles().
_findLatestFileForDate()
String LoggerManager::_findLatestFileForDate (const String & dateStr) private
Definition at line 606 of file LoggerManager.cpp.
References _extractSequenceNumber(), and _getFilesForDate().
Referenced by _recoverFromExistingFiles().
_generateAlarmStateLogFileName()
String LoggerManager::_generateAlarmStateLogFileName () private
Definition at line 931 of file LoggerManager.cpp.
References _alarmStateLogDirectory, and _getCurrentDateString().
Referenced by begin(), and logAlarmState().
_generateCSVHeader()
String LoggerManager::_generateCSVHeader () private
Definition at line 282 of file LoggerManager.cpp.
References _controller, _escapeCSVField(), and MeasurementPoint::getName().
Referenced by _hasHeaderChanged(), _recoverFromExistingFiles(), _writeHeader(), begin(), and createNewLogFile().
_generateEventLogFileName()
String LoggerManager::_generateEventLogFileName () private
Definition at line 789 of file LoggerManager.cpp.
References _eventLogDirectory, and _getCurrentDateString().
Referenced by init(), logEvent(), and update().
_generateLogFileName()
String LoggerManager::_generateLogFileName () private
Definition at line 255 of file LoggerManager.cpp.
References _generateLogFileNameWithSequence(), and _getCurrentDateString().
_generateLogFileNameWithSequence()
String LoggerManager::_generateLogFileNameWithSequence () private
Definition at line 260 of file LoggerManager.cpp.
References _fileSequenceNumber, _getCurrentDateString(), and _logDirectory.
Referenced by _generateLogFileName(), begin(), and createNewLogFile().
_getAlarmLogFilesInRange()
std::vector< String > LoggerManager::_getAlarmLogFilesInRange (const String & startDate, const String & endDate) static private
Definition at line 1198 of file LoggerManager.cpp.
References _instance, and _normalizeDate().
Referenced by getAlarmHistoryCsv(), and getAlarmHistoryJson().
_getCurrentDateString()
String LoggerManager::_getCurrentDateString () private
Definition at line 402 of file LoggerManager.cpp.
References _timeManager.
Referenced by _generateAlarmStateLogFileName(), _generateEventLogFileName(), _generateLogFileName(), _generateLogFileNameWithSequence(), _recoverFromExistingFiles(), _writeDataRow(), begin(), init(), logAlarmState(), logEvent(), and update().
_getCurrentTimeString()
String LoggerManager::_getCurrentTimeString () private
Definition at line 412 of file LoggerManager.cpp.
References _timeManager.
Referenced by _writeDataRow(), logAlarmState(), and logEvent().
_getEventLogFilesInRange()
std::vector< String > LoggerManager::_getEventLogFilesInRange (const String & startDate, const String & endDate) static private
Definition at line 1646 of file LoggerManager.cpp.
References _instance, and _normalizeDate().
Referenced by getEventLogsCsv(), getEventLogsJson(), and getEventLogStatsJson().
_getFilesForDate()
std::vector< String > LoggerManager::_getFilesForDate (const String & dateStr) private
Definition at line 555 of file LoggerManager.cpp.
References _fs, and _logDirectory.
Referenced by _findHighestSequenceForDate(), _findLatestFileForDate(), and _recoverFromExistingFiles().
_hasHeaderChanged()
bool LoggerManager::_hasHeaderChanged () private
Definition at line 447 of file LoggerManager.cpp.
References _generateCSVHeader(), and _lastGeneratedHeader.
Referenced by update().
_incrementSequenceNumber()
void LoggerManager::_incrementSequenceNumber () private
Definition at line 469 of file LoggerManager.cpp.
References _fileSequenceNumber.
Referenced by forceNewFile(), and update().
_isSDCardAvailable()
bool LoggerManager::_isSDCardAvailable () private
Definition at line 1062 of file LoggerManager.cpp.
References _fs.
_normalizeDate()
String LoggerManager::_normalizeDate (const String & dateStr) static private
Definition at line 1299 of file LoggerManager.cpp.
Referenced by _getAlarmLogFilesInRange(), and _getEventLogFilesInRange().
_parseAlarmStateLogEntry()
bool LoggerManager::_parseAlarmStateLogEntry (const String & line, DynamicJsonDocument & entry) static private
Definition at line 1254 of file LoggerManager.cpp.
Referenced by getAlarmHistoryJson().
_parseEventLogEntry()
bool LoggerManager::_parseEventLogEntry (const String & line, DynamicJsonDocument & entry) static private
Definition at line 1701 of file LoggerManager.cpp.
Referenced by getEventLogsJson().
_readHeaderFromFile()
String LoggerManager::_readHeaderFromFile (const String & filename) private
Definition at line 635 of file LoggerManager.cpp.
References _fs.
Referenced by _recoverFromExistingFiles().
_recoverFromExistingFiles()
bool LoggerManager::_recoverFromExistingFiles () private
Definition at line 494 of file LoggerManager.cpp.
References _currentLogFile, _enabled, _fileSequenceNumber, _findHighestSequenceForDate(), _findLatestFileForDate(), _generateCSVHeader(), _getCurrentDateString(), _getFilesForDate(), _headerWritten, and _readHeaderFromFile().
Referenced by begin(), and update().
_writeAlarmStateHeader()
bool LoggerManager::_writeAlarmStateHeader () private
Definition at line 962 of file LoggerManager.cpp.
References _currentAlarmStateLogFile, _enabled, _fs, and _lastError.
Referenced by _ensureAlarmStateLogExists().
_writeAlarmStateRow()
bool LoggerManager::_writeAlarmStateRow (const String & timestamp, int pointNumber, const String & pointName, const String & alarmType, const String & alarmPriority, const String & previousState, const String & newState, int16_t currentTemp, int16_t threshold) private
Definition at line 983 of file LoggerManager.cpp.
References _currentAlarmStateLogFile, _enabled, _escapeCSVField(), _fs, and _lastError.
Referenced by logAlarmState().
_writeDataRow()
bool LoggerManager::_writeDataRow () private
Definition at line 324 of file LoggerManager.cpp.
References _controller, _currentLogFile, _enabled, _fs, _getCurrentDateString(), _getCurrentTimeString(), _lastError, MeasurementPoint::getBoundSensor(), and MeasurementPoint::getCurrentTemp().
Referenced by logDataNow().
_writeEventHeader()
bool LoggerManager::_writeEventHeader () private
Definition at line 820 of file LoggerManager.cpp.
References _currentEventLogFile, _enabled, _fs, and _lastError.
Referenced by _ensureEventLogExists().
_writeEventRow()
bool LoggerManager::_writeEventRow (const String & timestamp, const String & source, const String & description, const String & priority) private
Definition at line 841 of file LoggerManager.cpp.
References _currentEventLogFile, _enabled, _escapeCSVField(), _fs, and _lastError.
Referenced by logEvent().
_writeHeader()
bool LoggerManager::_writeHeader () private
Definition at line 303 of file LoggerManager.cpp.
References _currentLogFile, _enabled, _fs, _generateCSVHeader(), and _lastError.
Referenced by logDataNow().
begin()
bool LoggerManager::begin ()
Begin logging operations.
Returns
bool True if startup successful
Starts the logging system and opens initial log files
Definition at line 46 of file LoggerManager.cpp.
References _alarmStateLoggingEnabled, _currentAlarmStateLogFile, _currentLogFile, _enabled, _ensureAlarmStateLogExists(), _ensureDirectoryExists(), _fileSequenceNumber, _generateAlarmStateLogFileName(), _generateCSVHeader(), _generateLogFileNameWithSequence(), _getCurrentDateString(), _headerWritten, _lastAlarmStateLogDate, _lastError, _lastGeneratedHeader, _lastLogDate, _logFrequency, _recoverFromExistingFiles(), and logInfo().
closeCurrentFile()
bool LoggerManager::closeCurrentFile ()
Definition at line 240 of file LoggerManager.cpp.
Referenced by createNewLogFile(), and ~LoggerManager().
createNewLogFile()
bool LoggerManager::createNewLogFile ()
Definition at line 664 of file LoggerManager.cpp.
References _currentLogFile, _enabled, _fileSequenceNumber, _generateCSVHeader(), _generateLogFileNameWithSequence(), _headerWritten, _lastGeneratedHeader, and closeCurrentFile().
Referenced by forceNewFile(), and update().
critical()
bool LoggerManager::critical (const String & source, const String & description) inline static
Log critical message (static convenience method)
Parameters
[in] source Source component or module
[in] description Description of the critical event
Returns
bool True if logging successful
Definition at line 175 of file LoggerManager.h.
References _instance.
deleteAlarmStateLogFile()
bool LoggerManager::deleteAlarmStateLogFile (const String & filename)
Definition at line 1053 of file LoggerManager.cpp.
References _alarmStateLogDirectory, and _fs.
deleteEventLogFile()
bool LoggerManager::deleteEventLogFile (const String & filename)
Definition at line 780 of file LoggerManager.cpp.
References _enabled, _eventLogDirectory, and _fs.
deleteLogFile()
bool LoggerManager::deleteLogFile (const String & filename)
Definition at line 430 of file LoggerManager.cpp.
References _enabled, _fs, and _logDirectory.
error()
bool LoggerManager::error (const String & source, const String & description) inline static
Log error message (static convenience method)
Parameters
[in] source Source component or module
[in] description Description of the error
Returns
bool True if logging successful
Definition at line 165 of file LoggerManager.h.
References _instance.
Referenced by ConfigManager::csvImportExportAPI(), TemperatureController::forceRelayState(), TemperatureController::getRelayActualState(), TemperatureController::getRelayControlMode(), TempModbusServer::readHoldingRegistersWorker(), TemperatureController::setRelayControlMode(), TemperatureController::unbindSensorFromPoint(), TemperatureController::updateAllSensors(), Alarm::updateCondition(), TempModbusServer::writeHoldingRegisterWorker(), and TempModbusServer::writeMultipleRegistersWorker().
forceNewFile()
void LoggerManager::forceNewFile ()
Definition at line 478 of file LoggerManager.cpp.
References _enabled, _incrementSequenceNumber(), and createNewLogFile().
getAlarmHistoryCsv()
String LoggerManager::getAlarmHistoryCsv (const String & startDate, const String & endDate) static
Definition at line 1153 of file LoggerManager.cpp.
References _getAlarmLogFilesInRange(), and _instance.
Referenced by ConfigManager::logsAPI().
getAlarmHistoryJson()
String LoggerManager::getAlarmHistoryJson (const String & startDate, const String & endDate) static
Definition at line 1073 of file LoggerManager.cpp.
References _getAlarmLogFilesInRange(), _instance, and _parseAlarmStateLogEntry().
Referenced by ConfigManager::logsAPI().
getAlarmStateLogDirectory()
String LoggerManager::getAlarmStateLogDirectory () const
Definition at line 888 of file LoggerManager.cpp.
References _alarmStateLogDirectory.
getAlarmStateLogFiles()
std::vector< String > LoggerManager::getAlarmStateLogFiles () static
Definition at line 1888 of file LoggerManager.cpp.
References _instance.
Referenced by ConfigManager::downloadAPI(), ConfigManager::getAlarmEventsForPoint(), and ConfigManager::logsAPI().
getCurrentAlarmStateLogFile()
String LoggerManager::getCurrentAlarmStateLogFile () const
Definition at line 1022 of file LoggerManager.cpp.
References _currentAlarmStateLogFile.
getCurrentEventLogFile()
String LoggerManager::getCurrentEventLogFile () const
Definition at line 749 of file LoggerManager.cpp.
References _currentEventLogFile.
getCurrentLogFile()
String LoggerManager::getCurrentLogFile () const
Definition at line 236 of file LoggerManager.cpp.
References _currentLogFile.
getCurrentSequenceNumber()
int LoggerManager::getCurrentSequenceNumber () const
Definition at line 485 of file LoggerManager.cpp.
References _fileSequenceNumber.
getEventLogDirectory()
String LoggerManager::getEventLogDirectory () const
Definition at line 699 of file LoggerManager.cpp.
References _eventLogDirectory.
getEventLogFiles()
std::vector< String > LoggerManager::getEventLogFiles ()
Definition at line 753 of file LoggerManager.cpp.
References _eventLogDirectory, and _fs.
getEventLogFilesStatic()
std::vector< String > LoggerManager::getEventLogFilesStatic () static
Definition at line 1827 of file LoggerManager.cpp.
References _instance.
Referenced by ConfigManager::downloadAPI(), and ConfigManager::logsAPI().
getEventLogsCsv()
String LoggerManager::getEventLogsCsv (const String & startDate, const String & endDate) static
Definition at line 1600 of file LoggerManager.cpp.
References _getEventLogFilesInRange(), and _instance.
Referenced by ConfigManager::logsAPI().
getEventLogsJson()
String LoggerManager::getEventLogsJson (const String & startDate, const String & endDate) static
Definition at line 1534 of file LoggerManager.cpp.
References _getEventLogFilesInRange(), _instance, and _parseEventLogEntry().
Referenced by ConfigManager::logsAPI().
getEventLogStatsJson()
String LoggerManager::getEventLogStatsJson (const String & startDate, const String & endDate) static
Definition at line 1741 of file LoggerManager.cpp.
References _getEventLogFilesInRange(), and _instance.
Referenced by ConfigManager::logsAPI().
getFileInfo()
bool LoggerManager::getFileInfo (const String & filename, const String & type, size_t & fileSize, String & date) static
Definition at line 1915 of file LoggerManager.cpp.
References _instance, and getLogDirectoryPath().
Referenced by ConfigManager::downloadAPI().
getInstance()
LoggerManager * LoggerManager::getInstance () inline static
Get singleton instance.
Returns
LoggerManager* Pointer to singleton instance
Provides access to the global logger instance
Definition at line 136 of file LoggerManager.h.
References _instance, and LoggerManager().
getLastError()
String LoggerManager::getLastError () const
Definition at line 249 of file LoggerManager.cpp.
References _lastError.
getLastLogTime()
unsigned long LoggerManager::getLastLogTime () const
Definition at line 245 of file LoggerManager.cpp.
References _lastLogTime.
getLogDirectory()
String LoggerManager::getLogDirectory () static
Get current log directory.
Returns
String Current log directory path
Definition at line 166 of file LoggerManager.cpp.
References _instance.
getLogDirectoryPath()
String LoggerManager::getLogDirectoryPath (const String & type) static
Definition at line 1964 of file LoggerManager.cpp.
References _instance.
Referenced by ConfigManager::getAlarmEventsForPoint(), getFileInfo(), and openLogFile().
getLogFiles()
std::vector< String > LoggerManager::getLogFiles () static
Definition at line 1861 of file LoggerManager.cpp.
References _instance.
Referenced by ConfigManager::downloadAPI().
getLogFileSize()
size_t LoggerManager::getLogFileSize () const
Definition at line 436 of file LoggerManager.cpp.
References _currentLogFile, _enabled, and _fs.
getLogFrequency()
unsigned long LoggerManager::getLogFrequency () const
Get current logging frequency.
Returns
unsigned long Frequency in milliseconds
Definition at line 138 of file LoggerManager.cpp.
References _logFrequency.
info()
bool LoggerManager::info (const String & source, const String & description) inline static
Log informational message (static convenience method)
Parameters
[in] source Source component or module
[in] description Description of the event
Returns
bool True if logging successful
Definition at line 145 of file LoggerManager.h.
References _instance.
Referenced by Alarm::acknowledge(), TemperatureController::addAlarm(), Alarm::Alarm(), ConfigManager::begin(), TemperatureController::begin(), TempModbusServer::begin(), TemperatureController::bindSensorToPointByBusNumber(), TemperatureController::bindSensorToPointByChipSelect(), TemperatureController::bindSensorToPointByRom(), Alarm::clear(), ConfigManager::csvImportExportAPI(), TemperatureController::discoverDS18B20Sensors(), TemperatureController::discoverPTSensors(), TemperatureController::forceRelayState(), TemperatureController::handleAlarmOutputs(), ConfigManager::loadPointsConfig(), TempModbusServer::processCommands(), TempModbusServer::readHoldingRegistersWorker(), TemperatureController::removeAlarm(), TemperatureController::resetMinMaxValues(), Alarm::resolve(), ConfigManager::savePointsConfig(), TemperatureController::setDeviceId(), Alarm::setEnabled(), MeasurementPoint::setHighAlarmThreshold(), Alarm::setHysteresis(), MeasurementPoint::setLowAlarmThreshold(), TemperatureController::setMeasurementPeriod(), MeasurementPoint::setName(), Alarm::setPriority(), TemperatureController::setRelayControlMode(), IndicatorInterface::startBlinking(), IndicatorInterface::stopBlinking(), TempModbusServer::TempModbusServer(), TemperatureController::unbindSensorFromPoint(), Alarm::updateCondition(), TempModbusServer::writeHoldingRegisterWorker(), TempModbusServer::writeMultipleRegistersWorker(), and Alarm::~Alarm().
init()
bool LoggerManager::init ()
Initialize the logging system.
Returns
bool True if initialization successful
Sets up file system, directories, and initial configuration
Definition at line 94 of file LoggerManager.cpp.
References _currentEventLogFile, _currentLogFile, _enabled, _ensureDirectoryExists(), _ensureEventLogExists(), _eventLoggingEnabled, _generateEventLogFileName(), _getCurrentDateString(), _lastError, _lastEventLogDate, and logInfo().
isAlarmStateLoggingEnabled()
bool LoggerManager::isAlarmStateLoggingEnabled () const
Definition at line 877 of file LoggerManager.cpp.
References _alarmStateLoggingEnabled.
isDailyFiles()
bool LoggerManager::isDailyFiles () const
Check if daily files are enabled.
Returns
bool True if daily files are enabled
Definition at line 155 of file LoggerManager.cpp.
References _dailyFiles.
isEnabled()
bool LoggerManager::isEnabled () const
Check if logging is enabled.
Returns
bool True if logging is enabled
Definition at line 147 of file LoggerManager.cpp.
References _enabled.
isEventLoggingEnabled()
bool LoggerManager::isEventLoggingEnabled () const
Definition at line 688 of file LoggerManager.cpp.
References _eventLoggingEnabled.
logAlarmState()
bool LoggerManager::logAlarmState (int pointNumber, const String & pointName, const String & alarmType, const String & alarmPriority, const String & previousState, const String & newState, int16_t currentTemp, int16_t threshold)
Definition at line 903 of file LoggerManager.cpp.
References _alarmStateLoggingEnabled, _currentAlarmStateLogFile, _enabled, _ensureAlarmStateLogExists(), _generateAlarmStateLogFileName(), _getCurrentDateString(), _getCurrentTimeString(), _lastAlarmStateLogDate, and _writeAlarmStateRow().
logAlarmStateChange()
bool LoggerManager::logAlarmStateChange (int pointNumber, const String & pointName, const String & alarmType, const String & alarmPriority, const String & previousState, const String & newState, int16_t currentTemp, int16_t threshold) static
Definition at line 893 of file LoggerManager.cpp.
References _instance.
Referenced by Alarm::acknowledge(), and Alarm::updateCondition().
logCritical()
bool LoggerManager::logCritical (const String & source, const String & description)
Definition at line 743 of file LoggerManager.cpp.
References _enabled, and logEvent().
logDataNow()
bool LoggerManager::logDataNow ()
Definition at line 213 of file LoggerManager.cpp.
References _enabled, _headerWritten, _lastLogTime, _writeDataRow(), and _writeHeader().
Referenced by update().
logError()
bool LoggerManager::logError (const String & source, const String & description)
Definition at line 738 of file LoggerManager.cpp.
References _enabled, and logEvent().
logEvent()
bool LoggerManager::logEvent (const String & source, const String & description, const String & priority = "INFO")
Definition at line 704 of file LoggerManager.cpp.
References _currentEventLogFile, _enabled, _ensureEventLogExists(), _eventLoggingEnabled, _generateEventLogFileName(), _getCurrentDateString(), _getCurrentTimeString(), _lastEventLogDate, and _writeEventRow().
Referenced by logCritical(), logError(), logInfo(), and logWarning().
logInfo()
bool LoggerManager::logInfo (const String & source, const String & description)
Definition at line 728 of file LoggerManager.cpp.
References _enabled, and logEvent().
Referenced by begin(), init(), and update().
logWarning()
bool LoggerManager::logWarning (const String & source, const String & description)
Definition at line 733 of file LoggerManager.cpp.
References _enabled, and logEvent().
Referenced by update().
openLogFile()
File LoggerManager::openLogFile (const String & filename, const String & type) static
Definition at line 1950 of file LoggerManager.cpp.
References _instance, and getLogDirectoryPath().
Referenced by ConfigManager::downloadAPI(), and ConfigManager::getAlarmEventsForPoint().
resetSequenceNumber()
void LoggerManager::resetSequenceNumber ()
Definition at line 489 of file LoggerManager.cpp.
References _fileSequenceNumber.
setAlarmStateLogDirectory()
void LoggerManager::setAlarmStateLogDirectory (const String & directory)
Definition at line 881 of file LoggerManager.cpp.
References _alarmStateLogDirectory.
setAlarmStateLoggingEnabled()
void LoggerManager::setAlarmStateLoggingEnabled (bool enabled)
Definition at line 872 of file LoggerManager.cpp.
References _alarmStateLoggingEnabled.
setDailyFiles()
void LoggerManager::setDailyFiles (bool enabled)
Enable or disable daily file creation.
Parameters
[in] enabled True to create new files daily
Definition at line 151 of file LoggerManager.cpp.
References _dailyFiles.
setEnabled()
void LoggerManager::setEnabled (bool enabled)
Enable or disable logging.
Parameters
[in] enabled True to enable logging
Definition at line 142 of file LoggerManager.cpp.
References _enabled.
setEventLogDirectory()
void LoggerManager::setEventLogDirectory (const String & directory)
Definition at line 692 of file LoggerManager.cpp.
References _eventLogDirectory.
setEventLoggingEnabled()
void LoggerManager::setEventLoggingEnabled (bool enabled)
Definition at line 683 of file LoggerManager.cpp.
References _eventLoggingEnabled.
setLogDirectory()
void LoggerManager::setLogDirectory (const String & directory)
Set base log directory.
Parameters
[in] directory Directory path for log files
Definition at line 159 of file LoggerManager.cpp.
References _logDirectory.
setLogFrequency()
void LoggerManager::setLogFrequency (unsigned long frequencyMs)
Set logging frequency.
Parameters
[in] frequencyMs Frequency in milliseconds between log entries
Definition at line 132 of file LoggerManager.cpp.
References _logFrequency.
update()
void LoggerManager::update ()
Definition at line 170 of file LoggerManager.cpp.
References _currentEventLogFile, _dailyFiles, _enabled, _eventLoggingEnabled, _generateEventLogFileName(), _getCurrentDateString(), _hasHeaderChanged(), _incrementSequenceNumber(), _lastEventLogDate, _lastLogDate, _lastLogTime, _logFrequency, _recoverFromExistingFiles(), createNewLogFile(), logDataNow(), logInfo(), and logWarning().
warning()
bool LoggerManager::warning (const String & source, const String & description) inline static
Log warning message (static convenience method)
Parameters
[in] source Source component or module
[in] description Description of the warning
Returns
bool True if logging successful
Definition at line 155 of file LoggerManager.h.
References _instance.
Referenced by TemperatureController::addAlarm(), ConfigManager::begin(), TempModbusServer::begin(), TemperatureController::bindSensorToPointByChipSelect(), TemperatureController::bindSensorToPointByRom(), TemperatureController::forceRelayState(), TempModbusServer::processCommands(), Alarm::reactivate(), and Alarm::updateCondition().
Field Documentation
_alarmStateLogDirectory
String LoggerManager::_alarmStateLogDirectory private
Definition at line 98 of file LoggerManager.h.
Referenced by _generateAlarmStateLogFileName(), deleteAlarmStateLogFile(), getAlarmStateLogDirectory(), LoggerManager(), and setAlarmStateLogDirectory().
_alarmStateLoggingEnabled
bool LoggerManager::_alarmStateLoggingEnabled private
Definition at line 97 of file LoggerManager.h.
Referenced by begin(), isAlarmStateLoggingEnabled(), logAlarmState(), LoggerManager(), and setAlarmStateLoggingEnabled().
_controller
TemperatureController* LoggerManager::_controller private
Reference to temperature controller.
Definition at line 40 of file LoggerManager.h.
Referenced by _generateCSVHeader(), _writeDataRow(), and LoggerManager().
_currentAlarmStateLogFile
String LoggerManager::_currentAlarmStateLogFile private
Definition at line 99 of file LoggerManager.h.
Referenced by _ensureAlarmStateLogExists(), _writeAlarmStateHeader(), _writeAlarmStateRow(), begin(), getCurrentAlarmStateLogFile(), logAlarmState(), and LoggerManager().
_currentEventLogFile
String LoggerManager::_currentEventLogFile private
Definition at line 86 of file LoggerManager.h.
Referenced by _ensureEventLogExists(), _writeEventHeader(), _writeEventRow(), getCurrentEventLogFile(), init(), logEvent(), LoggerManager(), and update().
_currentLogFile
String LoggerManager::_currentLogFile private
Current log file name.
Definition at line 46 of file LoggerManager.h.
Referenced by _recoverFromExistingFiles(), _writeDataRow(), _writeHeader(), begin(), createNewLogFile(), getCurrentLogFile(), getLogFileSize(), and init().
_dailyFiles
bool LoggerManager::_dailyFiles private
Create new file each day.
Definition at line 52 of file LoggerManager.h.
Referenced by isDailyFiles(), LoggerManager(), setDailyFiles(), and update().
_enabled
bool LoggerManager::_enabled private
Whether logging is enabled.
Definition at line 50 of file LoggerManager.h.
Referenced by _ensureAlarmStateLogExists(), _ensureDirectoryExists(), _ensureEventLogExists(), _recoverFromExistingFiles(), _writeAlarmStateHeader(), _writeAlarmStateRow(), _writeDataRow(), _writeEventHeader(), _writeEventRow(), _writeHeader(), begin(), createNewLogFile(), deleteEventLogFile(), deleteLogFile(), forceNewFile(), getLogFileSize(), init(), isEnabled(), logAlarmState(), logCritical(), logDataNow(), logError(), logEvent(), LoggerManager(), logInfo(), logWarning(), setEnabled(), and update().
_eventLogDirectory
String LoggerManager::_eventLogDirectory private
Definition at line 85 of file LoggerManager.h.
Referenced by _generateEventLogFileName(), deleteEventLogFile(), getEventLogDirectory(), getEventLogFiles(), LoggerManager(), and setEventLogDirectory().
_eventLoggingEnabled
bool LoggerManager::_eventLoggingEnabled private
Definition at line 84 of file LoggerManager.h.
Referenced by init(), isEventLoggingEnabled(), logEvent(), LoggerManager(), setEventLoggingEnabled(), and update().
_fileSequenceNumber
int LoggerManager::_fileSequenceNumber private
Definition at line 76 of file LoggerManager.h.
Referenced by _generateLogFileNameWithSequence(), _incrementSequenceNumber(), _recoverFromExistingFiles(), begin(), createNewLogFile(), getCurrentSequenceNumber(), LoggerManager(), and resetSequenceNumber().
_fs
fs::FS* LoggerManager::_fs private
File system interface (SD or LittleFS)
Definition at line 42 of file LoggerManager.h.
Referenced by _ensureAlarmStateLogExists(), _ensureDirectoryExists(), _ensureEventLogExists(), _getFilesForDate(), _isSDCardAvailable(), _readHeaderFromFile(), _writeAlarmStateHeader(), _writeAlarmStateRow(), _writeDataRow(), _writeEventHeader(), _writeEventRow(), _writeHeader(), deleteAlarmStateLogFile(), deleteEventLogFile(), deleteLogFile(), getEventLogFiles(), getLogFileSize(), and LoggerManager().
_headerChanged
bool LoggerManager::_headerChanged private
Definition at line 75 of file LoggerManager.h.
Referenced by LoggerManager().
_headerWritten
bool LoggerManager::_headerWritten private
Flag to track if header is written.
Definition at line 47 of file LoggerManager.h.
Referenced by _recoverFromExistingFiles(), begin(), createNewLogFile(), logDataNow(), and LoggerManager().
_instance
LoggerManager * LoggerManager::_instance = nullptr static private
Singleton instance pointer.
Definition at line 39 of file LoggerManager.h.
Referenced by _getAlarmLogFilesInRange(), _getEventLogFilesInRange(), critical(), error(), getAlarmHistoryCsv(), getAlarmHistoryJson(), getAlarmStateLogFiles(), getEventLogFilesStatic(), getEventLogsCsv(), getEventLogsJson(), getEventLogStatsJson(), getFileInfo(), getInstance(), getLogDirectory(), getLogDirectoryPath(), getLogFiles(), info(), logAlarmStateChange(), LoggerManager(), openLogFile(), and warning().
_lastAlarmStateLogDate
String LoggerManager::_lastAlarmStateLogDate private
Definition at line 100 of file LoggerManager.h.
Referenced by begin(), logAlarmState(), and LoggerManager().
_lastError
String LoggerManager::_lastError private
Definition at line 339 of file LoggerManager.h.
Referenced by _writeAlarmStateHeader(), _writeAlarmStateRow(), _writeDataRow(), _writeEventHeader(), _writeEventRow(), _writeHeader(), begin(), getLastError(), init(), and LoggerManager().
_lastEventLogDate
String LoggerManager::_lastEventLogDate private
Definition at line 87 of file LoggerManager.h.
Referenced by init(), logEvent(), LoggerManager(), and update().
_lastGeneratedHeader
String LoggerManager::_lastGeneratedHeader private
Definition at line 74 of file LoggerManager.h.
Referenced by _hasHeaderChanged(), begin(), createNewLogFile(), and LoggerManager().
_lastLogDate
String LoggerManager::_lastLogDate private
Track date for daily file creation.
Definition at line 53 of file LoggerManager.h.
Referenced by begin(), and update().
_lastLogTime
unsigned long LoggerManager::_lastLogTime private
Last time data was logged.
Definition at line 45 of file LoggerManager.h.
Referenced by getLastLogTime(), logDataNow(), LoggerManager(), and update().
_logDirectory
String LoggerManager::_logDirectory private
Base directory for log files.
Definition at line 51 of file LoggerManager.h.
Referenced by _ensureDirectoryExists(), _generateLogFileNameWithSequence(), _getFilesForDate(), deleteLogFile(), LoggerManager(), and setLogDirectory().
_logFrequency
unsigned long LoggerManager::_logFrequency private
Logging frequency in milliseconds.
Definition at line 44 of file LoggerManager.h.
Referenced by begin(), getLogFrequency(), LoggerManager(), setLogFrequency(), and update().
_timeManager
TimeManager* LoggerManager::_timeManager private
Reference to time manager.
Definition at line 41 of file LoggerManager.h.
Referenced by _getCurrentDateString(), _getCurrentTimeString(), and LoggerManager().
The documentation for this class was generated from the following files:
include/LoggerManager.h
src/LoggerManager.cpp