Temperature Control System: TemperatureController Class Reference
TemperatureController Class Reference
Main controller for temperature monitoring system.
#include <TemperatureController.h>
Public Member Functions
TemperatureController (uint8_t oneWirePin[4], uint8_t csPin[4], IndicatorInterface &indicator)
Construct a new Temperature Controller object.
~TemperatureController ()
Destroy the Temperature Controller object.
bool begin ()
Initialize the temperature controller system.
MeasurementPoint * getMeasurementPoint (uint8_t address)
Get measurement point by address.
MeasurementPoint * getDS18B20Point (uint8_t idx)
Get DS18B20 measurement point by index.
MeasurementPoint * getPT1000Point (uint8_t idx)
Get PT1000 measurement point by index.
bool addSensor (Sensor *sensor)
Add a sensor to the controller.
bool removeSensorByRom (const String &romString)
Remove sensor by ROM address string.
Sensor * findSensorByRom (const String &romString)
Find sensor by ROM address string.
Sensor * findSensorByChipSelect (uint8_t csPin)
Find PT1000 sensor by chip select pin.
int getSensorCount () const
Get total number of sensors.
Sensor * getSensorByIndex (int idx)
Get sensor by index.
bool bindSensorToPointByRom (const String &romString, uint8_t pointAddress)
Bind sensor to measurement point by ROM address.
bool bindSensorToPointByChipSelect (uint8_t csPin, uint8_t pointAddress)
Bind PT1000 sensor to measurement point by chip select pin.
bool unbindSensorFromPoint (uint8_t pointAddress)
Unbind sensor from measurement point.
Sensor * getBoundSensor (uint8_t pointAddress)
Get sensor bound to measurement point.
bool unbindSensorFromPointBySensor (Sensor *sensor)
Unbind sensor from any measurement point it's bound to.
void update ()
Main update function - must be called in loop()
void readAllPoints ()
Read temperature from all configured measurement points.
void updateRegisterMap ()
Update register map with current values from measurement points.
void applyConfigFromRegisterMap ()
Apply configuration from register map to system.
void applyConfigToRegisterMap ()
Apply current system configuration to register map.
bool discoverDS18B20Sensors ()
Discover DS18B20 sensors on all OneWire buses.
bool discoverPTSensors ()
Discover PT1000 sensors on SPI bus.
String getSensorsJson ()
Get JSON representation of all sensors.
String getPointsJson ()
Get JSON representation of all measurement points.
String getSystemStatusJson ()
Get JSON representation of system status.
void resetMinMaxValues ()
Reset min/max values for all measurement points.
RegisterMap & getRegisterMap ()
Get reference to register map.
void setDeviceId (uint16_t id)
Set device ID.
uint16_t getDeviceId () const
Get device ID.
void setFirmwareVersion (uint16_t version)
Set firmware version.
uint16_t getFirmwareVersion () const
Get firmware version.
void setMeasurementPeriod (uint16_t seconds)
Set measurement period.
uint16_t getMeasurementPeriod () const
Get measurement period.
void setOneWireBusPin (uint8_t pin, size_t idx)
Set OneWire bus pin.
uint8_t getOneWirePin (size_t bus)
Get OneWire bus pin.
int getDS18B20Count () const
Get count of discovered DS18B20 sensors.
int getPT1000Count () const
Get count of discovered PT1000 sensors.
void updateAllSensors ()
Update temperature readings for all sensors.
int getSensorBus (Sensor *sensor)
Get bus number for a sensor.
void updateAlarms ()
Update alarm states for all measurement points.
String getAlarmsJson ()
Get JSON representation of all alarms.
void handleAlarmDisplay ()
Handle alarm display on OLED/LEDs.
void handleAlarmOutputs ()
Handle alarm output signals.
std::vector< Alarm * > getActiveAlarms () const
Get list of active alarms.
void createAlarm (AlarmType type, MeasurementPoint *source, AlarmPriority priority)
Create new alarm for measurement point.
Alarm * getHighestPriorityAlarm () const
Get highest priority active alarm.
void acknowledgeHighestPriorityAlarm ()
Acknowledge highest priority alarm.
void acknowledgeAllAlarms ()
Acknowledge all active alarms.
void clearResolvedAlarms ()
Clear resolved alarms from system.
void clearConfiguredAlarms ()
Clear all configured alarms.
void ensureAlarmsForPoint (MeasurementPoint *point)
Ensure all 3 alarm types exist for a measurement point.
std::vector< Alarm * > getAlarmsForPoint (MeasurementPoint *point)
Get all alarms associated with a measurement point.
bool addAlarm (AlarmType type, uint8_t pointAddress, AlarmPriority priority)
Add alarm configuration.
bool removeAlarm (const String &configKey)
Remove alarm by configuration key.
bool updateAlarm (const String &configKey, AlarmPriority priority, bool enabled)
Update alarm configuration.
Alarm * findAlarm (const String &configKey)
Find alarm by configuration key.
Alarm * getAlarmByIndex (int idx)
Get alarm by index.
int getAlarmCount () const
Get total number of configured alarms.
std::vector< Alarm * > getConfiguredAlarms () const
Get list of configured alarms.
void handleCriticalAlarms ()
Handle critical priority alarms.
void handleHighPriorityAlarms ()
Handle high priority alarms.
void handleMediumPriorityAlarms ()
Handle medium priority alarms.
void handleLowPriorityAlarms ()
Handle low priority alarms.
bool setRelayControlMode (uint8_t relayNumber, RelayControlMode mode)
Set relay control mode.
RelayControlMode getRelayControlMode (uint8_t relayNumber) const
Get relay control mode.
bool getRelayCommandedState (uint8_t relayNumber) const
Get relay commanded state.
bool getRelayActualState (uint8_t relayNumber) const
Get relay actual state.
void forceRelayState (uint8_t relayNumber, bool state)
Force relay state (for Modbus control)
bool bindSensorToPointByBusNumber (uint8_t busNumber, uint8_t pointAddress)
Bind sensor to measurement point by bus number.
void setAcknowledgedDelayCritical (unsigned long delay)
Set acknowledge delay for critical alarms.
void setAcknowledgedDelayHigh (unsigned long delay)
Set acknowledge delay for high priority alarms.
void setAcknowledgedDelayMedium (unsigned long delay)
Set acknowledge delay for medium priority alarms.
void setAcknowledgedDelayLow (unsigned long delay)
Set acknowledge delay for low priority alarms.
unsigned long getAcknowledgedDelayCritical () const
Get acknowledge delay for critical alarms.
unsigned long getAcknowledgedDelayHigh () const
Get acknowledge delay for high priority alarms.
unsigned long getAcknowledgedDelayMedium () const
Get acknowledge delay for medium priority alarms.
unsigned long getAcknowledgedDelayLow () const
Get acknowledge delay for low priority alarms.
void applyAcknowledgedDelaysToAlarms ()
Apply acknowledged delays to existing alarms.
int getAlarmCount (AlarmPriority priority, const String &comparison="==") const
Get count of alarms by priority.
int getAlarmCount (AlarmStage stage, const String &comparison="==") const
Get count of alarms by stage.
int getAlarmCount (AlarmPriority priority, AlarmStage stage, const String &priorityComparison="==", const String &stageComparison="==") const
Get count of alarms by priority and stage.
Private Types
enum DisplaySection { SECTION_ALARM_ACK , SECTION_ACK_ALARMS , SECTION_STATUS , SECTION_NORMAL }
Private Member Functions
bool isDS18B20Address (uint8_t address) const
Check if address is for DS18B20 sensor.
bool isPT1000Address (uint8_t address) const
Check if address is for PT1000 sensor.
void _checkPointForAlarms (MeasurementPoint *point)
Check measurement point for alarm conditions.
bool _hasAlarmForPoint (MeasurementPoint *point, AlarmType type)
Check if alarm exists for point and type.
void _checkButtonPress ()
Check for button press and handle acknowledgment.
void _updateNormalDisplay ()
Update normal temperature display.
void _showOKAndTurnOffOLED ()
Show OK status and turn off OLED after delay.
bool _comparePriority (AlarmPriority alarmPriority, AlarmPriority targetPriority, const String &comparison) const
Compare alarm priority with comparison operator.
bool _compareStage (AlarmStage alarmStage, AlarmStage targetStage, const String &comparison) const
Compare alarm stage with comparison operator.
void _handleLowPriorityBlinking ()
Handle LED blinking for low priority alarms.
void _updateAlarmQueues ()
Update alarm display queues.
void _displayNextActiveAlarm ()
Display next active alarm in rotation.
void _displayNextAcknowledgedAlarm ()
Display next acknowledged alarm.
void _handleAlarmDisplayRotation ()
Handle alarm display rotation timing.
String _getPriorityString (AlarmPriority priority) const
Get string representation of alarm priority.
String _getAlarmTypeString (AlarmType type) const
Get string representation of alarm type.
void _handleSystemStatusMode ()
Handle system status mode display.
void _displayNetworkInfo ()
Display network info page.
void _displaySystemStats ()
Display system stats page.
void _displayAlarmSummaryByPriority ()
Display alarm summary by priority.
void _displayAlarmSummaryByType ()
Display alarm summary by type.
void _displayModbusStatus ()
Display Modbus status page.
void _handleDisplaySections ()
Handle display section switching.
void _switchToSection (DisplaySection newSection)
Switch to a new display section.
Private Attributes
IndicatorInterface & indicator
Reference to indicator interface for display/LED control.
OneWire * oneWireBuses [4]
Array of OneWire bus objects.
DallasTemperature * dallasSensors [4]
Array of Dallas temperature sensor objects.
MeasurementPoint dsPoints [50]
Array of DS18B20 measurement points.
MeasurementPoint ptPoints [10]
Array of PT1000 measurement points.
std::vector< Sensor * > sensors
Vector of all discovered sensors.
RegisterMap registerMap
Modbus register map for communication.
uint16_t measurementPeriodSeconds
Time between measurements in seconds.
uint16_t deviceId
Unique device identifier.
uint16_t firmwareVersion
Firmware version number.
unsigned long lastMeasurementTime
Timestamp of last measurement.
bool systemInitialized
System initialization flag.
uint8_t oneWireBusPin [4]
GPIO pins for OneWire buses.
uint8_t chipSelectPin [4]
Chip select pins for PT1000 sensors.
std::vector< Alarm * > _configuredAlarms
Vector of configured alarm objects.
unsigned long _lastAlarmCheck
Timestamp of last alarm check.
const unsigned long _alarmCheckInterval = 1000
Alarm check interval in milliseconds.
bool _lastButtonState
Previous button state for edge detection.
unsigned long _lastButtonPressTime
Timestamp of last button press.
const unsigned long _buttonDebounceDelay = 200
Button debounce delay in milliseconds.
Alarm * _currentDisplayedAlarm
Currently displayed alarm on OLED.
unsigned long _okDisplayStartTime
Timestamp when OK display started.
bool _showingOK
Flag indicating OK status display.
unsigned long _acknowledgedDelayCritical
Acknowledge delay for critical alarms.
unsigned long _acknowledgedDelayHigh
Acknowledge delay for high priority alarms.
unsigned long _acknowledgedDelayMedium
Acknowledge delay for medium priority alarms.
unsigned long _acknowledgedDelayLow
Acknowledge delay for low priority alarms.
bool _relay1State = false
Current state of relay 1.
bool _relay2State = false
Current state of relay 2.
bool _relay3State = false
Current state of relay 3 (Modbus-only)
bool _redLedState = false
Current state of red LED.
bool _greenLedState = false
Current state of green LED (system OK)
bool _yellowLedState = false
Current state of yellow LED.
bool _blueLedState = false
Current state of blue LED.
RelayControlMode _relay1Mode = RelayControlMode::AUTO
Control mode for relay 1.
RelayControlMode _relay2Mode = RelayControlMode::AUTO
Control mode for relay 2.
RelayControlMode _relay3Mode = RelayControlMode::AUTO
Control mode for relay 3.
bool _lowPriorityBlinkState = false
Current blink state for low priority alarms.
unsigned long _lastLowPriorityBlinkTime = 0
Last blink state change timestamp.
const unsigned long _blinkOnTime = 2000
Blink on duration (2 seconds)
const unsigned long _blinkOffTime = 30000
Blink off duration (30 seconds)
std::vector< Alarm * > _activeAlarmsQueue
Queue of active alarms for display rotation.
std::vector< Alarm * > _acknowledgedAlarmsQueue
Queue of acknowledged alarms for display.
int _currentActiveAlarmIndex
Current index in active alarms queue.
int _currentAcknowledgedAlarmIndex
Current index in acknowledged alarms queue.
unsigned long _lastAlarmDisplayTime
Last alarm display update timestamp.
unsigned long _acknowledgedAlarmDisplayDelay
Delay before showing acknowledged alarms.
bool _displayingActiveAlarm
Flag indicating if displaying active alarm.
DisplaySection _currentSection
Current display section.
DisplaySection _previousSection
Previous section (for returning)
bool _inSystemStatusMode
Flag indicating if in system status mode.
int _systemStatusPage
Current page in system status mode (0-4)
unsigned long _buttonPressStartTime
Timestamp when button press started.
unsigned long _systemStatusModeStartTime
Timestamp when entered system status mode.
const unsigned long _longPressThreshold = 3000
Long press threshold (3 seconds)
const unsigned long _systemStatusTimeout = 30000
Auto-exit timeout (30 seconds)
bool _buttonPressHandled
Flag to prevent multiple triggers.
Detailed Description
Main controller for temperature monitoring system.
Manages temperature sensors, measurement points, alarms, and system configuration. Provides unified interface for sensor operations, alarm handling, and data access. Supports both DS18B20 and PT1000 temperature sensors.
Definition at line 46 of file TemperatureController.h.
Member Enumeration Documentation
DisplaySection
enum TemperatureController::DisplaySection private
Enumerator
SECTION_ALARM_ACK
Active alarm acknowledgment section.
SECTION_ACK_ALARMS
Acknowledged alarms display section.
SECTION_STATUS
System status display section.
SECTION_NORMAL
Normal operation (no alarms)
Definition at line 809 of file TemperatureController.h.
Constructor & Destructor Documentation
TemperatureController()
TemperatureController::TemperatureController (uint8_t oneWirePin[4], uint8_t csPin[4], IndicatorInterface & indicator)
Construct a new Temperature Controller object.
Parameters
[in] oneWirePin Array of 4 OneWire bus pins for DS18B20 sensors
[in] csPin Array of 4 chip select pins for PT1000 sensors
[in] indicator Reference to the indicator interface for display/LED control
Definition at line 26 of file TemperatureController.cpp.
References _acknowledgedAlarmDisplayDelay, _buttonPressHandled, _buttonPressStartTime, _currentAcknowledgedAlarmIndex, _currentActiveAlarmIndex, _currentDisplayedAlarm, _currentSection, _displayingActiveAlarm, _inSystemStatusMode, _lastAlarmCheck, _lastAlarmDisplayTime, _lastButtonPressTime, _lastButtonState, _okDisplayStartTime, _previousSection, _showingOK, _systemStatusModeStartTime, _systemStatusPage, chipSelectPin, dallasSensors, deviceId, dsPoints, firmwareVersion, indicator, lastMeasurementTime, measurementPeriodSeconds, oneWireBuses, oneWireBusPin, ptPoints, SECTION_NORMAL, and systemInitialized.
~TemperatureController()
TemperatureController::~TemperatureController ()
Destroy the Temperature Controller object.
Cleans up dynamically allocated sensors and OneWire buses
Definition at line 74 of file TemperatureController.cpp.
References _configuredAlarms, dallasSensors, oneWireBuses, and sensors.
Member Function Documentation
_checkButtonPress()
void TemperatureController::_checkButtonPress () private
Check for button press and handle acknowledgment.
Definition at line 2077 of file TemperatureController.cpp.
References _acknowledgedAlarmsQueue, _activeAlarmsQueue, _buttonPressHandled, _buttonPressStartTime, _currentAcknowledgedAlarmIndex, _currentActiveAlarmIndex, _currentDisplayedAlarm, _currentSection, _lastAlarmDisplayTime, _lastButtonState, _longPressThreshold, _previousSection, _switchToSection(), _systemStatusPage, ACTIVE, indicator, SECTION_ACK_ALARMS, SECTION_ALARM_ACK, SECTION_NORMAL, and SECTION_STATUS.
Referenced by handleAlarmDisplay(), and update().
_checkPointForAlarms()
void TemperatureController::_checkPointForAlarms (MeasurementPoint * point) private
Check measurement point for alarm conditions.
Parameters
[in] point Measurement point to check
Definition at line 250 of file TemperatureController.cpp.
References _hasAlarmForPoint(), createAlarm(), MeasurementPoint::getBoundSensor(), MeasurementPoint::getCurrentTemp(), MeasurementPoint::getErrorStatus(), MeasurementPoint::getHighAlarmThreshold(), MeasurementPoint::getLowAlarmThreshold(), HIGH_TEMPERATURE, LOW_TEMPERATURE, PRIORITY_HIGH, PRIORITY_MEDIUM, and SENSOR_ERROR.
_comparePriority()
bool TemperatureController::_comparePriority (AlarmPriority alarmPriority, AlarmPriority targetPriority, const String & comparison) const private
Compare alarm priority with comparison operator.
Parameters
[in] alarmPriority Priority to compare
[in] targetPriority Target priority
[in] comparison Comparison operator string
Returns
true if comparison matches
Definition at line 1792 of file TemperatureController.cpp.
Referenced by getAlarmCount(), and getAlarmCount().
_compareStage()
bool TemperatureController::_compareStage (AlarmStage alarmStage, AlarmStage targetStage, const String & comparison) const private
Compare alarm stage with comparison operator.
Parameters
[in] alarmStage Stage to compare
[in] targetStage Target stage
[in] comparison Comparison operator string
Returns
true if comparison matches
Definition at line 1811 of file TemperatureController.cpp.
Referenced by getAlarmCount(), and getAlarmCount().
_displayAlarmSummaryByPriority()
void TemperatureController::_displayAlarmSummaryByPriority () private
Display alarm summary by priority.
Definition at line 2426 of file TemperatureController.cpp.
References _configuredAlarms, ACKNOWLEDGED, ACTIVE, getAlarmCount(), indicator, PRIORITY_CRITICAL, PRIORITY_HIGH, PRIORITY_LOW, and PRIORITY_MEDIUM.
Referenced by _handleSystemStatusMode().
_displayAlarmSummaryByType()
void TemperatureController::_displayAlarmSummaryByType () private
Display alarm summary by type.
Definition at line 2464 of file TemperatureController.cpp.
References _configuredAlarms, ACKNOWLEDGED, ACTIVE, HIGH_TEMPERATURE, indicator, LOW_TEMPERATURE, SENSOR_DISCONNECTED, and SENSOR_ERROR.
Referenced by _handleSystemStatusMode().
_displayModbusStatus()
void TemperatureController::_displayModbusStatus () private
Display Modbus status page.
Definition at line 2506 of file TemperatureController.cpp.
References configManager, indicator, and registerMap.
Referenced by _handleSystemStatusMode().
_displayNetworkInfo()
void TemperatureController::_displayNetworkInfo () private
Display network info page.
Definition at line 2347 of file TemperatureController.cpp.
References configManager, and indicator.
Referenced by _handleSystemStatusMode().
_displayNextAcknowledgedAlarm()
void TemperatureController::_displayNextAcknowledgedAlarm () private
Display next acknowledged alarm.
Definition at line 1962 of file TemperatureController.cpp.
References _acknowledgedAlarmsQueue, _currentAcknowledgedAlarmIndex, _currentDisplayedAlarm, _lastAlarmDisplayTime, _showingOK, indicator, and timeManager.
Referenced by _handleAlarmDisplayRotation(), and _handleDisplaySections().
_displayNextActiveAlarm()
void TemperatureController::_displayNextActiveAlarm () private
Display next active alarm in rotation.
Definition at line 1898 of file TemperatureController.cpp.
References _activeAlarmsQueue, _currentActiveAlarmIndex, _currentDisplayedAlarm, _showingOK, indicator, and timeManager.
Referenced by _handleAlarmDisplayRotation().
_displaySystemStats()
void TemperatureController::_displaySystemStats () private
Display system stats page.
Definition at line 2388 of file TemperatureController.cpp.
References getBoundSensor(), getDS18B20Count(), getPT1000Count(), and indicator.
Referenced by _handleSystemStatusMode().
_getAlarmTypeString()
String TemperatureController::_getAlarmTypeString (AlarmType type) const private
Get string representation of alarm type.
Parameters
[in] type Alarm type enum value
Returns
String Alarm type as string
Definition at line 2162 of file TemperatureController.cpp.
References HIGH_TEMPERATURE, LOW_TEMPERATURE, SENSOR_DISCONNECTED, and SENSOR_ERROR.
_getPriorityString()
String TemperatureController::_getPriorityString (AlarmPriority priority) const private
Get string representation of alarm priority.
Parameters
[in] priority Alarm priority enum value
Returns
String Priority as string
Definition at line 2172 of file TemperatureController.cpp.
References PRIORITY_CRITICAL, PRIORITY_HIGH, PRIORITY_LOW, and PRIORITY_MEDIUM.
Referenced by addAlarm().
_handleAlarmDisplayRotation()
void TemperatureController::_handleAlarmDisplayRotation () private
Handle alarm display rotation timing.
Definition at line 2027 of file TemperatureController.cpp.
References _acknowledgedAlarmDisplayDelay, _acknowledgedAlarmsQueue, _activeAlarmsQueue, _currentAcknowledgedAlarmIndex, _currentActiveAlarmIndex, _currentDisplayedAlarm, _displayingActiveAlarm, _displayNextAcknowledgedAlarm(), _displayNextActiveAlarm(), _lastAlarmDisplayTime, _okDisplayStartTime, _showingOK, _showOKAndTurnOffOLED(), _updateNormalDisplay(), ACKNOWLEDGED, and indicator.
Referenced by _handleDisplaySections().
_handleDisplaySections()
void TemperatureController::_handleDisplaySections () private
Handle display section switching.
Definition at line 2545 of file TemperatureController.cpp.
References _acknowledgedAlarmsQueue, _activeAlarmsQueue, _currentSection, _displayNextAcknowledgedAlarm(), _handleAlarmDisplayRotation(), _handleSystemStatusMode(), _previousSection, _switchToSection(), _systemStatusModeStartTime, _systemStatusTimeout, _updateAlarmQueues(), _updateNormalDisplay(), SECTION_ACK_ALARMS, SECTION_ALARM_ACK, SECTION_NORMAL, and SECTION_STATUS.
Referenced by handleAlarmDisplay().
_handleLowPriorityBlinking()
void TemperatureController::_handleLowPriorityBlinking () private
Handle LED blinking for low priority alarms.
Definition at line 1831 of file TemperatureController.cpp.
References _blinkOffTime, _blinkOnTime, _lastLowPriorityBlinkTime, and _lowPriorityBlinkState.
_handleSystemStatusMode()
void TemperatureController::_handleSystemStatusMode () private
Handle system status mode display.
Definition at line 2320 of file TemperatureController.cpp.
References _activeAlarmsQueue, _displayAlarmSummaryByPriority(), _displayAlarmSummaryByType(), _displayModbusStatus(), _displayNetworkInfo(), _displaySystemStats(), _switchToSection(), _systemStatusPage, and SECTION_ALARM_ACK.
Referenced by _handleDisplaySections().
_hasAlarmForPoint()
bool TemperatureController::_hasAlarmForPoint (MeasurementPoint * point, AlarmType type) private
Check if alarm exists for point and type.
Parameters
[in] point Measurement point to check
[in] type Alarm type to check
Returns
true if alarm exists for this point/type combination
Definition at line 275 of file TemperatureController.cpp.
References _configuredAlarms.
Referenced by _checkPointForAlarms().
_showOKAndTurnOffOLED()
void TemperatureController::_showOKAndTurnOffOLED () private
Show OK status and turn off OLED after delay.
Definition at line 844 of file TemperatureController.cpp.
References _okDisplayStartTime, _showingOK, and indicator.
Referenced by _handleAlarmDisplayRotation().
_switchToSection()
void TemperatureController::_switchToSection (DisplaySection newSection) private
Switch to a new display section.
Parameters
[in] newSection Section to switch to
Definition at line 2593 of file TemperatureController.cpp.
References _currentSection, _lastAlarmDisplayTime, _previousSection, _showingOK, _systemStatusModeStartTime, _systemStatusPage, indicator, SECTION_ACK_ALARMS, SECTION_ALARM_ACK, SECTION_NORMAL, and SECTION_STATUS.
Referenced by _checkButtonPress(), _handleDisplaySections(), and _handleSystemStatusMode().
_updateAlarmQueues()
void TemperatureController::_updateAlarmQueues () private
Update alarm display queues.
Definition at line 1862 of file TemperatureController.cpp.
References _acknowledgedAlarmsQueue, _activeAlarmsQueue, ACKNOWLEDGED, ACTIVE, getActiveAlarms(), and Alarm::getTimestamp().
Referenced by _handleDisplaySections().
_updateNormalDisplay()
void TemperatureController::_updateNormalDisplay () private
Update normal temperature display.
Definition at line 833 of file TemperatureController.cpp.
References indicator.
Referenced by _handleAlarmDisplayRotation(), and _handleDisplaySections().
acknowledgeAllAlarms()
void TemperatureController::acknowledgeAllAlarms ()
Acknowledge all active alarms.
Moves all alarms to acknowledged state
Definition at line 331 of file TemperatureController.cpp.
References _configuredAlarms.
acknowledgeHighestPriorityAlarm()
void TemperatureController::acknowledgeHighestPriorityAlarm ()
Acknowledge highest priority alarm.
Moves alarm from active to acknowledged state
Definition at line 323 of file TemperatureController.cpp.
References Alarm::acknowledge(), getHighestPriorityAlarm(), and Alarm::getStatusText().
addAlarm()
bool TemperatureController::addAlarm (AlarmType type, uint8_t pointAddress, AlarmPriority priority)
Add alarm configuration.
Parameters
[in] type Alarm type
[in] pointAddress Measurement point address
[in] priority Alarm priority
Returns
true if alarm added successfully
false if alarm already exists or invalid parameters
Definition at line 1502 of file TemperatureController.cpp.
References _acknowledgedDelayCritical, _acknowledgedDelayHigh, _acknowledgedDelayLow, _acknowledgedDelayMedium, _configuredAlarms, _getPriorityString(), getMeasurementPoint(), MeasurementPoint::getName(), Alarm::getTypeString(), LoggerManager::info(), PRIORITY_CRITICAL, PRIORITY_HIGH, PRIORITY_LOW, PRIORITY_MEDIUM, Alarm::setAcknowledgedDelay(), Alarm::setConfigKey(), and LoggerManager::warning().
addSensor()
bool TemperatureController::addSensor (Sensor * sensor)
Add a sensor to the controller.
Parameters
[in] sensor Pointer to sensor object to add
Returns
true if sensor added successfully
false if sensor already exists or nullptr
Definition at line 924 of file TemperatureController.cpp.
References DS18B20, findSensorByChipSelect(), findSensorByRom(), Sensor::getDS18B20RomString(), Sensor::getPT1000ChipSelectPin(), Sensor::getType(), PT1000, registerMap, and sensors.
applyAcknowledgedDelaysToAlarms()
void TemperatureController::applyAcknowledgedDelaysToAlarms ()
Apply acknowledged delays to existing alarms.
Updates all existing alarms with current delay settings
Definition at line 1688 of file TemperatureController.cpp.
References _acknowledgedDelayCritical, _acknowledgedDelayHigh, _acknowledgedDelayLow, _acknowledgedDelayMedium, _configuredAlarms, PRIORITY_CRITICAL, PRIORITY_HIGH, PRIORITY_LOW, and PRIORITY_MEDIUM.
Referenced by setAcknowledgedDelayCritical(), setAcknowledgedDelayHigh(), setAcknowledgedDelayLow(), and setAcknowledgedDelayMedium().
applyConfigFromRegisterMap()
void TemperatureController::applyConfigFromRegisterMap ()
Apply configuration from register map to system.
Updates system settings from Modbus register values
Definition at line 1079 of file TemperatureController.cpp.
References dsPoints, ptPoints, and registerMap.
applyConfigToRegisterMap()
void TemperatureController::applyConfigToRegisterMap ()
Apply current system configuration to register map.
Updates Modbus registers with current system settings
Definition at line 1086 of file TemperatureController.cpp.
References dsPoints, ptPoints, and registerMap.
begin()
bool TemperatureController::begin ()
Initialize the temperature controller system.
Returns
true if initialization successful
false if initialization failed
Initializes OneWire buses, discovers sensors, loads configuration
Definition at line 94 of file TemperatureController.cpp.
References deviceId, discoverPTSensors(), firmwareVersion, indicator, LoggerManager::info(), registerMap, and systemInitialized.
bindSensorToPointByBusNumber()
bool TemperatureController::bindSensorToPointByBusNumber (uint8_t busNumber, uint8_t pointAddress)
Bind sensor to measurement point by bus number.
Parameters
[in] busNumber OneWire bus number (0-3)
[in] pointAddress Measurement point address
Returns
true if binding successful
false if invalid bus or point
Definition at line 1625 of file TemperatureController.cpp.
References MeasurementPoint::bindSensor(), getMeasurementPoint(), getSensorBus(), LoggerManager::info(), PT1000, and sensors.
bindSensorToPointByChipSelect()
bool TemperatureController::bindSensorToPointByChipSelect (uint8_t csPin, uint8_t pointAddress)
Bind PT1000 sensor to measurement point by chip select pin.
Parameters
[in] csPin Chip select pin of PT1000 sensor
[in] pointAddress Measurement point address
Returns
true if binding successful
false if sensor or point not found
Definition at line 1006 of file TemperatureController.cpp.
References MeasurementPoint::bindSensor(), findSensorByChipSelect(), getMeasurementPoint(), MeasurementPoint::getName(), LoggerManager::info(), unbindSensorFromPointBySensor(), and LoggerManager::warning().
bindSensorToPointByRom()
bool TemperatureController::bindSensorToPointByRom (const String & romString, uint8_t pointAddress)
Bind sensor to measurement point by ROM address.
Parameters
[in] romString ROM address of sensor to bind
[in] pointAddress Measurement point address
Returns
true if binding successful
false if sensor or point not found
Definition at line 981 of file TemperatureController.cpp.
References MeasurementPoint::bindSensor(), findSensorByRom(), getMeasurementPoint(), MeasurementPoint::getName(), LoggerManager::info(), unbindSensorFromPointBySensor(), and LoggerManager::warning().
clearConfiguredAlarms()
void TemperatureController::clearConfiguredAlarms ()
Clear all configured alarms.
Removes all alarm configurations
Warning
This deletes all alarm settings
Definition at line 365 of file TemperatureController.cpp.
References _configuredAlarms, and _currentDisplayedAlarm.
clearResolvedAlarms()
void TemperatureController::clearResolvedAlarms ()
Clear resolved alarms from system.
Removes alarms that are no longer active
Definition at line 350 of file TemperatureController.cpp.
References _configuredAlarms, and _currentDisplayedAlarm.
createAlarm()
void TemperatureController::createAlarm (AlarmType type, MeasurementPoint * source, AlarmPriority priority)
Create new alarm for measurement point.
Parameters
[in] type Alarm type (HIGH_TEMP, LOW_TEMP, etc.)
[in] source Measurement point that triggered alarm
[in] priority Alarm priority level
Definition at line 288 of file TemperatureController.cpp.
References _configuredAlarms, MeasurementPoint::getAddress(), NEW, and Alarm::setConfigKey().
Referenced by _checkPointForAlarms().
discoverDS18B20Sensors()
bool TemperatureController::discoverDS18B20Sensors ()
Discover DS18B20 sensors on all OneWire buses.
Returns
true if any sensors discovered
false if no sensors found
Scans all 4 OneWire buses for DS18B20 sensors
Definition at line 1093 of file TemperatureController.cpp.
References dallasSensors, DS18B20, findSensorByRom(), Sensor::getName(), Sensor::getOneWirePin(), getSensorBus(), LoggerManager::info(), Sensor::initialize(), oneWireBusPin, registerMap, removeSensorByRom(), sensors, and Sensor::setupDS18B20().
discoverPTSensors()
bool TemperatureController::discoverPTSensors ()
Discover PT1000 sensors on SPI bus.
Returns
true if any sensors discovered
false if no sensors found
Checks all 4 chip select pins for PT1000 sensors
Definition at line 1168 of file TemperatureController.cpp.
References chipSelectPin, findSensorByChipSelect(), Sensor::getName(), Sensor::getPT1000ChipSelectPin(), getSensorBus(), LoggerManager::info(), Sensor::initialize(), PT1000, registerMap, sensors, and Sensor::setupPT1000().
Referenced by begin().
ensureAlarmsForPoint()
void TemperatureController::ensureAlarmsForPoint (MeasurementPoint * point)
Ensure all 3 alarm types exist for a measurement point.
Parameters
[in] point Measurement point to create alarms for
Creates LOW_TEMPERATURE, HIGH_TEMPERATURE, and SENSOR_ERROR alarms if they don't exist
Definition at line 376 of file TemperatureController.cpp.
References _configuredAlarms, findAlarm(), MeasurementPoint::getAddress(), MeasurementPoint::getBoundSensor(), HIGH_TEMPERATURE, LOW_TEMPERATURE, PRIORITY_HIGH, PRIORITY_MEDIUM, SENSOR_ERROR, Alarm::setConfigKey(), Alarm::setEnabled(), and Alarm::setPriority().
findAlarm()
Alarm * TemperatureController::findAlarm (const String & configKey)
Find alarm by configuration key.
Parameters
[in] configKey Alarm configuration key
Returns
Alarm* Pointer to alarm or nullptr if not found
Definition at line 1585 of file TemperatureController.cpp.
References _configuredAlarms.
Referenced by ensureAlarmsForPoint(), and updateAlarm().
findSensorByChipSelect()
Sensor * TemperatureController::findSensorByChipSelect (uint8_t csPin)
Find PT1000 sensor by chip select pin.
Parameters
[in] csPin Chip select pin number
Returns
Sensor* Pointer to sensor or nullptr if not found
Definition at line 969 of file TemperatureController.cpp.
References PT1000, and sensors.
Referenced by addSensor(), bindSensorToPointByChipSelect(), and discoverPTSensors().
findSensorByRom()
Sensor * TemperatureController::findSensorByRom (const String & romString)
Find sensor by ROM address string.
Parameters
[in] romString ROM address as hex string
Returns
Sensor* Pointer to sensor or nullptr if not found
Definition at line 959 of file TemperatureController.cpp.
References DS18B20, and sensors.
Referenced by addSensor(), bindSensorToPointByRom(), and discoverDS18B20Sensors().
forceRelayState()
void TemperatureController::forceRelayState (uint8_t relayNumber, bool state)
Force relay state (for Modbus control)
Parameters
[in] relayNumber Relay number (1-3)
[in] state Desired relay state
Only works when relay is in FORCE_OFF or FORCE_ON mode
Definition at line 2280 of file TemperatureController.cpp.
References _relay1State, _relay2State, _relay3State, AUTO, LoggerManager::error(), getRelayControlMode(), indicator, LoggerManager::info(), and LoggerManager::warning().
getAcknowledgedDelayCritical()
unsigned long TemperatureController::getAcknowledgedDelayCritical () const
Get acknowledge delay for critical alarms.
Returns
unsigned long Delay in milliseconds
Definition at line 1671 of file TemperatureController.cpp.
References _acknowledgedDelayCritical.
getAcknowledgedDelayHigh()
unsigned long TemperatureController::getAcknowledgedDelayHigh () const
Get acknowledge delay for high priority alarms.
Returns
unsigned long Delay in milliseconds
Definition at line 1675 of file TemperatureController.cpp.
References _acknowledgedDelayHigh.
getAcknowledgedDelayLow()
unsigned long TemperatureController::getAcknowledgedDelayLow () const
Get acknowledge delay for low priority alarms.
Returns
unsigned long Delay in milliseconds
Definition at line 1683 of file TemperatureController.cpp.
References _acknowledgedDelayLow.
getAcknowledgedDelayMedium()
unsigned long TemperatureController::getAcknowledgedDelayMedium () const
Get acknowledge delay for medium priority alarms.
Returns
unsigned long Delay in milliseconds
Definition at line 1679 of file TemperatureController.cpp.
References _acknowledgedDelayMedium.
getActiveAlarms()
std::vector< Alarm * > TemperatureController::getActiveAlarms () const
Get list of active alarms.
Returns
std::vector<Alarm*> Vector of active alarm pointers
Definition at line 340 of file TemperatureController.cpp.
References _configuredAlarms.
Referenced by _updateAlarmQueues(), and updateAlarms().
getAlarmByIndex()
Alarm * TemperatureController::getAlarmByIndex (int idx)
Get alarm by index.
Parameters
[in] idx Alarm index
Returns
Alarm* Pointer to alarm or nullptr if invalid index
Definition at line 1594 of file TemperatureController.cpp.
References _configuredAlarms.
getAlarmCount() [1/4]
int TemperatureController::getAlarmCount () const inline
Get total number of configured alarms.
Returns
int Number of configured alarms
Definition at line 471 of file TemperatureController.h.
References _configuredAlarms.
Referenced by _displayAlarmSummaryByPriority(), getRelayCommandedState(), and handleAlarmOutputs().
getAlarmCount() [2/4]
int TemperatureController::getAlarmCount (AlarmPriority priority, AlarmStage stage, const String & priorityComparison = "==", const String & stageComparison = "==") const
Get count of alarms by priority and stage.
Parameters
[in] priority Priority level to filter
[in] stage Alarm stage to filter
[in] priorityComparison Priority comparison operator
[in] stageComparison Stage comparison operator
Returns
int Number of alarms matching both criteria
Definition at line 1777 of file TemperatureController.cpp.
References _comparePriority(), _compareStage(), and _configuredAlarms.
getAlarmCount() [3/4]
int TemperatureController::getAlarmCount (AlarmPriority priority, const String & comparison = "==") const
Get count of alarms by priority.
Parameters
[in] priority Priority level to count
[in] comparison Comparison operator ("==", ">=", "<=", ">", "<")
Returns
int Number of alarms matching criteria
Definition at line 1757 of file TemperatureController.cpp.
References _comparePriority(), and _configuredAlarms.
getAlarmCount() [4/4]
int TemperatureController::getAlarmCount (AlarmStage stage, const String & comparison = "==") const
Get count of alarms by stage.
Parameters
[in] stage Alarm stage to count
[in] comparison Comparison operator ("==", "!=")
Returns
int Number of alarms matching criteria
Definition at line 1767 of file TemperatureController.cpp.
References _compareStage(), and _configuredAlarms.
getAlarmsForPoint()
std::vector< Alarm * > TemperatureController::getAlarmsForPoint (MeasurementPoint * point)
Get all alarms associated with a measurement point.
Parameters
[in] point Measurement point to get alarms for
Returns
std::vector<Alarm*> Vector of alarms for the point
Definition at line 415 of file TemperatureController.cpp.
References _configuredAlarms, and MeasurementPoint::getAddress().
getAlarmsJson()
String TemperatureController::getAlarmsJson ()
Get JSON representation of all alarms.
Returns
String JSON array of alarm objects
Includes alarm type, priority, state, and associated point
Definition at line 850 of file TemperatureController.cpp.
References _configuredAlarms, and HIGH_TEMPERATURE.
getBoundSensor()
Sensor * TemperatureController::getBoundSensor (uint8_t pointAddress)
Get sensor bound to measurement point.
Parameters
[in] pointAddress Measurement point address
Returns
Sensor* Pointer to bound sensor or nullptr if not bound
Definition at line 1053 of file TemperatureController.cpp.
References MeasurementPoint::getBoundSensor(), and getMeasurementPoint().
Referenced by _displaySystemStats(), removeSensorByRom(), and updateAlarms().
getConfiguredAlarms()
std::vector< Alarm * > TemperatureController::getConfiguredAlarms () const inline
Get list of configured alarms.
Returns
std::vector<Alarm*> Vector of configured alarm pointers
Definition at line 477 of file TemperatureController.h.
References _configuredAlarms.
getDeviceId()
uint16_t TemperatureController::getDeviceId () const
Get device ID.
Returns
uint16_t Current device identifier
Definition at line 1374 of file TemperatureController.cpp.
References deviceId.
getDS18B20Count()
int TemperatureController::getDS18B20Count () const
Get count of discovered DS18B20 sensors.
Returns
int Number of DS18B20 sensors
Definition at line 1402 of file TemperatureController.cpp.
References DS18B20, and sensors.
Referenced by _displaySystemStats(), and getSystemStatusJson().
getDS18B20Point()
MeasurementPoint * TemperatureController::getDS18B20Point (uint8_t idx)
Get DS18B20 measurement point by index.
Parameters
[in] idx Index in DS18B20 array (0-49)
Returns
MeasurementPoint* Pointer to DS18B20 point or nullptr if invalid index
Definition at line 916 of file TemperatureController.cpp.
References dsPoints.
getFirmwareVersion()
uint16_t TemperatureController::getFirmwareVersion () const
Get firmware version.
Returns
uint16_t Current firmware version
Definition at line 1381 of file TemperatureController.cpp.
References firmwareVersion.
getHighestPriorityAlarm()
Alarm * TemperatureController::getHighestPriorityAlarm () const
Get highest priority active alarm.
Returns
Alarm* Pointer to highest priority alarm or nullptr
Definition at line 313 of file TemperatureController.cpp.
References _configuredAlarms.
Referenced by acknowledgeHighestPriorityAlarm().
getMeasurementPeriod()
uint16_t TemperatureController::getMeasurementPeriod () const
Get measurement period.
Returns
uint16_t Current measurement period in seconds
Definition at line 1394 of file TemperatureController.cpp.
References measurementPeriodSeconds.
getMeasurementPoint()
MeasurementPoint * TemperatureController::getMeasurementPoint (uint8_t address)
Get measurement point by address.
Parameters
[in] address Point address (0-49 for DS18B20, 50-59 for PT1000)
Returns
MeasurementPoint* Pointer to measurement point or nullptr if invalid address
Definition at line 908 of file TemperatureController.cpp.
References dsPoints, isDS18B20Address(), isPT1000Address(), and ptPoints.
Referenced by addAlarm(), bindSensorToPointByBusNumber(), bindSensorToPointByChipSelect(), bindSensorToPointByRom(), getBoundSensor(), and unbindSensorFromPoint().
getOneWirePin()
uint8_t TemperatureController::getOneWirePin (size_t bus)
Get OneWire bus pin.
Parameters
[in] bus Bus index (0-3)
Returns
uint8_t GPIO pin number or 0xFF if invalid bus
Definition at line 1448 of file TemperatureController.cpp.
References oneWireBusPin.
getPointsJson()
String TemperatureController::getPointsJson ()
Get JSON representation of all measurement points.
Returns
String JSON array of measurement point objects
Includes point address, name, value, limits, and alarm status
Definition at line 1278 of file TemperatureController.cpp.
References DS18B20, dsPoints, MeasurementPoint::getAddress(), MeasurementPoint::getAlarmStatus(), MeasurementPoint::getBoundSensor(), MeasurementPoint::getCurrentTemp(), Sensor::getDS18B20RomArray(), Sensor::getDS18B20RomString(), MeasurementPoint::getErrorStatus(), MeasurementPoint::getHighAlarmThreshold(), MeasurementPoint::getLowAlarmThreshold(), MeasurementPoint::getMaxTemp(), MeasurementPoint::getMinTemp(), MeasurementPoint::getName(), Sensor::getPT1000ChipSelectPin(), getSensorBus(), Sensor::getType(), PT1000, and ptPoints.
getPT1000Count()
int TemperatureController::getPT1000Count () const
Get count of discovered PT1000 sensors.
Returns
int Number of PT1000 sensors
Definition at line 1412 of file TemperatureController.cpp.
References PT1000, and sensors.
Referenced by _displaySystemStats(), and getSystemStatusJson().
getPT1000Point()
MeasurementPoint * TemperatureController::getPT1000Point (uint8_t idx)
Get PT1000 measurement point by index.
Parameters
[in] idx Index in PT1000 array (0-9)
Returns
MeasurementPoint* Pointer to PT1000 point or nullptr if invalid index
Definition at line 920 of file TemperatureController.cpp.
References ptPoints.
getRegisterMap()
RegisterMap & TemperatureController::getRegisterMap () inline
Get reference to register map.
Returns
RegisterMap& Reference to the Modbus register map
Definition at line 260 of file TemperatureController.h.
References registerMap.
getRelayActualState()
bool TemperatureController::getRelayActualState (uint8_t relayNumber) const
Get relay actual state.
Parameters
[in] relayNumber Relay number (1-3)
Returns
bool Actual hardware state of relay
Definition at line 2269 of file TemperatureController.cpp.
References _relay1State, _relay2State, _relay3State, and LoggerManager::error().
Referenced by updateRegisterMap().
getRelayCommandedState()
bool TemperatureController::getRelayCommandedState (uint8_t relayNumber) const
Get relay commanded state.
Parameters
[in] relayNumber Relay number (1-3)
Returns
bool Commanded state (what system wants relay to be)
Definition at line 2225 of file TemperatureController.cpp.
References ACKNOWLEDGED, ACTIVE, FORCE_OFF, FORCE_ON, getAlarmCount(), getRelayControlMode(), PRIORITY_CRITICAL, PRIORITY_HIGH, PRIORITY_LOW, and PRIORITY_MEDIUM.
Referenced by updateRegisterMap().
getRelayControlMode()
RelayControlMode TemperatureController::getRelayControlMode (uint8_t relayNumber) const
Get relay control mode.
Parameters
[in] relayNumber Relay number (1-3)
Returns
RelayControlMode Current control mode
Definition at line 2214 of file TemperatureController.cpp.
References _relay1Mode, _relay2Mode, _relay3Mode, AUTO, and LoggerManager::error().
Referenced by forceRelayState(), and getRelayCommandedState().
getSensorBus()
int TemperatureController::getSensorBus (Sensor * sensor)
Get bus number for a sensor.
Parameters
[in] sensor Pointer to sensor
Returns
int Bus number (0-3) or -1 if not found
Definition at line 1452 of file TemperatureController.cpp.
References chipSelectPin, DS18B20, Sensor::getOneWirePin(), Sensor::getPT1000ChipSelectPin(), Sensor::getType(), oneWireBusPin, and PT1000.
Referenced by bindSensorToPointByBusNumber(), discoverDS18B20Sensors(), discoverPTSensors(), getPointsJson(), getSensorsJson(), and updateAllSensors().
getSensorByIndex()
Sensor * TemperatureController::getSensorByIndex (int idx)
Get sensor by index.
Parameters
[in] idx Sensor index
Returns
Sensor* Pointer to sensor or nullptr if invalid index
Definition at line 977 of file TemperatureController.cpp.
References sensors.
getSensorCount()
int TemperatureController::getSensorCount () const inline
Get total number of sensors.
Returns
int Number of sensors registered
Definition at line 127 of file TemperatureController.h.
References sensors.
getSensorsJson()
String TemperatureController::getSensorsJson ()
Get JSON representation of all sensors.
Returns
String JSON array of sensor objects
Includes sensor type, ROM/CS, binding status, and current value
Definition at line 1220 of file TemperatureController.cpp.
References DS18B20, dsPoints, Sensor::getDS18B20RomString(), getSensorBus(), Sensor::getType(), PT1000, ptPoints, and sensors.
getSystemStatusJson()
String TemperatureController::getSystemStatusJson ()
Get JSON representation of system status.
Returns
String JSON object with system information
Includes device ID, firmware version, sensor counts, alarm status
Definition at line 1339 of file TemperatureController.cpp.
References deviceId, firmwareVersion, getDS18B20Count(), getPT1000Count(), measurementPeriodSeconds, and registerMap.
handleAlarmDisplay()
void TemperatureController::handleAlarmDisplay ()
Handle alarm display on OLED/LEDs.
Updates display with highest priority active alarm
Definition at line 1851 of file TemperatureController.cpp.
References _checkButtonPress(), _handleDisplaySections(), and indicator.
Referenced by update().
handleAlarmOutputs()
void TemperatureController::handleAlarmOutputs ()
Handle alarm output signals.
Handle alarm outputs including LEDs and relays based on alarm priorities.
Controls relays and LEDs based on alarm states
LED Logic:
GREEN: Solid when no alarms (system OK)
RED: Solid for CRITICAL priority alarms
YELLOW: Solid for HIGH priority alarms
BLUE: Solid for MEDIUM priority, Blinking for LOW priority
Relay Logic:
CRITICAL: Siren + Beacon ON (acknowledged: Beacon only)
HIGH: Beacon ON (acknowledged: Beacon blink 2s/30s)
MEDIUM: Beacon blink 2s/30s (acknowledged: OFF)
LOW: No relay action
Implements intelligent blinking state management to prevent restart cycles
Definition at line 513 of file TemperatureController.cpp.
References _blueLedState, _greenLedState, _redLedState, _relay1Mode, _relay1State, _relay2Mode, _relay2State, _relay3Mode, _relay3State, _yellowLedState, ACKNOWLEDGED, ACTIVE, AUTO, FORCE_OFF, FORCE_ON, getAlarmCount(), indicator, LoggerManager::info(), PRIORITY_CRITICAL, PRIORITY_HIGH, PRIORITY_LOW, and PRIORITY_MEDIUM.
Referenced by setRelayControlMode(), and update().
handleCriticalAlarms()
void TemperatureController::handleCriticalAlarms ()
Handle critical priority alarms.
Implements specific behavior for critical alarms
Definition at line 1601 of file TemperatureController.cpp.
handleHighPriorityAlarms()
void TemperatureController::handleHighPriorityAlarms ()
Handle high priority alarms.
Implements specific behavior for high priority alarms
Definition at line 1610 of file TemperatureController.cpp.
handleLowPriorityAlarms()
void TemperatureController::handleLowPriorityAlarms ()
Handle low priority alarms.
Implements specific behavior for low priority alarms
Definition at line 1620 of file TemperatureController.cpp.
handleMediumPriorityAlarms()
void TemperatureController::handleMediumPriorityAlarms ()
Handle medium priority alarms.
Implements specific behavior for medium priority alarms
Definition at line 1616 of file TemperatureController.cpp.
isDS18B20Address()
bool TemperatureController::isDS18B20Address (uint8_t address) const inline private
Check if address is for DS18B20 sensor.
Parameters
[in] address Point address to check
Returns
true if DS18B20 address (0-49)
Definition at line 678 of file TemperatureController.h.
Referenced by getMeasurementPoint().
isPT1000Address()
bool TemperatureController::isPT1000Address (uint8_t address) const inline private
Check if address is for PT1000 sensor.
Parameters
[in] address Point address to check
Returns
true if PT1000 address (50-59)
Definition at line 685 of file TemperatureController.h.
Referenced by getMeasurementPoint().
readAllPoints()
void TemperatureController::readAllPoints ()
Read temperature from all configured measurement points.
Updates temperature values for all points with bound sensors
Definition at line 1058 of file TemperatureController.cpp.
References dsPoints, ptPoints, and update().
Referenced by update().
removeAlarm()
bool TemperatureController::removeAlarm (const String & configKey)
Remove alarm by configuration key.
Parameters
[in] configKey Alarm configuration key
Returns
true if alarm removed successfully
false if alarm not found
Definition at line 1560 of file TemperatureController.cpp.
References _configuredAlarms, and LoggerManager::info().
removeSensorByRom()
bool TemperatureController::removeSensorByRom (const String & romString)
Remove sensor by ROM address string.
Parameters
[in] romString ROM address as hex string (e.g., "28FF123456789ABC")
Returns
true if sensor removed successfully
false if sensor not found
Definition at line 941 of file TemperatureController.cpp.
References DS18B20, dsPoints, getBoundSensor(), registerMap, and sensors.
Referenced by discoverDS18B20Sensors().
resetMinMaxValues()
void TemperatureController::resetMinMaxValues ()
Reset min/max values for all measurement points.
Clears historical minimum and maximum temperature records
Definition at line 1358 of file TemperatureController.cpp.
References dsPoints, LoggerManager::info(), and ptPoints.
setAcknowledgedDelayCritical()
void TemperatureController::setAcknowledgedDelayCritical (unsigned long delay)
Set acknowledge delay for critical alarms.
Parameters
[in] delay Delay in milliseconds
Definition at line 1650 of file TemperatureController.cpp.
References _acknowledgedDelayCritical, and applyAcknowledgedDelaysToAlarms().
setAcknowledgedDelayHigh()
void TemperatureController::setAcknowledgedDelayHigh (unsigned long delay)
Set acknowledge delay for high priority alarms.
Parameters
[in] delay Delay in milliseconds
Definition at line 1655 of file TemperatureController.cpp.
References _acknowledgedDelayHigh, and applyAcknowledgedDelaysToAlarms().
setAcknowledgedDelayLow()
void TemperatureController::setAcknowledgedDelayLow (unsigned long delay)
Set acknowledge delay for low priority alarms.
Parameters
[in] delay Delay in milliseconds
Definition at line 1665 of file TemperatureController.cpp.
References _acknowledgedDelayLow, and applyAcknowledgedDelaysToAlarms().
setAcknowledgedDelayMedium()
void TemperatureController::setAcknowledgedDelayMedium (unsigned long delay)
Set acknowledge delay for medium priority alarms.
Parameters
[in] delay Delay in milliseconds
Definition at line 1660 of file TemperatureController.cpp.
References _acknowledgedDelayMedium, and applyAcknowledgedDelaysToAlarms().
setDeviceId()
void TemperatureController::setDeviceId (uint16_t id)
Set device ID.
Parameters
[in] id Device identifier (0-65535)
Definition at line 1366 of file TemperatureController.cpp.
References deviceId, LoggerManager::info(), and registerMap.
setFirmwareVersion()
void TemperatureController::setFirmwareVersion (uint16_t version)
Set firmware version.
Parameters
[in] version Firmware version number
Definition at line 1376 of file TemperatureController.cpp.
References firmwareVersion, and registerMap.
setMeasurementPeriod()
void TemperatureController::setMeasurementPeriod (uint16_t seconds)
Set measurement period.
Parameters
[in] seconds Time between measurements in seconds
Definition at line 1383 of file TemperatureController.cpp.
References LoggerManager::info(), and measurementPeriodSeconds.
setOneWireBusPin()
void TemperatureController::setOneWireBusPin (uint8_t pin, size_t idx)
Set OneWire bus pin.
Parameters
[in] pin GPIO pin number
[in] idx Bus index (0-3)
Definition at line 1398 of file TemperatureController.cpp.
References oneWireBusPin.
setRelayControlMode()
bool TemperatureController::setRelayControlMode (uint8_t relayNumber, RelayControlMode mode)
Set relay control mode.
Parameters
[in] relayNumber Relay number (1-3)
[in] mode Control mode (AUTO/FORCE_OFF/FORCE_ON)
Returns
true if mode set successfully
Definition at line 2183 of file TemperatureController.cpp.
References _relay1Mode, _relay2Mode, _relay3Mode, AUTO, LoggerManager::error(), handleAlarmOutputs(), indicator, and LoggerManager::info().
unbindSensorFromPoint()
bool TemperatureController::unbindSensorFromPoint (uint8_t pointAddress)
Unbind sensor from measurement point.
Parameters
[in] pointAddress Measurement point address to unbind
Returns
true if unbinding successful
false if point not found or not bound
Definition at line 1030 of file TemperatureController.cpp.
References DS18B20, LoggerManager::error(), MeasurementPoint::getBoundSensor(), Sensor::getDS18B20RomString(), getMeasurementPoint(), MeasurementPoint::getName(), Sensor::getPT1000ChipSelectPin(), Sensor::getType(), LoggerManager::info(), and MeasurementPoint::unbindSensor().
unbindSensorFromPointBySensor()
bool TemperatureController::unbindSensorFromPointBySensor (Sensor * sensor)
Unbind sensor from any measurement point it's bound to.
Parameters
[in] sensor Pointer to sensor to unbind
Returns
true if unbinding successful
false if sensor not bound to any point
Definition at line 1472 of file TemperatureController.cpp.
References dsPoints, Sensor::getName(), and ptPoints.
Referenced by bindSensorToPointByChipSelect(), and bindSensorToPointByRom().
update()
void TemperatureController::update ()
Main update function - must be called in loop()
Reads sensors, updates alarms, handles display and outputs
Note
Call this regularly for proper system operation
Definition at line 159 of file TemperatureController.cpp.
References _checkButtonPress(), handleAlarmDisplay(), handleAlarmOutputs(), indicator, lastMeasurementTime, measurementPeriodSeconds, readAllPoints(), systemInitialized, updateAlarms(), updateAllSensors(), and updateRegisterMap().
Referenced by readAllPoints().
updateAlarm()
bool TemperatureController::updateAlarm (const String & configKey, AlarmPriority priority, bool enabled)
Update alarm configuration.
Parameters
[in] configKey Alarm configuration key
[in] priority New priority level
[in] enabled Enable/disable alarm
Returns
true if update successful
false if alarm not found
Definition at line 1575 of file TemperatureController.cpp.
References findAlarm(), Alarm::setEnabled(), and Alarm::setPriority().
updateAlarms()
void TemperatureController::updateAlarms ()
Update alarm states for all measurement points.
Checks alarm conditions and updates alarm states
Definition at line 192 of file TemperatureController.cpp.
References _alarmCheckInterval, _configuredAlarms, _lastAlarmCheck, dsPoints, getActiveAlarms(), getBoundSensor(), and ptPoints.
Referenced by update().
updateAllSensors()
void TemperatureController::updateAllSensors ()
Update temperature readings for all sensors.
Forces immediate temperature reading from all sensors
Definition at line 1422 of file TemperatureController.cpp.
References DS18B20, LoggerManager::error(), getSensorBus(), and sensors.
Referenced by update().
updateRegisterMap()
void TemperatureController::updateRegisterMap ()
Update register map with current values from measurement points.
Synchronizes Modbus registers with current temperature data
Definition at line 1065 of file TemperatureController.cpp.
References dsPoints, getRelayActualState(), getRelayCommandedState(), ptPoints, and registerMap.
Referenced by update().
Field Documentation
_acknowledgedAlarmDisplayDelay
unsigned long TemperatureController::_acknowledgedAlarmDisplayDelay private
Delay before showing acknowledged alarms.
Definition at line 770 of file TemperatureController.h.
Referenced by _handleAlarmDisplayRotation(), and TemperatureController().
_acknowledgedAlarmsQueue
std::vector<Alarm*> TemperatureController::_acknowledgedAlarmsQueue private
Queue of acknowledged alarms for display.
Definition at line 766 of file TemperatureController.h.
Referenced by _checkButtonPress(), _displayNextAcknowledgedAlarm(), _handleAlarmDisplayRotation(), _handleDisplaySections(), and _updateAlarmQueues().
_acknowledgedDelayCritical
unsigned long TemperatureController::_acknowledgedDelayCritical private
Acknowledge delay for critical alarms.
Definition at line 717 of file TemperatureController.h.
Referenced by addAlarm(), applyAcknowledgedDelaysToAlarms(), getAcknowledgedDelayCritical(), and setAcknowledgedDelayCritical().
_acknowledgedDelayHigh
unsigned long TemperatureController::_acknowledgedDelayHigh private
Acknowledge delay for high priority alarms.
Definition at line 718 of file TemperatureController.h.
Referenced by addAlarm(), applyAcknowledgedDelaysToAlarms(), getAcknowledgedDelayHigh(), and setAcknowledgedDelayHigh().
_acknowledgedDelayLow
unsigned long TemperatureController::_acknowledgedDelayLow private
Acknowledge delay for low priority alarms.
Definition at line 720 of file TemperatureController.h.
Referenced by addAlarm(), applyAcknowledgedDelaysToAlarms(), getAcknowledgedDelayLow(), and setAcknowledgedDelayLow().
_acknowledgedDelayMedium
unsigned long TemperatureController::_acknowledgedDelayMedium private
Acknowledge delay for medium priority alarms.
Definition at line 719 of file TemperatureController.h.
Referenced by addAlarm(), applyAcknowledgedDelaysToAlarms(), getAcknowledgedDelayMedium(), and setAcknowledgedDelayMedium().
_activeAlarmsQueue
std::vector<Alarm*> TemperatureController::_activeAlarmsQueue private
Queue of active alarms for display rotation.
Definition at line 765 of file TemperatureController.h.
Referenced by _checkButtonPress(), _displayNextActiveAlarm(), _handleAlarmDisplayRotation(), _handleDisplaySections(), _handleSystemStatusMode(), and _updateAlarmQueues().
_alarmCheckInterval
const unsigned long TemperatureController::_alarmCheckInterval = 1000 private
Alarm check interval in milliseconds.
Definition at line 662 of file TemperatureController.h.
Referenced by updateAlarms().
_blinkOffTime
const unsigned long TemperatureController::_blinkOffTime = 30000 private
Blink off duration (30 seconds)
Definition at line 757 of file TemperatureController.h.
Referenced by _handleLowPriorityBlinking().
_blinkOnTime
const unsigned long TemperatureController::_blinkOnTime = 2000 private
Blink on duration (2 seconds)
Definition at line 756 of file TemperatureController.h.
Referenced by _handleLowPriorityBlinking().
_blueLedState
bool TemperatureController::_blueLedState = false private
Current state of blue LED.
Definition at line 728 of file TemperatureController.h.
Referenced by handleAlarmOutputs().
_buttonDebounceDelay
const unsigned long TemperatureController::_buttonDebounceDelay = 200 private
Button debounce delay in milliseconds.
Definition at line 665 of file TemperatureController.h.
_buttonPressHandled
bool TemperatureController::_buttonPressHandled private
Flag to prevent multiple triggers.
Definition at line 826 of file TemperatureController.h.
Referenced by _checkButtonPress(), and TemperatureController().
_buttonPressStartTime
unsigned long TemperatureController::_buttonPressStartTime private
Timestamp when button press started.
Definition at line 822 of file TemperatureController.h.
Referenced by _checkButtonPress(), and TemperatureController().
_configuredAlarms
std::vector<Alarm*> TemperatureController::_configuredAlarms private
Vector of configured alarm objects.
Definition at line 660 of file TemperatureController.h.
Referenced by _displayAlarmSummaryByPriority(), _displayAlarmSummaryByType(), _hasAlarmForPoint(), acknowledgeAllAlarms(), addAlarm(), applyAcknowledgedDelaysToAlarms(), clearConfiguredAlarms(), clearResolvedAlarms(), createAlarm(), ensureAlarmsForPoint(), findAlarm(), getActiveAlarms(), getAlarmByIndex(), getAlarmCount(), getAlarmCount(), getAlarmCount(), getAlarmCount(), getAlarmsForPoint(), getAlarmsJson(), getConfiguredAlarms(), getHighestPriorityAlarm(), removeAlarm(), updateAlarms(), and ~TemperatureController().
_currentAcknowledgedAlarmIndex
int TemperatureController::_currentAcknowledgedAlarmIndex private
Current index in acknowledged alarms queue.
Definition at line 768 of file TemperatureController.h.
Referenced by _checkButtonPress(), _displayNextAcknowledgedAlarm(), _handleAlarmDisplayRotation(), and TemperatureController().
_currentActiveAlarmIndex
int TemperatureController::_currentActiveAlarmIndex private
Current index in active alarms queue.
Definition at line 767 of file TemperatureController.h.
Referenced by _checkButtonPress(), _displayNextActiveAlarm(), _handleAlarmDisplayRotation(), and TemperatureController().
_currentDisplayedAlarm
Alarm* TemperatureController::_currentDisplayedAlarm private
Currently displayed alarm on OLED.
Definition at line 668 of file TemperatureController.h.
Referenced by _checkButtonPress(), _displayNextAcknowledgedAlarm(), _displayNextActiveAlarm(), _handleAlarmDisplayRotation(), clearConfiguredAlarms(), clearResolvedAlarms(), and TemperatureController().
_currentSection
DisplaySection TemperatureController::_currentSection private
Current display section.
Definition at line 816 of file TemperatureController.h.
Referenced by _checkButtonPress(), _handleDisplaySections(), _switchToSection(), and TemperatureController().
_displayingActiveAlarm
bool TemperatureController::_displayingActiveAlarm private
Flag indicating if displaying active alarm.
Definition at line 771 of file TemperatureController.h.
Referenced by _handleAlarmDisplayRotation(), and TemperatureController().
_greenLedState
bool TemperatureController::_greenLedState = false private
Current state of green LED (system OK)
Definition at line 726 of file TemperatureController.h.
Referenced by handleAlarmOutputs().
_inSystemStatusMode
bool TemperatureController::_inSystemStatusMode private
Flag indicating if in system status mode.
Definition at line 820 of file TemperatureController.h.
Referenced by TemperatureController().
_lastAlarmCheck
unsigned long TemperatureController::_lastAlarmCheck private
Timestamp of last alarm check.
Definition at line 661 of file TemperatureController.h.
Referenced by TemperatureController(), and updateAlarms().
_lastAlarmDisplayTime
unsigned long TemperatureController::_lastAlarmDisplayTime private
Last alarm display update timestamp.
Definition at line 769 of file TemperatureController.h.
Referenced by _checkButtonPress(), _displayNextAcknowledgedAlarm(), _handleAlarmDisplayRotation(), _switchToSection(), and TemperatureController().
_lastButtonPressTime
unsigned long TemperatureController::_lastButtonPressTime private
Timestamp of last button press.
Definition at line 664 of file TemperatureController.h.
Referenced by TemperatureController().
_lastButtonState
bool TemperatureController::_lastButtonState private
Previous button state for edge detection.
Definition at line 663 of file TemperatureController.h.
Referenced by _checkButtonPress(), and TemperatureController().
_lastLowPriorityBlinkTime
unsigned long TemperatureController::_lastLowPriorityBlinkTime = 0 private
Last blink state change timestamp.
Definition at line 755 of file TemperatureController.h.
Referenced by _handleLowPriorityBlinking().
_longPressThreshold
const unsigned long TemperatureController::_longPressThreshold = 3000 private
Long press threshold (3 seconds)
Definition at line 824 of file TemperatureController.h.
Referenced by _checkButtonPress().
_lowPriorityBlinkState
bool TemperatureController::_lowPriorityBlinkState = false private
Current blink state for low priority alarms.
Definition at line 754 of file TemperatureController.h.
Referenced by _handleLowPriorityBlinking().
_okDisplayStartTime
unsigned long TemperatureController::_okDisplayStartTime private
Timestamp when OK display started.
Definition at line 669 of file TemperatureController.h.
Referenced by _handleAlarmDisplayRotation(), _showOKAndTurnOffOLED(), and TemperatureController().
_previousSection
DisplaySection TemperatureController::_previousSection private
Previous section (for returning)
Definition at line 817 of file TemperatureController.h.
Referenced by _checkButtonPress(), _handleDisplaySections(), _switchToSection(), and TemperatureController().
_redLedState
bool TemperatureController::_redLedState = false private
Current state of red LED.
Definition at line 725 of file TemperatureController.h.
Referenced by handleAlarmOutputs().
_relay1Mode
RelayControlMode TemperatureController::_relay1Mode = RelayControlMode::AUTO private
Control mode for relay 1.
Definition at line 731 of file TemperatureController.h.
Referenced by getRelayControlMode(), handleAlarmOutputs(), and setRelayControlMode().
_relay1State
bool TemperatureController::_relay1State = false private
Current state of relay 1.
Definition at line 722 of file TemperatureController.h.
Referenced by forceRelayState(), getRelayActualState(), and handleAlarmOutputs().
_relay2Mode
RelayControlMode TemperatureController::_relay2Mode = RelayControlMode::AUTO private
Control mode for relay 2.
Definition at line 732 of file TemperatureController.h.
Referenced by getRelayControlMode(), handleAlarmOutputs(), and setRelayControlMode().
_relay2State
bool TemperatureController::_relay2State = false private
Current state of relay 2.
Definition at line 723 of file TemperatureController.h.
Referenced by forceRelayState(), getRelayActualState(), and handleAlarmOutputs().
_relay3Mode
RelayControlMode TemperatureController::_relay3Mode = RelayControlMode::AUTO private
Control mode for relay 3.
Definition at line 733 of file TemperatureController.h.
Referenced by getRelayControlMode(), handleAlarmOutputs(), and setRelayControlMode().
_relay3State
bool TemperatureController::_relay3State = false private
Current state of relay 3 (Modbus-only)
Definition at line 724 of file TemperatureController.h.
Referenced by forceRelayState(), getRelayActualState(), and handleAlarmOutputs().
_showingOK
bool TemperatureController::_showingOK private
Flag indicating OK status display.
Definition at line 670 of file TemperatureController.h.
Referenced by _displayNextAcknowledgedAlarm(), _displayNextActiveAlarm(), _handleAlarmDisplayRotation(), _showOKAndTurnOffOLED(), _switchToSection(), and TemperatureController().
_systemStatusModeStartTime
unsigned long TemperatureController::_systemStatusModeStartTime private
Timestamp when entered system status mode.
Definition at line 823 of file TemperatureController.h.
Referenced by _handleDisplaySections(), _switchToSection(), and TemperatureController().
_systemStatusPage
int TemperatureController::_systemStatusPage private
Current page in system status mode (0-4)
Definition at line 821 of file TemperatureController.h.
Referenced by _checkButtonPress(), _handleSystemStatusMode(), _switchToSection(), and TemperatureController().
_systemStatusTimeout
const unsigned long TemperatureController::_systemStatusTimeout = 30000 private
Auto-exit timeout (30 seconds)
Definition at line 825 of file TemperatureController.h.
Referenced by _handleDisplaySections().
_yellowLedState
bool TemperatureController::_yellowLedState = false private
Current state of yellow LED.
Definition at line 727 of file TemperatureController.h.
Referenced by handleAlarmOutputs().
chipSelectPin
uint8_t TemperatureController::chipSelectPin[4] private
Chip select pins for PT1000 sensors.
Definition at line 657 of file TemperatureController.h.
Referenced by discoverPTSensors(), getSensorBus(), and TemperatureController().
dallasSensors
DallasTemperature* TemperatureController::dallasSensors[4] private
Array of Dallas temperature sensor objects.
Definition at line 642 of file TemperatureController.h.
Referenced by discoverDS18B20Sensors(), TemperatureController(), and ~TemperatureController().
deviceId
uint16_t TemperatureController::deviceId private
Unique device identifier.
Definition at line 652 of file TemperatureController.h.
Referenced by begin(), getDeviceId(), getSystemStatusJson(), setDeviceId(), and TemperatureController().
dsPoints
MeasurementPoint TemperatureController::dsPoints[50] private
Array of DS18B20 measurement points.
Definition at line 645 of file TemperatureController.h.
Referenced by applyConfigFromRegisterMap(), applyConfigToRegisterMap(), getDS18B20Point(), getMeasurementPoint(), getPointsJson(), getSensorsJson(), readAllPoints(), removeSensorByRom(), resetMinMaxValues(), TemperatureController(), unbindSensorFromPointBySensor(), updateAlarms(), and updateRegisterMap().
firmwareVersion
uint16_t TemperatureController::firmwareVersion private
Firmware version number.
Definition at line 653 of file TemperatureController.h.
Referenced by begin(), getFirmwareVersion(), getSystemStatusJson(), setFirmwareVersion(), and TemperatureController().
indicator
IndicatorInterface& TemperatureController::indicator private
Reference to indicator interface for display/LED control.
Definition at line 640 of file TemperatureController.h.
Referenced by _checkButtonPress(), _displayAlarmSummaryByPriority(), _displayAlarmSummaryByType(), _displayModbusStatus(), _displayNetworkInfo(), _displayNextAcknowledgedAlarm(), _displayNextActiveAlarm(), _displaySystemStats(), _handleAlarmDisplayRotation(), _showOKAndTurnOffOLED(), _switchToSection(), _updateNormalDisplay(), begin(), forceRelayState(), handleAlarmDisplay(), handleAlarmOutputs(), setRelayControlMode(), TemperatureController(), and update().
lastMeasurementTime
unsigned long TemperatureController::lastMeasurementTime private
Timestamp of last measurement.
Definition at line 654 of file TemperatureController.h.
Referenced by TemperatureController(), and update().
measurementPeriodSeconds
uint16_t TemperatureController::measurementPeriodSeconds private
Time between measurements in seconds.
Definition at line 651 of file TemperatureController.h.
Referenced by getMeasurementPeriod(), getSystemStatusJson(), setMeasurementPeriod(), TemperatureController(), and update().
oneWireBuses
OneWire* TemperatureController::oneWireBuses[4] private
Array of OneWire bus objects.
Definition at line 641 of file TemperatureController.h.
Referenced by TemperatureController(), and ~TemperatureController().
oneWireBusPin
uint8_t TemperatureController::oneWireBusPin[4] private
GPIO pins for OneWire buses.
Definition at line 656 of file TemperatureController.h.
Referenced by discoverDS18B20Sensors(), getOneWirePin(), getSensorBus(), setOneWireBusPin(), and TemperatureController().
ptPoints
MeasurementPoint TemperatureController::ptPoints[10] private
Array of PT1000 measurement points.
Definition at line 646 of file TemperatureController.h.
Referenced by applyConfigFromRegisterMap(), applyConfigToRegisterMap(), getMeasurementPoint(), getPointsJson(), getPT1000Point(), getSensorsJson(), readAllPoints(), resetMinMaxValues(), TemperatureController(), unbindSensorFromPointBySensor(), updateAlarms(), and updateRegisterMap().
registerMap
RegisterMap TemperatureController::registerMap private
Modbus register map for communication.
Definition at line 650 of file TemperatureController.h.
Referenced by _displayModbusStatus(), addSensor(), applyConfigFromRegisterMap(), applyConfigToRegisterMap(), begin(), discoverDS18B20Sensors(), discoverPTSensors(), getRegisterMap(), getSystemStatusJson(), removeSensorByRom(), setDeviceId(), setFirmwareVersion(), and updateRegisterMap().
sensors
std::vector<Sensor*> TemperatureController::sensors private
Vector of all discovered sensors.
Definition at line 647 of file TemperatureController.h.
Referenced by addSensor(), bindSensorToPointByBusNumber(), discoverDS18B20Sensors(), discoverPTSensors(), findSensorByChipSelect(), findSensorByRom(), getDS18B20Count(), getPT1000Count(), getSensorByIndex(), getSensorCount(), getSensorsJson(), removeSensorByRom(), updateAllSensors(), and ~TemperatureController().
systemInitialized
bool TemperatureController::systemInitialized private
System initialization flag.
Definition at line 655 of file TemperatureController.h.
Referenced by begin(), TemperatureController(), and update().
The documentation for this class was generated from the following files:
include/TemperatureController.h
src/TemperatureController.cpp