Temperature Control System: src/main.cpp File Reference
main.cpp File Reference
Main application entry point for Industrial Temperature Monitoring System.
#include <Arduino.h>
#include "TemperatureController.h"
#include "TempModbusServer.h"
#include "ConfigManager.h"
#include "IndicatorInterface.h"
#include <SPI.h>
#include "TimeManager.h"
#include "LoggerManager.h"
Macros
#define BUS1_PIN 4
OneWire bus 1 for DS18B20 sensors.
#define BUS2_PIN 5
OneWire bus 2 for DS18B20 sensors.
#define BUS3_PIN 18
OneWire bus 3 for DS18B20 sensors.
#define BUS4_PIN 19
OneWire bus 4 for DS18B20 sensors.
#define SCK_PIN 14
SPI clock pin.
#define MISO_PIN 12
SPI MISO pin.
#define MOSI_PIN 13
SPI MOSI pin.
#define CS1_PIN 32
Chip select for PT1000 sensor 1.
#define CS2_PIN 33
Chip select for PT1000 sensor 2.
#define CS3_PIN 26
Chip select for PT1000 sensor 3.
#define CS4_PIN 27
Chip select for PT1000 sensor 4.
#define CS5_PIN_TF_CARD 0
Chip select for SD card.
#define RX_PIN 22
RS485 receive pin.
#define TX_PIN 23
RS485 transmit pin.
#define DE_PIN -1
RS485 driver enable pin (-1 = not used)
#define I2C_SDA 21
I2C data pin (default, available)
#define I2C_SCL 25
I2C clock pin (alternative, GPIO 22 used by RS485)
#define PCF_INT 34
PCF8575 I/O expander interrupt pin.
Functions
void setup ()
System initialization function.
void loop ()
Main system loop.
Variables
IndicatorInterface indicator (Wire, 0x20, PCF_INT)
Indicator interface for OLED display and I/O control (I2C address 0x20)
uint8_t onwWirePins [4] = {BUS1_PIN, BUS2_PIN, BUS3_PIN, BUS4_PIN}
OneWire bus pin array for DS18B20 sensors.
uint8_t csPins [4] = {CS1_PIN, CS2_PIN, CS3_PIN, CS4_PIN}
SPI chip select pin array for PT1000 sensors.
TemperatureController controller (onwWirePins, csPins, indicator)
Main temperature controller managing all sensors and measurement points.
ConfigManager * configManager
Web-based configuration manager (dynamically allocated)
TempModbusServer * modbusServer
Modbus RTU server for industrial communication (dynamically allocated)
TimeManager timeManager (I2C_SDA, I2C_SCL)
Time manager for RTC and NTP synchronization.
LoggerManager logger (controller, timeManager, SD)
Data and event logger with SD card storage.
Detailed Description
Main application entry point for Industrial Temperature Monitoring System.
Author
Claude Code Session 20250720
Date
2025-07-20
This is the main application file that initializes and coordinates all system components including temperature sensors, web configuration, Modbus communication, and data logging.
Dependencies
TemperatureController.h for sensor management
ConfigManager.h for web-based configuration
TempModbusServer.h for Modbus RTU communication
IndicatorInterface.h for OLED display and I/O control
TimeManager.h for RTC and NTP time synchronization
LoggerManager.h for data and event logging
Hardware Requirements
ESP32-WROVER module
DS18B20 temperature sensors on 4 OneWire buses
PT1000 sensors via MAX31865 on SPI
PCF8575 I/O expander for indicator control
SH1106 OLED display
DS3231 RTC module
SD card for data logging
RS485 interface for Modbus communication
Definition in file main.cpp.
Macro Definition Documentation
BUS1_PIN
#define BUS1_PIN 4
OneWire bus 1 for DS18B20 sensors.
Definition at line 42 of file main.cpp.
BUS2_PIN
#define BUS2_PIN 5
OneWire bus 2 for DS18B20 sensors.
Definition at line 43 of file main.cpp.
BUS3_PIN
#define BUS3_PIN 18
OneWire bus 3 for DS18B20 sensors.
Definition at line 44 of file main.cpp.
BUS4_PIN
#define BUS4_PIN 19
OneWire bus 4 for DS18B20 sensors.
Definition at line 45 of file main.cpp.
CS1_PIN
#define CS1_PIN 32
Chip select for PT1000 sensor 1.
Definition at line 53 of file main.cpp.
Referenced by setup().
CS2_PIN
#define CS2_PIN 33
Chip select for PT1000 sensor 2.
Definition at line 54 of file main.cpp.
Referenced by setup().
CS3_PIN
#define CS3_PIN 26
Chip select for PT1000 sensor 3.
Definition at line 55 of file main.cpp.
Referenced by setup().
CS4_PIN
#define CS4_PIN 27
Chip select for PT1000 sensor 4.
Definition at line 56 of file main.cpp.
Referenced by setup().
CS5_PIN_TF_CARD
#define CS5_PIN_TF_CARD 0
Chip select for SD card.
Definition at line 58 of file main.cpp.
Referenced by setup().
DE_PIN
#define DE_PIN -1
RS485 driver enable pin (-1 = not used)
Definition at line 63 of file main.cpp.
Referenced by setup().
I2C_SCL
#define I2C_SCL 25
I2C clock pin (alternative, GPIO 22 used by RS485)
Definition at line 67 of file main.cpp.
Referenced by setup().
I2C_SDA
#define I2C_SDA 21
I2C data pin (default, available)
Definition at line 66 of file main.cpp.
Referenced by setup().
MISO_PIN
#define MISO_PIN 12
SPI MISO pin.
Definition at line 49 of file main.cpp.
Referenced by setup().
MOSI_PIN
#define MOSI_PIN 13
SPI MOSI pin.
Definition at line 50 of file main.cpp.
Referenced by setup().
PCF_INT
#define PCF_INT 34
PCF8575 I/O expander interrupt pin.
Definition at line 68 of file main.cpp.
RX_PIN
#define RX_PIN 22
RS485 receive pin.
Definition at line 61 of file main.cpp.
Referenced by setup().
SCK_PIN
#define SCK_PIN 14
SPI clock pin.
Definition at line 48 of file main.cpp.
Referenced by setup().
TX_PIN
#define TX_PIN 23
RS485 transmit pin.
Definition at line 62 of file main.cpp.
Referenced by setup().
Function Documentation
loop()
void loop ()
Main system loop.
Continuously updates all system components including time management, configuration, temperature monitoring, and data logging
Definition at line 251 of file main.cpp.
References configManager, controller, logger, modbusServer, and timeManager.
setup()
void setup ()
System initialization function.
Initializes all hardware components, communication interfaces, and system managers in the correct sequence
Definition at line 101 of file main.cpp.
References configManager, controller, CS1_PIN, CS2_PIN, CS3_PIN, CS4_PIN, CS5_PIN_TF_CARD, DE_PIN, I2C_SCL, I2C_SDA, logger, MISO_PIN, modbusServer, MOSI_PIN, RX_PIN, SCK_PIN, timeManager, and TX_PIN.
Variable Documentation
configManager
ConfigManager* configManager
Web-based configuration manager (dynamically allocated)
Definition at line 85 of file main.cpp.
Referenced by TemperatureController::_displayModbusStatus(), TemperatureController::_displayNetworkInfo(), loop(), and setup().
controller
TemperatureController controller(onwWirePins, csPins, indicator) (onwWirePins , csPins , indicator)
Main temperature controller managing all sensors and measurement points.
Referenced by CSVConfigManager::CSVConfigManager(), LoggerManager::LoggerManager(), loop(), and setup().
csPins
uint8_t csPins[4] = {CS1_PIN, CS2_PIN, CS3_PIN, CS4_PIN}
SPI chip select pin array for PT1000 sensors.
Definition at line 79 of file main.cpp.
indicator
IndicatorInterface indicator(Wire, 0x20, PCF_INT) (Wire , 0x20 , PCF_INT)
Indicator interface for OLED display and I/O control (I2C address 0x20)
logger
LoggerManager logger(controller, timeManager, SD) (controller , timeManager , SD)
Data and event logger with SD card storage.
Referenced by loop(), and setup().
modbusServer
TempModbusServer* modbusServer
Modbus RTU server for industrial communication (dynamically allocated)
Definition at line 88 of file main.cpp.
Referenced by loop(), and setup().
onwWirePins
uint8_t onwWirePins[4] = {BUS1_PIN, BUS2_PIN, BUS3_PIN, BUS4_PIN}
OneWire bus pin array for DS18B20 sensors.
Definition at line 76 of file main.cpp.
timeManager
TimeManager timeManager(I2C_SDA, I2C_SCL) (I2C_SDA , I2C_SCL)
Time manager for RTC and NTP synchronization.
Referenced by TemperatureController::_displayNextAcknowledgedAlarm(), TemperatureController::_displayNextActiveAlarm(), LoggerManager::LoggerManager(), loop(), and setup().